import yaml from "js-yaml";
import type { FieldDef, NodeConfig, ModuleConfig } from "./types.js";
import type { KieDocsEntry } from "./schema-fetcher.js";

/** Inclusive numeric bounds parsed from a schema or its prose. */
type NumericBounds = { min?: number; max?: number };

type JsonRecord = Record<string, unknown>;
type MediaKind = "image" | "audio" | "video";

const GEMINI_OMNI_MODULE: ModuleConfig["moduleName"] = "video";

const IMAGE_REF = {
  type: "image" as const,
  uri: "",
  asset_id: null,
  data: null,
  metadata: null
};

const AUDIO_REF = {
  type: "audio" as const,
  uri: "",
  asset_id: null,
  data: null,
  metadata: null
};

const VIDEO_REF = {
  type: "video" as const,
  uri: "",
  asset_id: null,
  data: null,
  metadata: null,
  duration: null,
  format: null
};

function asRecord(value: unknown): JsonRecord | undefined {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as JsonRecord)
    : undefined;
}

function asStringArray(value: unknown): string[] | undefined {
  return Array.isArray(value) && value.every((item) => typeof item === "string")
    ? value
    : undefined;
}

function toWords(value: string): string[] {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);
}

function toPascalCase(value: string): string {
  const className = toWords(value)
    .map((word) => `${word[0]?.toUpperCase() ?? ""}${word.slice(1)}`)
    .join("");
  return /^[A-Za-z]/.test(className) ? className : `Model${className}`;
}

function toTitle(value: string): string {
  return toWords(value)
    .map((word) => `${word[0]?.toUpperCase() ?? ""}${word.slice(1)}`)
    .join(" ");
}

function sanitizeParamName(name: string): string {
  return name.trim().replace(/\s+/g, "_");
}

function fieldNameForUrl(
  paramName: string,
  kind: MediaKind,
  isList: boolean
): string {
  if (isList) {
    if (paramName === "input_urls") {
      return `${kind}s`;
    }
    if (paramName.endsWith(`_${kind}_urls`)) {
      return `${paramName.slice(0, -`${kind}_urls`.length)}${kind}s`;
    }
    if (paramName === `${kind}_urls`) {
      return `${kind}s`;
    }
    return paramName.replace(/_urls$/, "s");
  }
  return paramName.replace(/_url$/, "");
}

function isGeminiOmniDoc(entry: KieDocsEntry): boolean {
  return /gemini-omni/i.test(`${entry.title} ${entry.url}`);
}

function isOmniDirectPath(path: string): boolean {
  return /^\/api\/v1\/omni\/.+\/create$/.test(path);
}

function omniModelIdFromPath(path: string): string | null {
  if (path === "/api/v1/omni/audio/create") {
    return "gemini-omni-audio";
  }
  if (path === "/api/v1/omni/character/create") {
    return "gemini-omni-character";
  }
  return null;
}

function classNameForModelId(modelId: string, fallback: string): string {
  if (modelId === "gemini-omni-audio") {
    return "GeminiOmniAudio";
  }
  if (modelId === "gemini-omni-character") {
    return "GeminiOmniCharacter";
  }
  if (modelId === "gemini-omni-video") {
    return "GeminiOmniVideo";
  }
  // Some docs pages carry an autogenerated operationId ("playground-252"),
  // which would name the node after the docs page instead of the model.
  if (/^playground[-_]?\d+$/i.test(fallback.trim())) {
    return toPascalCase(modelId);
  }
  return toPascalCase(fallback);
}

function moduleFromCategory(
  category: string
): ModuleConfig["moduleName"] | null {
  const lower = category.toLowerCase().replace(/\s+/g, " ");
  if (lower.includes("video models")) {
    return "video";
  }
  if (
    lower.includes("audio") ||
    lower.includes("music models") ||
    lower.includes("suno") ||
    lower.includes("elevenlabs")
  ) {
    return "audio";
  }
  if (!lower.includes("image models")) {
    return null;
  }
  return "image";
}

function outputTypeForModule(
  moduleName: ModuleConfig["moduleName"]
): NodeConfig["outputType"] {
  if (moduleName === "video") {
    return "video";
  }
  if (moduleName === "audio") {
    return "audio";
  }
  return "image";
}

function outputTypeForModelId(
  modelId: string,
  moduleName: ModuleConfig["moduleName"]
): NodeConfig["outputType"] {
  if (modelId === "gemini-omni-audio" || modelId === "gemini-omni-character") {
    return "text";
  }
  if (modelId === "gemini-omni-video") {
    return "video";
  }
  return outputTypeForModule(moduleName);
}

/** The empty media ref a media property starts at before the user picks one. */
type MediaRefDefault = typeof IMAGE_REF | typeof AUDIO_REF | typeof VIDEO_REF;

/** What a field starts at when the schema names no default. */
type FieldDefault =
  | string
  | number
  | boolean
  | null
  | FieldDefault[]
  | { [key: string]: FieldDefault };

function defaultForMedia(kind: MediaKind): MediaRefDefault {
  if (kind === "audio") {
    return AUDIO_REF;
  }
  if (kind === "video") {
    return VIDEO_REF;
  }
  return IMAGE_REF;
}

function inferMediaKind(name: string, schema: JsonRecord): MediaKind | null {
  const lowerName = name.toLowerCase();
  if (/image_urls?|^images?$|_image/.test(lowerName)) {
    return "image";
  }
  if (/video_urls?|video_list|_video/.test(lowerName)) {
    return "video";
  }
  if (/audio_urls?|_audio/.test(lowerName)) {
    return "audio";
  }
  const text = `${name} ${String(schema.description ?? "")}`.toLowerCase();
  if (/\baudio\b|mp3|wav|aac|ogg|mpeg/.test(text)) {
    return "audio";
  }
  if (/\bvideo\b|mp4|mov|quicktime|matroska|mkv/.test(text)) {
    return "video";
  }
  if (/\bimage\b|\bframe\b|jpeg|jpg|png|webp|bmp|tiff|gif/.test(text)) {
    return "image";
  }
  return null;
}

function isVideoClipSchema(schema: JsonRecord): boolean {
  const items = asRecord(schema.items);
  if (!items) {
    return false;
  }
  const props = asRecord(items.properties);
  return !!(
    props?.url &&
    (props.start !== undefined || props.ends !== undefined)
  );
}

function cleanDescription(value: unknown): string {
  if (typeof value !== "string") {
    return "";
  }
  return value.replace(/\s+/g, " ").trim();
}

function numericValue(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value)
    ? value
    : undefined;
}

function numericBoundsFromText(text: string): NumericBounds {
  const minMatch = text.match(/\bMinimum:\s*(-?\d+(?:\.\d+)?)/i);
  const maxMatch = text.match(/\bMaximum:\s*(-?\d+(?:\.\d+)?)/i);
  if (minMatch || maxMatch) {
    const bounds: NumericBounds = {};
    if (minMatch) {
      bounds.min = Number(minMatch[1]);
    }
    if (maxMatch) {
      bounds.max = Number(maxMatch[1]);
    }
    return bounds;
  }

  const rangeMatch = text.match(
    /\b(?:Range|Duration|Length)\b[^.\n\r]*?(?:\[|\(|:)?\s*(-?\d+(?:\.\d+)?)\s*(?:,|to|-|~)\s*(-?\d+(?:\.\d+)?)/i
  );
  if (rangeMatch) {
    return { min: Number(rangeMatch[1]), max: Number(rangeMatch[2]) };
  }
  return {};
}

function boundsForSchema(schema: JsonRecord): NumericBounds {
  const descriptionBounds = numericBoundsFromText(
    cleanDescription(schema.description)
  );
  return {
    min:
      numericValue(schema.minimum) ??
      numericValue(schema.minLength) ??
      numericValue(schema.minItems) ??
      descriptionBounds.min,
    max:
      numericValue(schema.maximum) ??
      numericValue(schema.maxLength) ??
      numericValue(schema.maxItems) ??
      descriptionBounds.max
  };
}

function applyBounds(field: FieldDef, schema: JsonRecord): void {
  const bounds = boundsForSchema(schema);
  if (bounds.min !== undefined) {
    field.min = bounds.min;
  }
  if (bounds.max !== undefined) {
    field.max = bounds.max;
  }
}

function coerceDefault(
  schema: JsonRecord,
  type: FieldDef["type"]
): FieldDefault {
  if (type === "image" || type === "audio" || type === "video") {
    return defaultForMedia(type);
  }
  if (type.startsWith("list[")) {
    return [];
  }
  if (schema.default !== undefined) {
    // SAFETY: `schema` is a JSON-decoded API schema, so its `default` is a
    // JSON value.
    return schema.default as FieldDefault;
  }
  if (type === "bool") {
    return false;
  }
  if (type === "int" || type === "float") {
    return 0;
  }
  return "";
}

function mapField(
  paramName: string,
  schema: JsonRecord,
  required: boolean
): {
  field: FieldDef;
  upload?: NonNullable<NodeConfig["uploads"]>[number];
  paramName?: string;
} | null {
  if (schema.deprecated === true) {
    return null;
  }

  const sourceName = sanitizeParamName(paramName);
  const schemaType = String(schema.type ?? "string");
  const enumValues = asStringArray(schema.enum);
  const isArray = schemaType === "array";
  const itemSchema = asRecord(schema.items) ?? {};
  const isUrlArray =
    isArray &&
    (sourceName.endsWith("_urls") ||
      itemSchema.format === "uri" ||
      cleanDescription(schema.description).includes("asset://"));
  const isUrl =
    schemaType === "string" &&
    (sourceName.endsWith("_url") || schema.format === "uri");
  const isIdArray =
    isArray &&
    sourceName.endsWith("_ids") &&
    String(itemSchema.type ?? "string") === "string" &&
    itemSchema.format !== "uri";

  if (isIdArray) {
    const field: FieldDef = {
      name: sourceName,
      type: "list[str]",
      default: [],
      title: toTitle(sourceName),
      description: cleanDescription(schema.description),
      required
    };
    applyBounds(field, schema);
    return { field };
  }

  if (isArray && (sourceName === "video_list" || isVideoClipSchema(schema))) {
    const field: FieldDef = {
      name: "video_list",
      type: "list[video]",
      default: [],
      title: "Video List",
      description: cleanDescription(schema.description),
      required
    };
    applyBounds(field, schema);
    return {
      field,
      upload: {
        field: "video_list",
        kind: "video",
        isList: true,
        isVideoClip: true,
        paramName: "video_list"
      }
    };
  }

  const mediaKind =
    isUrl || isUrlArray ? inferMediaKind(sourceName, schema) : null;

  if (mediaKind) {
    const fieldName = fieldNameForUrl(sourceName, mediaKind, isUrlArray);
    const fieldType = isUrlArray
      ? (`list[${mediaKind}]` as FieldDef["type"])
      : mediaKind;
    const field: FieldDef = {
      name: fieldName,
      type: fieldType,
      default: coerceDefault(schema, fieldType),
      title: toTitle(fieldName),
      description: cleanDescription(schema.description),
      required
    };
    applyBounds(field, schema);
    const upload: NonNullable<NodeConfig["uploads"]>[number] = {
      field: fieldName,
      kind: mediaKind,
      paramName: sourceName
    };
    if (isUrlArray) {
      upload.isList = true;
    }
    return { field, upload };
  }

  let type: FieldDef["type"];
  if (enumValues?.length) {
    type = "enum";
  } else if (schemaType === "boolean") {
    type = "bool";
  } else if (schemaType === "integer") {
    type = "int";
  } else if (schemaType === "number") {
    type = "float";
  } else if (schemaType === "array") {
    type = "list[image]";
  } else {
    type = "str";
  }

  const field: FieldDef = {
    name: sourceName,
    type,
    default: coerceDefault(schema, type),
    title: toTitle(sourceName),
    description: cleanDescription(schema.description),
    required
  };
  if (enumValues?.length) {
    field.values = enumValues;
  }
  applyBounds(field, schema);
  return { field };
}

/**
 * Read the page's OpenAPI YAML block. Descriptions inside the spec sometimes
 * embed their own fenced examples (```json …```), always indented; only the
 * block's own closing fence sits at column 0. Matching the first ``` of any
 * kind truncates the spec mid-operation, and the half-document still parses as
 * YAML — the model then drops out of the manifest with no error.
 */
function extractOpenApi(markdown: string): JsonRecord | null {
  const match = markdown.match(/```ya?ml\s*\n([\s\S]*?)\n```[ \t]*(?:\n|$)/i);
  if (!match) {
    return null;
  }
  const parsed = yaml.load(match[1]) as unknown;
  return asRecord(parsed) ?? null;
}

function firstPostOperation(
  openApi: JsonRecord,
  entry: KieDocsEntry
): { path: string; operation: JsonRecord } | null {
  const paths = asRecord(openApi.paths);
  if (!paths) {
    return null;
  }

  if (/gemini-omni-audio/i.test(`${entry.title} ${entry.url}`)) {
    const omni = asRecord(paths["/api/v1/omni/audio/create"]);
    const omniPost = asRecord(omni?.post);
    if (omniPost) {
      return { path: "/api/v1/omni/audio/create", operation: omniPost };
    }
  }

  if (/gemini-omni-character/i.test(`${entry.title} ${entry.url}`)) {
    const omni = asRecord(paths["/api/v1/omni/character/create"]);
    const omniPost = asRecord(omni?.post);
    if (omniPost) {
      return { path: "/api/v1/omni/character/create", operation: omniPost };
    }
  }

  const createTask = asRecord(paths["/api/v1/jobs/createTask"]);
  const createTaskPost = asRecord(createTask?.post);
  if (createTaskPost) {
    return { path: "/api/v1/jobs/createTask", operation: createTaskPost };
  }
  for (const [path, pathItem] of Object.entries(paths)) {
    const operation = asRecord(asRecord(pathItem)?.post);
    if (operation) {
      return { path, operation };
    }
  }
  return null;
}

function requestSchema(operation: JsonRecord): JsonRecord | null {
  const requestBody = asRecord(operation.requestBody);
  const content = asRecord(requestBody?.content);
  const json = asRecord(content?.["application/json"]);
  return asRecord(json?.schema) ?? null;
}

function inputSchema(schema: JsonRecord): JsonRecord | null {
  const properties = asRecord(schema.properties);
  return asRecord(properties?.input) ?? null;
}

/**
 * Flatten the properties of a request schema, pulling in the branches of a
 * `oneOf`/`anyOf` union. Suno endpoints describe mutually exclusive input modes
 * that way (separate by `taskId`+`audioId` or by `audioUrl`), and reading only
 * the top-level `properties` drops every field the union carries. A field takes
 * the requiredness of the first branch that declares it, so the node's primary
 * input mode — the first documented branch — stays a complete set of inputs.
 */
function flattenProperties(schema: JsonRecord): {
  properties: JsonRecord;
  required: Set<string>;
} {
  const properties: JsonRecord = { ...(asRecord(schema.properties) ?? {}) };
  const required = new Set(asStringArray(schema.required) ?? []);
  for (const key of ["oneOf", "anyOf"] as const) {
    const branches = schema[key];
    if (!Array.isArray(branches)) {
      continue;
    }
    let isPrimaryBranch = true;
    for (const branch of branches) {
      const branchRecord = asRecord(branch);
      const branchProperties = asRecord(branchRecord?.properties);
      if (!branchRecord || !branchProperties) {
        continue;
      }
      const branchRequired = new Set(
        asStringArray(branchRecord.required) ?? []
      );
      for (const [name, value] of Object.entries(branchProperties)) {
        if (name in properties) {
          continue;
        }
        properties[name] = value;
        if (isPrimaryBranch && branchRequired.has(name)) {
          required.add(name);
        }
      }
      isPrimaryBranch = false;
    }
  }
  return { properties, required };
}

function modelIdFromSchema(schema: JsonRecord): string | null {
  const properties = asRecord(schema.properties);
  const model = asRecord(properties?.model);
  const enumValues = asStringArray(model?.enum);
  if (enumValues?.[0]) {
    return enumValues[0];
  }
  return typeof model?.default === "string" ? model.default : null;
}

export class KieSchemaParser {
  parse(markdown: string, entry: KieDocsEntry): NodeConfig | null {
    const omniDoc = isGeminiOmniDoc(entry);
    let moduleName = moduleFromCategory(entry.category);
    if (!moduleName && omniDoc) {
      moduleName = GEMINI_OMNI_MODULE;
    }
    if (!moduleName) {
      return null;
    }
    const openApi = extractOpenApi(markdown);
    if (!openApi) {
      return null;
    }
    const post = firstPostOperation(openApi, entry);
    if (!post) {
      return null;
    }
    const schema = requestSchema(post.operation);
    if (!schema) {
      return null;
    }
    const isCreateTask = post.path === "/api/v1/jobs/createTask";
    const useOmniDirect = isOmniDirectPath(post.path);
    if (!isCreateTask && moduleName !== "audio" && !useOmniDirect) {
      return null;
    }
    const input = isCreateTask ? inputSchema(schema) : schema;
    const modelId =
      (isCreateTask
        ? modelIdFromSchema(schema)
        : omniModelIdFromPath(post.path)) ??
      String(post.operation.operationId ?? post.path.replace(/^\//, ""));
    if (!input) {
      return null;
    }
    if (!modelId) {
      return null;
    }

    const { properties: inputProperties, required: requiredFields } =
      flattenProperties(input);
    const fields: FieldDef[] = [];
    const uploads: NonNullable<NodeConfig["uploads"]> = [];
    const paramNames: Record<string, string> = {};

    for (const [rawName, rawSchema] of Object.entries(inputProperties)) {
      if (
        ["callBackUrl", "callback_url", "callbackUrl"].includes(rawName.trim())
      ) {
        continue;
      }
      const propertySchema = asRecord(rawSchema);
      if (!propertySchema) {
        continue;
      }
      const mapped = mapField(
        rawName,
        propertySchema,
        requiredFields.has(rawName.trim())
      );
      if (!mapped) {
        continue;
      }
      fields.push(mapped.field);
      if (mapped.upload) {
        uploads.push(mapped.upload);
      }
      if (mapped.paramName && mapped.paramName !== mapped.field.name) {
        paramNames[mapped.field.name] = mapped.paramName;
      }
    }

    const outputType = outputTypeForModelId(modelId, moduleName);
    const className = classNameForModelId(
      modelId,
      String(post.operation.operationId ?? entry.title)
    );
    const description = `${entry.title} via Kie.ai.\n\n    kie, ${moduleName}, ai\n\n    ${entry.summary || cleanDescription(post.operation.summary)}`;
    const validation = fields
      .filter(
        (field) =>
          field.required && (field.type === "str" || field.type === "enum")
      )
      .map((field) => ({
        field: field.name,
        rule: "not_empty" as const,
        message: `${field.title ?? field.name} is required`
      }));

    const omniModule = modelId.startsWith("gemini-omni-")
      ? GEMINI_OMNI_MODULE
      : undefined;

    // Built in two halves so the emitted config keeps the key order the
    // checked-in `configs/*.ts` files were generated with.
    const execution: Partial<NodeConfig> = {};
    if (omniModule) {
      execution.moduleName = omniModule;
    }
    if (moduleName === "audio" && !isCreateTask && !useOmniDirect) {
      execution.useSuno = true;
      execution.sunoEndpoint = post.path;
    }
    if (useOmniDirect) {
      execution.useOmniDirect = true;
      execution.submitEndpoint = post.path;
      execution.responseIdKey =
        post.path === "/api/v1/omni/audio/create" ? "audioId" : "characterId";
    }

    const extras: Partial<NodeConfig> = {};
    if (uploads.length) {
      extras.uploads = uploads;
    }
    if (Object.keys(paramNames).length) {
      extras.paramNames = paramNames;
    }
    if (validation.length) {
      extras.validation = validation;
    }

    return {
      className,
      modelId,
      title: entry.title,
      description,
      outputType,
      ...execution,
      fields,
      ...extras
    };
  }
}
