import { app, Notification } from "electron";
import { autoUpdater, ProgressInfo, UpdateInfo } from "electron-updater";
import log from "electron-log";
import path from "path";
import fs from "fs";
import { logMessage } from "./logger";
import { getMainWindow } from "./state";
import { IpcChannels } from "./types.d";
import { readSettings, readSettingsAsync } from "./settings";

let updateAvailable: boolean = false;

/**
 * Auto-updater Module
 *
 * This module handles automatic updates for the Nodetool application using electron-updater.
 * It connects to GitHub releases to check for and download new versions of the application.
 *
 * Key Features:
 * - Automatically checks for updates when the app starts
 * - Downloads updates in the background
 * - Notifies the user through the main window when updates are available
 * - Provides download progress information
 * - Handles update errors gracefully
 *
 * Update Process:
 * 1. Checks GitHub releases for new versions
 * 2. If an update is found, notifies the user with the new version and release URL
 * 3. Downloads the update in the background, showing progress
 * 4. Once downloaded, notifies the user that the update is ready
 *
 * Configuration:
 * - Updates are only checked in packaged mode (not in development)
 * - Updates are fetched from the nodetool-ai/nodetool GitHub repository
 * - Update cache is stored in "nodetool-updater" directory
 *
 * Error Handling:
 * - Gracefully handles missing app-update.yml file
 * - Logs warnings instead of crashing
 * - Skips auto-update when not in packaged mode
 */

/**
 * Checks if the app-update.yml file exists in the expected location
 * This file is required by electron-updater and is generated by electron-builder
 * @returns true if the file exists, false otherwise
 */
function isAppUpdateConfigPresent(): boolean {
  try {
    // In packaged apps, the app-update.yml is in the resources directory (next to app.asar)
    // The exact location varies by platform but is always at process.resourcesPath
    const resourcesPath = process.resourcesPath;
    const appUpdateYmlPath = path.join(resourcesPath, "app-update.yml");
    
    // Normalize path to handle any Windows path issues (e.g., \r or other control characters)
    const normalizedPath = path.normalize(appUpdateYmlPath);
    
    const exists = fs.existsSync(normalizedPath);
    if (!exists) {
      logMessage(
        `app-update.yml not found at expected path: ${normalizedPath}`,
        "warn"
      );
    }
    return exists;
  } catch (err) {
    logMessage(
      `Error checking for app-update.yml: ${(err as Error).message}`,
      "warn"
    );
    return false;
  }
}

/**
 * Checks if an error is related to missing app-update.yml configuration file
 * @param err - The error to check
 * @returns true if the error indicates a missing app-update.yml file
 */
function isMissingAppUpdateConfigError(err: Error): boolean {
  return err.message.includes("ENOENT") && err.message.includes("app-update.yml");
}

/**
 * Checks if auto-updates are enabled in settings.
 * Auto-updates are opt-in by default (disabled unless explicitly enabled).
 * @returns Promise resolving to true if auto-updates are enabled, false otherwise
 */
async function isAutoUpdatesEnabledAsync(): Promise<boolean> {
  try {
    const settings = await readSettingsAsync();
    // Auto-updates are opt-in, so default to false if not set
    return settings.autoUpdatesEnabled === true;
  } catch (err) {
    logMessage(
      `Error reading auto-updates setting: ${(err as Error).message}`,
      "warn"
    );
    return false;
  }
}

/**
 * Sets up the auto-updater
 */
async function setupAutoUpdater(): Promise<void> {
  // Skip auto-update in development mode
  if (!app.isPackaged) {
    logMessage("Skipping auto-updater in development mode");
    return;
  }

  // Check if auto-updates are enabled (opt-in)
  const autoUpdateEnabled = await isAutoUpdatesEnabledAsync();
  if (!autoUpdateEnabled) {
    logMessage("Auto-updates disabled by user preference (opt-in required)");
    return;
  }

  // Check if the required app-update.yml file exists
  // This file is generated by electron-builder and is required by electron-updater
  if (!isAppUpdateConfigPresent()) {
    logMessage(
      "Auto-update disabled: app-update.yml configuration file is missing. " +
      "This may occur on older installations. Please reinstall the application " +
      "from GitHub releases to enable auto-updates: " +
      "https://github.com/nodetool-ai/nodetool/releases",
      "warn"
    );
    return;
  }

  try {
    autoUpdater.setFeedURL({
      provider: "github",
      owner: "nodetool-ai",
      repo: "nodetool",
      updaterCacheDirName: "nodetool-updater",
    });

    autoUpdater.logger = log;

    autoUpdater.checkForUpdates().catch((err: Error) => {
      // Handle specific error for missing app-update.yml more gracefully
      if (isMissingAppUpdateConfigError(err)) {
        logMessage(
          "Auto-update check skipped: app-update.yml not found. " +
          "Please reinstall from GitHub releases to enable auto-updates.",
          "warn"
        );
      } else {
        logMessage(`Failed to check for updates: ${err.message}`, "warn");
      }
    });

    setupAutoUpdaterEvents();
  } catch (err) {
    // Catch any synchronous errors during setup
    logMessage(
      `Failed to initialize auto-updater: ${(err as Error).message}`,
      "warn"
    );
  }
}

/**
 * Sets up the auto-updater events
 */
function setupAutoUpdaterEvents(): void {
  autoUpdater.on("checking-for-update", () => {
    logMessage("Checking for updates...");
  });

  autoUpdater.on("update-available", async (info: UpdateInfo) => {
    try {
      logMessage(`Update available: ${info.version}`);
      updateAvailable = true;
      const mainWindow = getMainWindow();
      if (mainWindow) {
        const releaseUrl = `https://github.com/nodetool-ai/nodetool/releases/tag/v${info.version}`;
        mainWindow.webContents.send(IpcChannels.UPDATE_AVAILABLE, {
          version: info.version,
          releaseUrl,
          downloaded: false,
        });
      }

      // Show native notification
      // Note: When auto-updates are disabled, electron-updater doesn't auto-download,
      // so we direct user to open the app to download manually
      if (Notification.isSupported()) {
        const autoUpdateEnabled = await isAutoUpdatesEnabledAsync();
        const notification = new Notification({
          title: "NodeTool Update Available",
          body: autoUpdateEnabled
            ? `Version ${info.version} is available. Downloading in the background...`
            : `Version ${info.version} is available. Click to open NodeTool.`,
        });
        notification.on("click", () => {
          const win = getMainWindow();
          if (win) {
            if (win.isMinimized()) win.restore();
            win.show();
            win.focus();
          }
        });
        notification.show();
      }
    } catch (err) {
      logMessage(
        `Error handling update-available event: ${(err as Error).message}`,
        "error"
      );
    }
  });

  autoUpdater.on("update-not-available", () => {
    logMessage("No updates available");
  });

  autoUpdater.on("download-progress", (progress: ProgressInfo) => {
    try {
      const mainWindow = getMainWindow();
      if (mainWindow) {
        mainWindow.webContents.send(IpcChannels.UPDATE_PROGRESS, progress);
      }
    } catch (err) {
      logMessage(
        `Error handling download progress: ${(err as Error).message}`,
        "error"
      );
    }
  });

  autoUpdater.on("update-downloaded", async (info: UpdateInfo) => {
    try {
      logMessage(`Update downloaded: ${info.version}`);

      const mainWindow = getMainWindow();
      if (mainWindow) {
        const releaseUrl = `https://github.com/nodetool-ai/nodetool/releases/tag/v${info.version}`;
        mainWindow.webContents.send(IpcChannels.UPDATE_AVAILABLE, {
          version: info.version,
          releaseUrl,
          downloaded: true,
        });
      }

      // Show native notification
      if (Notification.isSupported()) {
        const notification = new Notification({
          title: "NodeTool Update Ready",
          body: `Version ${info.version} has been downloaded. Click to restart and install.`,
        });
        notification.on("click", () => {
          const win = getMainWindow();
          if (win) {
            if (win.isMinimized()) win.restore();
            win.show();
            win.focus();
          }
        });
        notification.show();
      }
    } catch (err) {
      logMessage(
        `Error handling update-downloaded event: ${(err as Error).message}`,
        "error"
      );
    }
  });

  autoUpdater.on("error", (err: Error) => {
    // Handle missing app-update.yml error more gracefully
    if (isMissingAppUpdateConfigError(err)) {
      logMessage(
        "Auto-update error: app-update.yml not found. " +
        "This is expected on older installations. " +
        "Please reinstall from GitHub releases to enable auto-updates.",
        "warn"
      );
      // Don't send error to window for missing config - it's not actionable by the user
      return;
    }

    logMessage(`Update error: ${err.message}`, "error");
    try {
      const mainWindow = getMainWindow();
      if (mainWindow) {
        mainWindow.webContents.send("update-error", {
          message: "Failed to check for updates. Please try again later.",
          details: err.message,
        });
      }
    } catch (sendErr) {
      logMessage(
        `Error sending update error to window: ${(sendErr as Error).message}`,
        "error"
      );
    }
  });
}

const isUpdateAvailable = () => updateAvailable;

export { setupAutoUpdater, isUpdateAvailable };
