/**
 * ComfyUIStore
 * 
 * Zustand store for managing ComfyUI backend connection and state.
 */

import { create } from "zustand";
import {
  getComfyUIService,
  ComfyUIObjectInfo,
  getDefaultComfyBaseUrl,
  normalizeComfyBaseUrl
} from "../services/ComfyUIService";
import useMetadataStore from "./MetadataStore";
import { comfyObjectInfoToMetadataMap } from "../utils/comfySchemaConverter";
import { BASE_URL } from "./BASE_URL";

// Lazy-load the bundled ComfyUI object_info snapshot.
// Generated by: npm run fetch-comfy-schema (in web/)
let bundledObjectInfoPromise: Promise<ComfyUIObjectInfo | null> | null = null;
function loadBundledObjectInfo(): Promise<ComfyUIObjectInfo | null> {
  if (!bundledObjectInfoPromise) {
    bundledObjectInfoPromise = import("../data/comfy-object-info.json")
      .then((m) => (m.default ?? m) as unknown as ComfyUIObjectInfo)
      .catch(() => null);
  }
  return bundledObjectInfoPromise;
}

export type ComfyBackendType = "local" | "runpod";

interface ComfyUIState {
  // Connection state
  isConnected: boolean;
  isConnecting: boolean;
  connectionError: string | null;
  baseUrl: string;

  // Backend selection
  backendType: ComfyBackendType;

  // RunPod state (API key is stored as a secret via SecretsStore)
  isRunpodKeyConfigured: boolean;

  // Node schema cache
  objectInfo: ComfyUIObjectInfo | null;
  isFetchingObjectInfo: boolean;
  objectInfoError: string | null;

  // Execution state
  currentPromptId: string | null;
  isExecuting: boolean;
  executionProgress: number;

  // Actions
  setBaseUrl: (url: string) => void;
  setBackendType: (type: ComfyBackendType) => void;
  setRunpodKeyConfigured: (configured: boolean) => void;
  checkConnection: () => Promise<boolean>;
  connect: () => Promise<void>;
  disconnect: () => void;
  fetchObjectInfo: (forceRefresh?: boolean) => Promise<void>;
  setCurrentPromptId: (id: string | null) => void;
  setExecuting: (isExecuting: boolean) => void;
  setExecutionProgress: (progress: number) => void;
  reset: () => void;
}

const DEFAULT_COMFY_URL = getDefaultComfyBaseUrl();

/**
 * Load ComfyUI URL from localStorage or use default
 */
function loadComfyUIUrl(): string {
  const stored = localStorage.getItem("comfyui_base_url");
  const resolved = normalizeComfyBaseUrl(stored || DEFAULT_COMFY_URL);
  if (stored !== resolved) {
    localStorage.setItem("comfyui_base_url", resolved);
  }
  return resolved;
}

/**
 * Save ComfyUI URL to localStorage
 */
function saveComfyUIUrl(url: string): void {
  localStorage.setItem("comfyui_base_url", normalizeComfyBaseUrl(url));
}

function loadBackendType(): ComfyBackendType {
  const stored = localStorage.getItem("comfyui_backend_type");
  return stored === "runpod" ? "runpod" : "local";
}

function saveBackendType(type: ComfyBackendType): void {
  localStorage.setItem("comfyui_backend_type", type);
}

// Deduplication promise for connect() — ensures concurrent calls share one request.
// After a failure, block retries for CONNECT_COOLDOWN_MS to prevent request spam
// when ComfyUI or the backend server is unreachable.
let connectInFlightPromise: Promise<void> | null = null;
let connectLastFailureTime = 0;
const CONNECT_COOLDOWN_MS = 10_000;

export const useComfyUIStore = create<ComfyUIState>((set, get) => ({
  // Initial state
  isConnected: false,
  isConnecting: false,
  connectionError: null,
  baseUrl: loadComfyUIUrl(),

  backendType: loadBackendType(),
  isRunpodKeyConfigured: false,

  objectInfo: null,
  isFetchingObjectInfo: false,
  objectInfoError: null,

  currentPromptId: null,
  isExecuting: false,
  executionProgress: 0,

  // Actions
  setBaseUrl: (url: string) => {
    const service = getComfyUIService();
    const normalizedUrl = normalizeComfyBaseUrl(url);
    service.setBaseUrl(normalizedUrl);
    saveComfyUIUrl(normalizedUrl);
    connectLastFailureTime = 0;
    set({
      baseUrl: normalizedUrl,
      isConnected: false,
      connectionError: null,
      objectInfo: null
    });
  },

  setBackendType: (type: ComfyBackendType) => {
    saveBackendType(type);
    set({ backendType: type });
  },

  setRunpodKeyConfigured: (configured: boolean) => {
    set({ isRunpodKeyConfigured: configured });
  },

  checkConnection: async () => {
    const service = getComfyUIService();
    try {
      const connected = await service.checkConnection();
      set({ isConnected: connected, connectionError: null });
      return connected;
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      set({ isConnected: false, connectionError: errorMessage });
      return false;
    }
  },

  connect: async () => {
    // Deduplicate concurrent connect() calls — return the in-flight promise
    if (connectInFlightPromise) {
      return connectInFlightPromise;
    }

    // Skip if we recently failed — prevents spam when ComfyUI is unreachable
    if (connectLastFailureTime && Date.now() - connectLastFailureTime < CONNECT_COOLDOWN_MS) {
      const msg = get().connectionError || "ComfyUI connection failed recently, waiting before retry";
      throw new Error(msg);
    }

    const doConnect = async () => {
      const { baseUrl } = get();
      const service = getComfyUIService();

      set({ isConnecting: true, connectionError: null });

      try {
        service.setBaseUrl(baseUrl);

        // Determine whether this is a local/default ComfyUI URL.
        const isLocalUrl =
          baseUrl.startsWith("/") ||
          baseUrl.includes("localhost") ||
          baseUrl.includes("127.0.0.1");



        let objectInfo: ComfyUIObjectInfo | null = null;

        if (isLocalUrl) {
          // Use bundled schema snapshot for local ComfyUI (no network request)
          objectInfo = await loadBundledObjectInfo();
          if (!objectInfo || Object.keys(objectInfo).length === 0) {
            throw new Error(
              "No bundled ComfyUI schema found. Run: cd web && npm run fetch-comfy-schema"
            );
          }
        } else {
          // Remote host (e.g. RunPod) — fetch live via backend proxy
          const proxyHost = baseUrl.replace(/\/api\/?$/, "");
          const resp = await fetch(
            `${BASE_URL}/api/comfy/object_info?host=${encodeURIComponent(proxyHost)}`
          );
          if (!resp.ok) {
            const body = await resp.json().catch(() => ({ error: `HTTP ${resp.status}` }));
            throw new Error((body as Record<string, string>).error || `HTTP ${resp.status}`);
          }
          objectInfo = await resp.json() as ComfyUIObjectInfo;
        }

        // Register ComfyUI node metadata and components
        const comfyMetadata = comfyObjectInfoToMetadataMap(objectInfo);
        const metaStore = useMetadataStore.getState();
        metaStore.setMetadata({
          ...metaStore.metadata,
          ...comfyMetadata,
        });
        // Use an existing node component as base for all comfy nodes
        const baseComponent =
          metaStore.nodeTypes["nodetool.workflows.base_node.Preview"] ||
          Object.values(metaStore.nodeTypes)[0];
        if (baseComponent) {
          for (const nodeType of Object.keys(comfyMetadata)) {
            metaStore.addNodeType(nodeType, baseComponent);
          }
        }

        set({
          objectInfo,
          isConnected: true,
          isConnecting: false,
          connectionError: null
        });

        connectLastFailureTime = 0;
        console.info(`Connected to ComfyUI at ${baseUrl}, registered ${Object.keys(comfyMetadata).length} nodes`);
      } catch (error) {
        connectLastFailureTime = Date.now();
        const errorMessage = error instanceof Error ? error.message : "Failed to connect";
        set({
          isConnected: false,
          isConnecting: false,
          connectionError: errorMessage,
          objectInfo: null
        });
        console.error("Failed to connect to ComfyUI:", error);
        throw error;
      }
    };

    connectInFlightPromise = doConnect().finally(() => {
      connectInFlightPromise = null;
    });

    return connectInFlightPromise;
  },

  disconnect: () => {
    const service = getComfyUIService();
    service.disconnectWebSocket();
    set({
      isConnected: false,
      connectionError: null,
      currentPromptId: null,
      isExecuting: false,
      executionProgress: 0
    });
  },

  fetchObjectInfo: async (forceRefresh = false) => {
    const service = getComfyUIService();

    set({ isFetchingObjectInfo: true, objectInfoError: null });

    try {
      const objectInfo = await service.fetchObjectInfo(forceRefresh);
      set({
        objectInfo,
        isFetchingObjectInfo: false,
        objectInfoError: null
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Failed to fetch object info";
      set({
        objectInfo: null,
        isFetchingObjectInfo: false,
        objectInfoError: errorMessage
      });
      throw error;
    }
  },

  setCurrentPromptId: (id: string | null) => {
    set({ currentPromptId: id });
  },

  setExecuting: (isExecuting: boolean) => {
    set({ isExecuting });
    if (!isExecuting) {
      set({ executionProgress: 0 });
    }
  },

  setExecutionProgress: (progress: number) => {
    set({ executionProgress: progress });
  },

  reset: () => {
    set({
      isConnected: false,
      isConnecting: false,
      connectionError: null,
      objectInfo: null,
      isFetchingObjectInfo: false,
      objectInfoError: null,
      currentPromptId: null,
      isExecuting: false,
      executionProgress: 0
    });
  }
}));

/**
 * Initialize ComfyUI service with stored URL
 */
export function initializeComfyUI(): void {
  const url = loadComfyUIUrl();
  const service = getComfyUIService();
  service.setBaseUrl(url);
}

