export const codeHighlightTheme = {
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-token-atrule",
    attr: "editor-token-attr",
    boolean: "editor-token-boolean",
    builtin: "editor-token-builtin",
    cdata: "editor-token-cdata",
    char: "editor-token-char",
    class: "editor-token-class",
    "class-name": "editor-token-class-name",
    comment: "editor-token-comment",
    constant: "editor-token-constant",
    deleted: "editor-token-deleted",
    doctype: "editor-token-doctype",
    entity: "editor-token-entity",
    function: "editor-token-function",
    important: "editor-token-important",
    inserted: "editor-token-inserted",
    keyword: "editor-token-keyword",
    namespace: "editor-token-namespace",
    number: "editor-token-number",
    operator: "editor-token-operator",
    prolog: "editor-token-prolog",
    property: "editor-token-property",
    punctuation: "editor-token-punctuation",
    regex: "editor-token-regex",
    selector: "editor-token-selector",
    string: "editor-token-string",
    symbol: "editor-token-symbol",
    tag: "editor-token-tag",
    url: "editor-token-url",
    variable: "editor-token-variable"
  }
};
