/**
 * The scaffolding every media generation runs inside, shared by the two
 * surfaces that generate media: the chat turn (`handleMediaGenerationMessage`)
 * and the `generate_media` RPC (`runDirectMediaGeneration`).
 *
 * Both open a {@link GenerationContext}, register the provider, wire the asset
 * model interface, attach the run cost ledger, and wrap every provider call in
 * `runGenerationWith` + `ledger.settled()` so each render is one ledger row
 * (docs/media-generation-tracking-design.md § 8, S5). That is what lives here.
 * What stays with each caller is what actually differs: which provider method
 * a mode calls, with which parameters, and what it does with the bytes.
 */

import { randomUUID } from "node:crypto";

import { createLogger } from "@nodetool-ai/config";
import { Asset } from "@nodetool-ai/models";
import { attachRunCostLedger } from "@nodetool-ai/execution";
import { ProcessingContext as GenerationContext } from "@nodetool-ai/runtime";
import type {
  BaseProvider,
  GenerationRequest,
  GenerationResult
} from "@nodetool-ai/runtime";
import type { GenerationReceipt } from "@nodetool-ai/protocol";

import { createAssetModelInterface } from "../lib/asset-model-interface.js";
import { storeAssetWithThumbnail } from "../lib/thumbnail.js";

const log = createLogger("nodetool.websocket.media-generation");

export interface GenerationRunOptions {
  userId: string;
  providerId: string;
  modelId: string;
  provider: BaseProvider;
  /** Names the surface on every ledger row this run writes. */
  origin: GenerationRequest["origin"];
  /** Chat threads scope their context; the RPC has none. */
  threadId?: string | null;
  /** Stamped on assets stored through {@link GenerationRun.storeAsset}. */
  workflowId?: string | null;
  /** Prefixes a stored asset's name, e.g. `image_1730000000000`. */
  assetNamePrefix: string;
  signal?: AbortSignal;
  /** Overrides the node type the ledger records for these rows. */
  nodeType?: () => string;
  /** The managed-provider receipt, read once the assets are stored. */
  receiptAfterPersist?: () => { cost: NonNullable<GenerationReceipt["cost"]> } | null;
  /** Called with every generation id this run opened. */
  onGenerationId?: (id: string) => void;
}

export interface GenerationRun {
  /**
   * Run one provider call inside the seam: a ledger row opened before the
   * call, closed with its cost and asset ids, and settled before returning —
   * the caller reads the ledger as soon as this answers.
   */
  generate<T>(
    capability: GenerationRequest["capability"],
    params: Record<string, unknown>,
    persist: GenerationRequest["persist"] | null,
    call: (abort: AbortSignal) => Promise<T>,
    id?: string
  ): Promise<GenerationResult<T>>;
  /** The asset the seam already persisted for one output, when it did. */
  seamAssetId(
    result: { assets: ReadonlyArray<{ asset_id?: string | null }> },
    index?: number
  ): string | null;
  /**
   * Store generated bytes as an Asset row and return its id. The fallback for
   * when the seam did not persist: a DB message stores only `asset_id`, and
   * URLs are resolved at serve time.
   */
  storeAsset(
    bytes: Uint8Array,
    contentType: string,
    ext: string
  ): Promise<string>;
}

export function createGenerationRun(
  options: GenerationRunOptions
): GenerationRun {
  const {
    userId,
    providerId,
    modelId,
    provider,
    origin,
    threadId = null,
    workflowId = null,
    assetNamePrefix,
    signal,
    nodeType,
    receiptAfterPersist,
    onGenerationId
  } = options;

  const context = new GenerationContext({
    jobId: randomUUID(),
    userId,
    threadId: threadId || null
  });
  context.registerProvider(providerId, provider);
  context.setModelInterfaces({ createAsset: createAssetModelInterface });
  const ledgerOptions: Parameters<typeof attachRunCostLedger>[1] = {
    userId,
    workflowId
  };
  if (nodeType) {
    ledgerOptions.nodeType = nodeType;
  }
  const ledger = attachRunCostLedger(context, ledgerOptions);

  return {
    async generate(capability, params, persist, call, id) {
      const result = await context.runGenerationWith(
        {
          id,
          provider: providerId,
          capability,
          model: modelId,
          params,
          origin,
          persist: persist ? { ...persist, parentId: userId } : undefined,
          signal
        },
        (_provider, abort) => call(abort),
        receiptAfterPersist ? { receiptAfterPersist } : undefined
      );
      onGenerationId?.(result.id);
      await ledger.settled();
      return result;
    },

    seamAssetId(result, index = 0) {
      return result.assets[index]?.asset_id ?? null;
    },

    async storeAsset(bytes, contentType, ext) {
      const asset = new Asset({
        user_id: userId,
        workflow_id: workflowId,
        name: `${assetNamePrefix}_${Date.now()}`,
        content_type: contentType,
        // Home, the same folder an upload lands in. A null parent is
        // unreachable from the folder the asset browser opens on.
        parent_id: userId
      });
      await storeAssetWithThumbnail(
        asset.user_id,
        asset.id,
        `${asset.id}.${ext}`,
        bytes,
        contentType
      );
      asset.size = bytes.length;
      await asset.save();
      return asset.id;
    }
  };
}

const ENCODED_AUDIO_MIME_TO_EXT: Record<string, string> = {
  "audio/mpeg": "mp3",
  "audio/wav": "wav",
  "audio/ogg": "ogg",
  "audio/flac": "flac",
  "audio/aac": "aac"
};

/** Wrap raw 16-bit mono PCM in a WAV container so browsers can play it. */
export function pcmToWav(pcm: Uint8Array, sampleRate: number): Uint8Array {
  const numChannels = 1;
  const bitsPerSample = 16;
  const byteRate = sampleRate * numChannels * (bitsPerSample / 8);
  const blockAlign = numChannels * (bitsPerSample / 8);
  const header = new ArrayBuffer(44);
  const dv = new DataView(header);
  const writeStr = (pos: number, str: string) => {
    for (let i = 0; i < str.length; i++) dv.setUint8(pos + i, str.charCodeAt(i));
  };
  writeStr(0, "RIFF");
  dv.setUint32(4, 36 + pcm.byteLength, true);
  writeStr(8, "WAVE");
  writeStr(12, "fmt ");
  dv.setUint32(16, 16, true);
  dv.setUint16(20, 1, true);
  dv.setUint16(22, numChannels, true);
  dv.setUint32(24, sampleRate, true);
  dv.setUint32(28, byteRate, true);
  dv.setUint16(32, blockAlign, true);
  dv.setUint16(34, bitsPerSample, true);
  writeStr(36, "data");
  dv.setUint32(40, pcm.byteLength, true);

  const wav = new Uint8Array(44 + pcm.byteLength);
  wav.set(new Uint8Array(header), 0);
  wav.set(pcm, 44);
  return wav;
}

export interface SpeechRequest {
  text: string;
  model: string;
  voice?: string;
  speed?: number;
  /** The container the caller asked for, already validated. */
  audioFormat?: string | null;
}

export interface SpeechBytes {
  bytes: Uint8Array;
  mimeType: string;
  ext: string;
}

/**
 * Produce speech bytes from whichever path the provider supports: a
 * fully-encoded container (OpenAI, HuggingFace) when it offers one, otherwise
 * the streaming-PCM path (OpenAI, Gemini) wrapped in WAV unless the caller
 * asked for raw PCM.
 *
 * Returns null when `cancelled` went true mid-stream, so a caller that had a
 * Stop pressed never stores what it read.
 */
export async function generateSpeechBytes(
  provider: BaseProvider,
  request: SpeechRequest,
  cancelled?: () => boolean
): Promise<SpeechBytes | null> {
  const requestedFormat = request.audioFormat ?? null;
  const providerRequest = {
    text: request.text,
    model: request.model,
    voice: request.voice,
    speed: request.speed,
    audioFormat: requestedFormat ?? undefined
  };

  const encoded = await provider.textToSpeechEncoded(providerRequest);
  if (encoded) {
    const ext = ENCODED_AUDIO_MIME_TO_EXT[encoded.mimeType] ?? "flac";
    if (requestedFormat && requestedFormat !== ext && requestedFormat !== "pcm") {
      log.warn(
        "Requested audio_format not supported by provider; returning native format",
        {
          model: request.model,
          requestedFormat,
          returnedMime: encoded.mimeType
        }
      );
    }
    if (cancelled?.()) return null;
    return { bytes: encoded.data, mimeType: encoded.mimeType, ext };
  }

  const pcmChunks: Uint8Array[] = [];
  let totalBytes = 0;
  let sampleRate = 24000;
  for await (const chunk of provider.textToSpeech(providerRequest)) {
    if (cancelled?.()) return null;
    if (!chunk?.samples) continue;
    if (chunk.sampleRate) sampleRate = chunk.sampleRate;
    const copy = new Uint8Array(
      new Uint8Array(
        chunk.samples.buffer,
        chunk.samples.byteOffset,
        chunk.samples.byteLength
      )
    );
    pcmChunks.push(copy);
    totalBytes += copy.byteLength;
  }
  const merged = new Uint8Array(totalBytes);
  let offset = 0;
  for (const c of pcmChunks) {
    merged.set(c, offset);
    offset += c.byteLength;
  }
  if (cancelled?.()) return null;

  if (requestedFormat === "pcm") {
    return { bytes: merged, mimeType: "audio/pcm", ext: "pcm" };
  }
  if (requestedFormat && requestedFormat !== "wav") {
    log.warn(
      "Requested audio_format cannot be produced from streaming PCM; falling back to WAV",
      { model: request.model, requestedFormat }
    );
  }
  return {
    bytes: pcmToWav(merged, sampleRate),
    mimeType: "audio/wav",
    ext: "wav"
  };
}
