/**
 * `nodetool.game.ExportGodotProject` — the graph's last node writes a project
 * (game-prd § 5.5, criterion 6).
 *
 * The fills come from the protocol fixture and the bytes from the template's
 * own placeholders, the same setup `capabilities-godot.test.ts` uses, so the
 * exported project is one Godot can import: when a binary is present the
 * verification really runs, and when it is absent the node says so instead of
 * reporting green.
 */

import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { unzipSync } from "fflate";
import { createLocalWorkspace } from "@nodetool-ai/runtime";
import type { ProcessingContext } from "@nodetool-ai/runtime";
import { findGodot, getTemplate } from "@nodetool-ai/godot-templates";
import { filledManifest, type FilledManifest } from "@nodetool-ai/protocol";
import {
  ExportGodotProjectNode,
  GAME_EXPORT_NODES,
  type GodotVerification
} from "../src/index.js";

const fixture: FilledManifest = filledManifest.parse(
  JSON.parse(
    readFileSync(
      fileURLToPath(
        new URL(
          "../../protocol/fixtures/game-assets/platformer.filled.json",
          import.meta.url
        )
      ),
      "utf8"
    )
  )
);

const template = getTemplate("platformer");

/** The template placeholder that stands in for a slot's generated bytes. */
function placeholderFor(templateDir: string, slotId: string, kind: string): string {
  const stem = slotId.replace(/\./g, "_");
  const rel =
    kind === "spritesheet"
      ? `assets/sprites/${stem}.png`
      : kind === "tileset"
        ? `assets/tiles/${stem}.png`
        : kind === "image"
          ? `assets/images/${stem}.png`
          : `assets/audio/${stem}.wav`;
  return join(templateDir, rel);
}

let dir: string;
let bytes: Map<string, Uint8Array>;

/**
 * A run whose asset store answers the fixture's own ids. `createAsset` is
 * absent, so nothing here depends on a database.
 */
function contextFor(): ProcessingContext {
  return {
    userId: "user-game-nodes",
    workspace: createLocalWorkspace(dir),
    resolveAssetBytes: async (uri: string) => {
      const id = uri.replace(/^asset:\/\//, "").replace(/\.[a-z0-9]+$/i, "");
      return { bytes: bytes.get(id) ?? null, attempts: [] };
    }
  } as unknown as ProcessingContext;
}

/**
 * The dynamic inputs the graph feeds the export node: one checker `fill`
 * output per fixture slot, each carrying the asset the checker stored.
 */
function slotInputs(): Record<string, unknown> {
  const inputs: Record<string, unknown> = {};
  for (const slot of fixture.slots) {
    const isAudio = slot.fill.kind === "sfx" || slot.fill.kind === "music";
    const id = slot.asset.asset_id;
    bytes.set(
      id,
      new Uint8Array(
        readFileSync(placeholderFor(template.dir, slot.slot_id, slot.fill.kind))
      )
    );
    inputs[slot.slot_id] = {
      ...slot.fill,
      asset_id: id,
      uri: `asset://${id}.${isAudio ? "wav" : "png"}`
    };
  }
  return inputs;
}

type ExportResult = {
  output: { directory: string; verified: boolean };
  directory: string;
  files: string[];
  verified: boolean;
  verification: GodotVerification;
  errors: string[];
  archive: string;
};

async function runExport(
  properties: Record<string, unknown>
): Promise<ExportResult> {
  const node = new ExportGodotProjectNode();
  node.assign(properties);
  return (await node.process(contextFor())) as unknown as ExportResult;
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "game-export-"));
  bytes = new Map();
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe("nodetool.game.ExportGodotProject", () => {
  it("exports one node, tagged for the node tier only", () => {
    expect(GAME_EXPORT_NODES).toEqual([ExportGodotProjectNode]);
    expect(ExportGodotProjectNode.platforms).toEqual(["node"]);
    expect(ExportGodotProjectNode.supportsDynamicInputs).toBe(true);
  });

  it("declares every key it returns as an output slot", async () => {
    const result = await runExport({
      template: "platformer",
      name: "Blank Fox",
      verify: false,
      ...slotInputs()
    });
    expect(Object.keys(result).sort()).toEqual(
      Object.keys(ExportGodotProjectNode.metadataOutputTypes).sort()
    );
  });

  it("exports the template's placeholders when no slot is connected", async () => {
    const result = await runExport({
      template: "platformer",
      name: "Blank Fox",
      verify: false
    });
    expect(result.directory).toBe("games/blank-fox");
    const project = readFileSync(
      join(dir, "games/blank-fox/project.godot"),
      "utf8"
    );
    expect(project).toContain('config/name="Blank Fox"');
    // The template's own art is what a blank export ships (game-prd § 4.1).
    expect(existsSync(join(dir, "games/blank-fox/assets/sprites/player.png"))).toBe(
      true
    );
    expect(existsSync(join(dir, "games/blank-fox/scripts/player.gd"))).toBe(true);
    expect(result.errors).toEqual([]);
  });

  it("writes a zip beside the directory holding the whole project", async () => {
    const result = await runExport({
      template: "platformer",
      name: "Fox Letters",
      verify: false,
      ...slotInputs()
    });
    expect(result.archive).toBe("games/fox-letters.zip");
    const archive = readFileSync(join(dir, "games/fox-letters.zip"));
    const entries = Object.keys(unzipSync(new Uint8Array(archive)));
    expect(entries).toContain("fox-letters/project.godot");
    expect(entries).toContain("fox-letters/assets/sprites/player.tres");
    expect(entries.length).toBe(result.files.length);
  });

  it("writes the project the filled fixture describes, every reference resolving", async () => {
    const result = await runExport({
      template: "platformer",
      name: "Fox",
      verify: false,
      ...slotInputs()
    });
    expect(result.errors).toEqual([]);
    expect(result.files).toContain("assets/sprites/player.tres");
    const frames = readFileSync(
      join(dir, "games/fox/assets/sprites/player.tres"),
      "utf8"
    );
    expect(frames).toContain('type="SpriteFrames"');
    expect(frames).toContain('"name": &"run"');
  });

  it("keeps a slot's placeholder when nothing feeds it", async () => {
    const inputs = slotInputs();
    delete inputs["music.level"];
    delete inputs["sfx.hurt"];
    const result = await runExport({
      template: "platformer",
      name: "Fox",
      verify: false,
      ...inputs
    });
    // D27: keeping the template's audio is a choice, not a failure.
    expect(result.errors).toEqual([]);
    expect(existsSync(join(dir, "games/fox/assets/audio/music_level.wav"))).toBe(
      true
    );
  });

  it("refuses a fill for another slot, naming both", async () => {
    const inputs = slotInputs();
    inputs["title"] = inputs["bg.far"];
    await expect(
      runExport({ template: "platformer", name: "Fox", verify: false, ...inputs })
    ).rejects.toThrow(/input "title" carries a fill for slot "bg\.far"/);
  });

  it("refuses an input the template has no slot for", async () => {
    await expect(
      runExport({
        template: "platformer",
        name: "Fox",
        verify: false,
        "sfx.explode": { kind: "sfx", slot_id: "sfx.explode", seconds: 1 }
      })
    ).rejects.toThrow(/has no slot "sfx\.explode"/);
  });

  it("refuses a fill with no stored asset rather than exporting an empty file", async () => {
    const inputs = slotInputs();
    inputs["title"] = { ...(inputs["title"] as object), asset_id: null };
    await expect(
      runExport({ template: "platformer", name: "Fox", verify: false, ...inputs })
    ).rejects.toThrow(/slot "title" has no stored asset/);
  });

  it("refuses an unknown template, listing the ones it has", async () => {
    await expect(
      runExport({ template: "roguelike", name: "Fox", verify: false })
    ).rejects.toThrow(/unknown template "roguelike".*platformer/s);
  });

  it("reports why verification did not run, and never reports verified", async () => {
    const saved = process.env["GODOT_BIN"];
    const savedPath = process.env["PATH"];
    process.env["GODOT_BIN"] = join(dir, "no-such-godot");
    process.env["PATH"] = dir;
    try {
      const result = await runExport({
        template: "platformer",
        name: "Fox",
        ...slotInputs()
      });
      expect(result.verification.ran).toBe(false);
      expect(result.verification.reason).toMatch(/No Godot binary/);
      // D28: a skipped check is never green.
      expect(result.verified).toBe(false);
      expect(result.output).toEqual({ directory: "games/fox", verified: false });
    } finally {
      if (saved === undefined) delete process.env["GODOT_BIN"];
      else process.env["GODOT_BIN"] = saved;
      process.env["PATH"] = savedPath;
    }
  });

  const godot = findGodot();
  it.skipIf(!godot)(
    "imports, checks scripts and runs the smoke scene under real Godot",
    async () => {
      const result = await runExport({
        template: "platformer",
        name: "Fox",
        ...slotInputs()
      });
      expect(result.verification.ran).toBe(true);
      expect(result.verification.scripts?.every((s) => s.code === 0)).toBe(true);
      expect(result.verification.smoke?.stdout).toContain("SMOKE OK");
      expect(result.verified).toBe(true);
      expect(result.errors).toEqual([]);
    },
    180_000
  );
});
