name: nodetool-environment
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - accelerate
  - addict
  - aiofiles
  - aiohttp
  - anthropic
  - authlib
  - av
  - beautifulsoup4
  - bitsandbytes
  - black
  - boto3
  - click
  - cryptography
  - datasets
  - diffusers
  - einops
  - fastapi
  - ffmpeg
  - ffmpeg-python
  - fvcore
  - httpx
  - imageio
  - importlib-metadata
  - importlib-resources
  - isdangerous
  - joblib
  - jsonpath-ng
  - jsonschema
  - kornia
  - librosa
  - matplotlib
  - moto
  - moviepy
  - msgpack-python
  - networkx
  - numba
  - numpy
  - omegaconf
  - onnxruntime
  - openapi-pydantic
  - open-clip-torch
  - opencv
  - openai
  - pandas
  - peft
  - pillow
  - pip
  - protobuf
  - psutil
  - psycopg2
  - py3-validate-email
  - pyarrow
  - pydantic
  - pydub
  - pymemcache
  - pytesseract
  - pytest
  - python-dateutil
  - python-dotenv
  - python=3.11.10
  - python-multipart
  - pytorch-cuda=12.4
  - pytorch=
  - pyyaml
  - replicate
  - requests
  - respx
  - safetensors
  - sam2
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - selenium
  - sentence-transformers
  - sentencepiece
  - setuptools
  - six
  - sympy
  - spandrel
  - svglib
  - tensorboard
  - tiktoken
  - torchaudio
  - torchaudio=
  - torchvision
  - torchvision=
  - tqdm
  - transformers ==4.43.3
  - trimesh
  - uvicorn
  - websocket-client
  - websockets
  - wheel
  - yacs
  - zipp
  - pip:
      - dac
      - descript-audio-codec
      - huggingface-hub
      - lumaai
      - modal
      - ollama
      - pedalboard
      - torchsde
      - yapf
