name: nodetool-environment
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - conda-forge::python=3.11.10
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchaudio
  - pytorch::torchvision
  - pytorch::torchvision=
  - nvidia::cuda=12.4
  - conda-forge::accelerate
  - conda-forge::addict
  - conda-forge::aiofiles
  - conda-forge::aiohttp
  - conda-forge::anthropic
  - conda-forge::authlib
  - conda-forge::av
  - conda-forge::beautifulsoup4
  - conda-forge::black
  - conda-forge::boto3
  - conda-forge::click
  - conda-forge::cryptography
  - conda-forge::datasets
  - conda-forge::diffusers
  - conda-forge::einops
  - conda-forge::fastapi
  - conda-forge::ffmpeg
  - conda-forge::ffmpeg-python
  - conda-forge::fvcore
  - conda-forge::httpx
  - conda-forge::imageio
  - conda-forge::importlib-metadata
  - conda-forge::importlib-resources
  - conda-forge::joblib
  - conda-forge::jsonpath-ng
  - conda-forge::jsonschema
  - conda-forge::kornia
  - conda-forge::librosa
  - conda-forge::matplotlib
  - conda-forge::moto
  - conda-forge::moviepy
  - conda-forge::msgpack-python
  - conda-forge::networkx
  - conda-forge::numba
  - conda-forge::numpy
  - conda-forge::omegaconf
  - conda-forge::onnxruntime
  - conda-forge::openapi-pydantic
  - conda-forge::open-clip-torch
  - conda-forge::opencv
  - conda-forge::openai
  - conda-forge::pandas
  - conda-forge::peft
  - conda-forge::pillow
  - conda-forge::pip
  - conda-forge::protobuf
  - conda-forge::psutil
  - conda-forge::psycopg2
  - conda-forge::py3-validate-email
  - conda-forge::pyarrow
  - conda-forge::pydantic
  - conda-forge::pydub
  - conda-forge::pymemcache
  - conda-forge::pytesseract
  - conda-forge::pytest
  - conda-forge::python-dateutil
  - conda-forge::python-dotenv
  - conda-forge::python-multipart
  - conda-forge::pyyaml
  - conda-forge::replicate
  - conda-forge::requests
  - conda-forge::respx
  - conda-forge::safetensors
  - conda-forge::sam2
  - conda-forge::scikit-image
  - conda-forge::scikit-learn
  - conda-forge::scipy
  - conda-forge::seaborn
  - conda-forge::selenium
  - conda-forge::sentence-transformers
  - conda-forge::sentencepiece
  - conda-forge::setuptools
  - conda-forge::six
  - conda-forge::sympy
  - conda-forge::svglib
  - conda-forge::tensorboard
  - conda-forge::tiktoken
  - conda-forge::tqdm
  - conda-forge::transformers ==4.43.3
  - conda-forge::trimesh
  - conda-forge::uvicorn
  - conda-forge::websocket-client
  - conda-forge::websockets
  - conda-forge::wheel
  - conda-forge::yacs
  - conda-forge::zipp
  - pip:
      - bitsandbytes
      - dac
      - descript-audio-codec
      - huggingface-hub
      - lumaai
      - modal
      - ollama
      - pedalboard
      - spandrel
      - torchsde
      - yapf
