name: nodetool-environment
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - accelerate
  - aiofiles
  - aiohttp
  - av
  - beautifulsoup4
  - black
  - click
  - cryptography
  - diffusers
  - ffmpeg
  - httpx
  - imageio
  - joblib
  - librosa
  - matplotlib
  - moviepy
  - networkx
  - numba
  - numpy
  - open-clip-torch
  - onnxruntime
  - opencv
  - pandas
  - pillow
  - pip
  - protobuf
  - psutil
  - psycopg2
  - pyarrow
  - pydantic
  - pydub
  - pytest
  - python-dateutil
  - python-dotenv
  - python=3.11.10
  - pytorch=
  - pytorch-cuda=12.4
  - torchvision=
  - torchaudio=
  - pyyaml
  - requests
  - safetensors
  - scikit-image
  - scikit-learn
  - scipy
  - sentence-transformers
  - seaborn
  - selenium
  - sentencepiece
  - setuptools
  - six
  - tensorboard
  - torchaudio
  - torchvision
  - tqdm
  - trimesh
  - transformers ==4.43.3
  - uvicorn
  - wheel
  - pip:
      - addict
      - anthropic
      - authlib
      - bitsandbytes
      - boto3>=1.34.5
      - chromadb
      - dac
      - datasets
      - descript-audio-codec
      - einops
      - fastapi>=0.109.0
      - ffmpeg-python
      - freezegun
      - ftfy
      - fvcore
      - huggingface-hub
      - importlib-metadata
      - importlib-resources
      - itsdangerous
      - jsonpath-ng
      - jsonschema
      - jwt
      - kornia
      - lumaai
      - modal
      - moto[s3]
      - msgpack
      - ollama
      - omegaconf
      - openai>=1.10.0
      - openapi-pydantic
      - pedalboard
      - peft
      - pymemcache
      - pytesseract
      - python-multipart
      - replicate
      - respx
      - sam2
      - spandrel
      - svglib
      - tiktoken
      - torchsde
      - validate-email
      - websocket-client
      - websockets
      - yacs
      - yapf
      - zipp
