name: nodetool
channels:
  - https://nodetool-conda.s3.amazonaws.com
  - conda-forge
  - defaults
dependencies:
  - python=3.11.10
  - pip
  - ollama-binary
  - nodetool-web
  - pip:
      - nodetool
