/**
 * @jest-environment jsdom
 *
 * PRD § 10.7, criteria 3 and 4 — the two claims the image flow's spend rests
 * on, and both are about what does *not* happen.
 *
 * Criterion 3: refining the brief is text and nothing else. No layer is added
 * and no `generate_media` frame is sent (D4).
 *
 * Criterion 4: `Generate your image` produces exactly N layers that share a
 * prompt, a size and a model and differ only by seed — which is what makes the
 * contact sheet a comparison instead of N unrelated pictures.
 */
import { beforeEach, describe, expect, it, jest } from "@jest/globals";
import { act, renderHook } from "@testing-library/react";

const sendMock = jest.fn(async (_frame?: unknown) => {});
const subscribeMock = jest.fn(
  (_id: string, _handler: (msg: unknown) => void): (() => void) =>
    () => {}
);
jest.mock("../../../lib/websocket/GlobalWebSocketManager", () => ({
  globalWebSocketManager: {
    ensureConnection: jest.fn(async () => {}),
    send: (...args: unknown[]) => sendMock(...(args as [unknown])),
    subscribe: (...args: unknown[]) =>
      subscribeMock(...(args as [string, (msg: unknown) => void])),
    setResumeJobIdProvider: jest.fn()
  }
}));

const rpcRequest = jest.fn(
  async (
    _command: string,
    _data: Record<string, unknown>,
    _timeoutMs?: number,
    _signal?: AbortSignal
  ): Promise<Record<string, unknown>> => ({
    data: {
      subject: "a ceramic pour-over dripper",
      composition: "centred on seamless white",
      lighting: "soft window light from the left",
      style_words: "product photography, 85mm",
      negative: "hands"
    }
  })
);
jest.mock("../../../lib/websocket/rpcRequest", () => ({
  rpcRequest: (...args: unknown[]) =>
    rpcRequest(...(args as [string, Record<string, unknown>])),
  randomRequestId: () => "req-1"
}));

import { useRefineBrief } from "../useRefineBrief";
import { useGenerateVariations } from "../useGenerateVariations";
import { useSketchStore } from "../../../components/sketch/state/useSketchStore";
import { useSketchSessionStore } from "../../../stores/sketch/SketchSessionStore";
import { createDefaultDocument } from "../../../components/sketch/types";

const resetDocument = (): void => {
  act(() => {
    useSketchStore.getState().setDocument(createDefaultDocument(1024, 1024));
    useSketchSessionStore.setState({ bindings: {} } as never);
  });
};

beforeEach(() => {
  sendMock.mockReset();
  sendMock.mockResolvedValue(undefined);
  subscribeMock.mockClear();
  rpcRequest.mockClear();
  resetDocument();
});

describe("expandBrief (criterion 3)", () => {
  it("adds no layer and starts no job", async () => {
    act(() => {
      useSketchStore
        .getState()
        .setSetup({
          stage: "useCase",
          brief: "a pour-over dripper",
          use_case: "product"
        });
    });
    const layersBefore = useSketchStore.getState().document.layers.length;

    const { result } = renderHook(() => useRefineBrief());
    await act(async () => {
      expect(await result.current.expandBrief()).toEqual({ ok: true });
    });

    // The whole run is one language-model request.
    expect(rpcRequest).toHaveBeenCalledTimes(1);
    expect(rpcRequest.mock.calls[0][0]).toBe("generate_text");
    // No layer.
    expect(useSketchStore.getState().document.layers).toHaveLength(
      layersBefore
    );
    // No binding, so nothing can be regenerated by accident either.
    expect(Object.keys(useSketchSessionStore.getState().bindings)).toHaveLength(
      0
    );
    // No job: `generate_media` is the only frame that starts one.
    expect(sendMock).not.toHaveBeenCalled();

    const setup = useSketchStore.getState().document.setup;
    expect(setup?.stage).toBe("review");
    expect(setup?.refined?.subject).toBe("a ceramic pour-over dripper");
  });

  // F9: a model call outlives the stage that asked for it. An answer that
  // arrives after the creator has moved on must not replace what they are
  // reading, nor pull them back to the review.
  it("drops an answer that arrives after the creator left the stage", async () => {
    act(() => {
      useSketchStore.getState().setSetup({
        stage: "useCase",
        brief: "a pour-over dripper",
        use_case: "product"
      });
    });

    let answer: (value: Record<string, unknown>) => void = () => {};
    rpcRequest.mockImplementationOnce(
      () =>
        new Promise<Record<string, unknown>>((resolve) => {
          answer = resolve;
        })
    );

    const { result } = renderHook(() => useRefineBrief());
    let expansion: Promise<unknown> = Promise.resolve(null);
    act(() => {
      expansion = result.current.expandBrief();
    });

    // The creator goes back to the idea step while the model is still reading.
    act(() => {
      useSketchStore.getState().setSetup({ stage: "idea" });
    });

    await act(async () => {
      answer({
        data: {
          subject: "a ceramic pour-over dripper",
          composition: "centred",
          lighting: "soft",
          style_words: "85mm",
          negative: "hands"
        }
      });
      expect(await expansion).toEqual({ ok: false, error: null });
    });

    const setup = useSketchStore.getState().document.setup;
    expect(setup?.stage).toBe("idea");
    expect(setup?.refined).toBeUndefined();
    expect(result.current.error).toBeNull();
  });

  it.each(["shell", "review"])(
    "keeps the draft unchanged when %s cancels a refinement",
    async (source) => {
      act(() => {
        useSketchStore.getState().setSetup({
          stage: "useCase",
          brief: "a pour-over dripper",
          use_case: "product"
        });
      });
      let answer: (value: Record<string, unknown>) => void = () => {};
      rpcRequest.mockImplementationOnce(
        () =>
          new Promise((resolve) => {
            answer = resolve;
          })
      );
      const { result } = renderHook(() => useRefineBrief());
      const controller = new AbortController();
      let expansion: Promise<unknown> = Promise.resolve(null);
      act(() => {
        expansion = result.current.expandBrief(controller.signal);
        if (source === "shell") {
          controller.abort();
        } else {
          result.current.cancel();
        }
      });
      expect(rpcRequest.mock.calls[0][3]?.aborted).toBe(true);
      await act(async () => {
        answer({
          data: {
            subject: "a ceramic dripper",
            composition: "centred",
            lighting: "soft",
            style_words: "photography",
            negative: "hands"
          }
        });
        expect(await expansion).toEqual({ ok: false, error: null });
      });
      expect(useSketchStore.getState().document.setup?.stage).toBe("useCase");
      expect(useSketchStore.getState().document.setup?.refined).toBeUndefined();
      expect(result.current.refining).toBe(false);
      expect(result.current.error).toBeNull();
    }
  );

  it("refuses an empty brief without calling the model", async () => {
    const { result } = renderHook(() => useRefineBrief());
    await act(async () => {
      expect(await result.current.expandBrief()).toEqual({
        ok: false,
        error: "Describe the image before refining the brief."
      });
    });
    expect(rpcRequest).not.toHaveBeenCalled();
    expect(result.current.error).toBe(
      "Describe the image before refining the brief."
    );
  });
});

// F5: the flow throws the failure into the shell from the same tick the call
// resolves, before React re-renders with `error`. The outcome itself must carry
// the reason, or the button says "The model did not return a brief."
describe("expandBrief failure reason", () => {
  it("resolves with the model's refusal, not only in state", async () => {
    act(() => {
      useSketchStore.getState().setSetup({
        stage: "useCase",
        brief: "a pour-over dripper",
        use_case: "product"
      });
    });
    rpcRequest.mockRejectedValueOnce(new Error("Provider quota exceeded"));
    const { result } = renderHook(() => useRefineBrief());
    let outcome: unknown;
    await act(async () => {
      outcome = await result.current.expandBrief();
    });
    expect(outcome).toEqual({ ok: false, error: "Provider quota exceeded" });
  });
});

// O4: `Re-refine` on the review polishes the fields the creator edited instead
// of expanding the sentence from scratch over them.
describe("expandBrief with keepEdits", () => {
  const edited = {
    subject: "a matte black dripper",
    composition: "low angle",
    lighting: "",
    style_words: "film grain",
    negative: "steam"
  };

  it("sends the edited fields with the request", async () => {
    act(() => {
      useSketchStore.getState().setSetup({
        stage: "review",
        brief: "a pour-over dripper",
        use_case: "product",
        refined: edited
      });
    });
    const { result } = renderHook(() => useRefineBrief());
    await act(async () => {
      await result.current.expandBrief(undefined, { keepEdits: true });
    });
    const prompt = String(rpcRequest.mock.calls[0][1].prompt);
    expect(prompt).toContain("Subject: a matte black dripper");
    expect(prompt).toContain("Style words: film grain");
    expect(prompt).toContain("Leave out: steam");
  });

  it("leaves a first expansion unchanged", async () => {
    act(() => {
      useSketchStore.getState().setSetup({
        stage: "useCase",
        brief: "a pour-over dripper",
        use_case: "product",
        refined: edited
      });
    });
    const { result } = renderHook(() => useRefineBrief());
    await act(async () => {
      await result.current.expandBrief();
    });
    expect(String(rpcRequest.mock.calls[0][1].prompt)).not.toContain(
      "a matte black dripper"
    );
  });
});

describe("generateVariations (criterion 4)", () => {
  it("creates N layers differing only by seed", async () => {
    const { result } = renderHook(() => useGenerateVariations());
    const layersBefore = useSketchStore.getState().document.layers.length;

    await act(async () => {
      await result.current.generateVariations({
        prompt: "a ceramic dripper. centred on seamless white",
        provider: "prov",
        model: "model-1",
        width: 1024,
        height: 1024,
        aspectRatio: "1:1",
        count: 4
      });
    });

    expect(useSketchStore.getState().document.layers).toHaveLength(
      layersBefore + 4
    );
    const bindings = Object.values(useSketchSessionStore.getState().bindings);
    expect(bindings).toHaveLength(4);

    // Everything that shapes the picture is shared…
    const shared = bindings.map((binding) => ({
      kind: binding.kind,
      prompt: binding.prompt,
      provider: binding.provider,
      model: binding.model,
      width: binding.width,
      height: binding.height,
      aspectRatio: binding.aspectRatio
    }));
    expect(new Set(shared.map((entry) => JSON.stringify(entry))).size).toBe(1);

    // …and the seed is the one thing that is not.
    const seeds = bindings.map((binding) => binding.seed);
    expect(seeds.every((seed) => typeof seed === "number")).toBe(true);
    expect(new Set(seeds).size).toBe(4);

    // Each seed reaches the provider on its own request.
    const frames = sendMock.mock.calls.map(
      (call) => call[0] as { data?: Record<string, unknown> }
    );
    expect(frames).toHaveLength(4);
    expect(new Set(frames.map((frame) => frame.data?.seed)).size).toBe(4);
    expect(new Set(frames.map((frame) => frame.data?.prompt)).size).toBe(1);
  });

  it("writes the terminal stage before the first job is enqueued", async () => {
    const stagesWhenSent: (string | undefined)[] = [];
    sendMock.mockImplementation(async () => {
      stagesWhenSent.push(useSketchStore.getState().document.setup?.stage);
    });

    const { result } = renderHook(() => useGenerateVariations());
    await act(async () => {
      await result.current.generateVariations({
        prompt: "a dripper",
        provider: "prov",
        model: "model-1",
        width: 1024,
        height: 1024,
        count: 2
      });
    });

    expect(stagesWhenSent).toEqual(["done", "done"]);
    expect(useSketchStore.getState().document.setup?.variations).toBe(2);
  });
});
