/**
 * @jest-environment jsdom
 *
 * PRD § 10.7, criteria 3 and 4 — the two claims the image flow's spend rests
 * on, and both are about what does *not* happen.
 *
 * Criterion 3: refining the brief is text and nothing else. No layer is added
 * and no `generate_media` frame is sent (D4).
 *
 * Criterion 4: `Generate your image` produces exactly N layers that share a
 * prompt, a size and a model and differ only by seed — which is what makes the
 * contact sheet a comparison instead of N unrelated pictures.
 */
import { beforeEach, describe, expect, it, jest } from "@jest/globals";
import { act, renderHook } from "@testing-library/react";

const sendMock = jest.fn(async (_frame?: unknown) => {});
const subscribeMock = jest.fn(
  (_id: string, _handler: (msg: unknown) => void): (() => void) => () => {}
);
jest.mock("../../../lib/websocket/GlobalWebSocketManager", () => ({
  globalWebSocketManager: {
    ensureConnection: jest.fn(async () => {}),
    send: (...args: unknown[]) => sendMock(...(args as [unknown])),
    subscribe: (...args: unknown[]) =>
      subscribeMock(...(args as [string, (msg: unknown) => void])),
    setResumeJobIdProvider: jest.fn()
  }
}));

const rpcRequest = jest.fn(
  async (
    _command: string,
    _data: Record<string, unknown>
  ): Promise<Record<string, unknown>> => ({
    data: {
      subject: "a ceramic pour-over dripper",
      composition: "centred on seamless white",
      lighting: "soft window light from the left",
      style_words: "product photography, 85mm",
      negative: "hands"
    }
  })
);
jest.mock("../../../lib/websocket/rpcRequest", () => ({
  rpcRequest: (...args: unknown[]) =>
    rpcRequest(...(args as [string, Record<string, unknown>])),
  randomRequestId: () => "req-1"
}));

import { useRefineBrief } from "../useRefineBrief";
import { useGenerateVariations } from "../useGenerateVariations";
import { useSketchStore } from "../../../components/sketch/state/useSketchStore";
import { useSketchSessionStore } from "../../../stores/sketch/SketchSessionStore";
import { createDefaultDocument } from "../../../components/sketch/types";

const resetDocument = (): void => {
  act(() => {
    useSketchStore.getState().setDocument(createDefaultDocument(1024, 1024));
    useSketchSessionStore.setState({ bindings: {} } as never);
  });
};

beforeEach(() => {
  sendMock.mockReset();
  sendMock.mockResolvedValue(undefined);
  subscribeMock.mockClear();
  rpcRequest.mockClear();
  resetDocument();
});

describe("expandBrief (criterion 3)", () => {
  it("adds no layer and starts no job", async () => {
    act(() => {
      useSketchStore
        .getState()
        .setSetup({ stage: "useCase", brief: "a pour-over dripper", use_case: "product" });
    });
    const layersBefore = useSketchStore.getState().document.layers.length;

    const { result } = renderHook(() => useRefineBrief());
    await act(async () => {
      expect(await result.current.expandBrief()).toBe(true);
    });

    // The whole run is one language-model request.
    expect(rpcRequest).toHaveBeenCalledTimes(1);
    expect(rpcRequest.mock.calls[0][0]).toBe("generate_text");
    // No layer.
    expect(useSketchStore.getState().document.layers).toHaveLength(
      layersBefore
    );
    // No binding, so nothing can be regenerated by accident either.
    expect(
      Object.keys(useSketchSessionStore.getState().bindings)
    ).toHaveLength(0);
    // No job: `generate_media` is the only frame that starts one.
    expect(sendMock).not.toHaveBeenCalled();

    const setup = useSketchStore.getState().document.setup;
    expect(setup?.stage).toBe("review");
    expect(setup?.refined?.subject).toBe("a ceramic pour-over dripper");
  });

  it("refuses an empty brief without calling the model", async () => {
    const { result } = renderHook(() => useRefineBrief());
    await act(async () => {
      expect(await result.current.expandBrief()).toBe(false);
    });
    expect(rpcRequest).not.toHaveBeenCalled();
    expect(result.current.error).toBe(
      "Describe the image before refining the brief."
    );
  });
});

describe("generateVariations (criterion 4)", () => {
  it("creates N layers differing only by seed", async () => {
    const { result } = renderHook(() => useGenerateVariations());
    const layersBefore = useSketchStore.getState().document.layers.length;

    await act(async () => {
      await result.current.generateVariations({
        prompt: "a ceramic dripper. centred on seamless white",
        provider: "prov",
        model: "model-1",
        width: 1024,
        height: 1024,
        aspectRatio: "1:1",
        count: 4
      });
    });

    expect(useSketchStore.getState().document.layers).toHaveLength(
      layersBefore + 4
    );
    const bindings = Object.values(
      useSketchSessionStore.getState().bindings
    );
    expect(bindings).toHaveLength(4);

    // Everything that shapes the picture is shared…
    const shared = bindings.map((binding) => ({
      kind: binding.kind,
      prompt: binding.prompt,
      provider: binding.provider,
      model: binding.model,
      width: binding.width,
      height: binding.height,
      aspectRatio: binding.aspectRatio
    }));
    expect(new Set(shared.map((entry) => JSON.stringify(entry))).size).toBe(1);

    // …and the seed is the one thing that is not.
    const seeds = bindings.map((binding) => binding.seed);
    expect(seeds.every((seed) => typeof seed === "number")).toBe(true);
    expect(new Set(seeds).size).toBe(4);

    // Each seed reaches the provider on its own request.
    const frames = sendMock.mock.calls.map(
      (call) => call[0] as { data?: Record<string, unknown> }
    );
    expect(frames).toHaveLength(4);
    expect(new Set(frames.map((frame) => frame.data?.seed)).size).toBe(4);
    expect(new Set(frames.map((frame) => frame.data?.prompt)).size).toBe(1);
  });

  it("writes the terminal stage before the first job is enqueued", async () => {
    const stagesWhenSent: (string | undefined)[] = [];
    sendMock.mockImplementation(async () => {
      stagesWhenSent.push(useSketchStore.getState().document.setup?.stage);
    });

    const { result } = renderHook(() => useGenerateVariations());
    await act(async () => {
      await result.current.generateVariations({
        prompt: "a dripper",
        provider: "prov",
        model: "model-1",
        width: 1024,
        height: 1024,
        count: 2
      });
    });

    expect(stagesWhenSent).toEqual(["done", "done"]);
    expect(useSketchStore.getState().document.setup?.variations).toBe(2);
  });
});
