/**
 * The `godot` capability module — a template plus filled slots become a
 * project on disk.
 *
 * The fills come from the protocol fixture and the bytes from the template's
 * own placeholders, so the exported project is one Godot can import: when a
 * binary is present the verification really runs, and when it is absent the
 * result says so instead of reporting green.
 */

import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, readFileSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ProcessingContext } from "@nodetool-ai/runtime";
import { createLocalWorkspace } from "@nodetool-ai/runtime";
import { Asset, initTestDb } from "@nodetool-ai/models";
import { findGodot, getTemplate } from "@nodetool-ai/godot-templates";
import {
  filledManifest,
  SLOT_METADATA_KEY,
  type FilledManifest
} from "@nodetool-ai/protocol";
import { GODOT_CAPABILITIES, module as godotModule } from "../src/capabilities/godot.js";
import { UNGATED, createCapabilityRun } from "../src/capabilities/index.js";
import {
  capabilityModuleIssues,
  loadCapabilityModule
} from "../src/capabilities/registry.js";
import { toolForCapabilityName } from "../src/capabilities/lazy-tool.js";
import { permissionCategoryFor } from "../src/tools/tool-permissions.js";

const USER = "user-godot";

const fixture: FilledManifest = filledManifest.parse(
  JSON.parse(
    readFileSync(
      fileURLToPath(
        new URL(
          "../../protocol/fixtures/game-assets/platformer.filled.json",
          import.meta.url
        )
      ),
      "utf8"
    )
  )
);

const template = getTemplate("platformer");

/** The template placeholder that stands in for a slot's generated bytes. */
function placeholderFor(slotId: string, kind: string): string {
  const stem = slotId.replace(/\./g, "_");
  const rel =
    kind === "spritesheet"
      ? `assets/sprites/${stem}.png`
      : kind === "tileset"
        ? `assets/tiles/${stem}.png`
        : kind === "image"
          ? `assets/images/${stem}.png`
          : `assets/audio/${stem}.wav`;
  return join(template.dir, rel);
}

let dir: string;
let bytes: Map<string, Uint8Array>;

function contextFor(): ProcessingContext {
  return {
    userId: USER,
    workspace: createLocalWorkspace(dir),
    resolveAssetBytes: async (uri: string) => {
      const id = uri.replace(/^asset:\/\//, "").replace(/\.[a-z0-9]+$/i, "");
      return { bytes: bytes.get(id) ?? null, attempts: [] };
    }
  } as unknown as ProcessingContext;
}

const run = () => createCapabilityRun({ context: contextFor(), gate: UNGATED });

/**
 * One stored asset per fixture slot, its fill stamped, its bytes the
 * template placeholder. `audioExt` names audio assets, so a test can make
 * the filled extension differ from the placeholder's `.wav`.
 */
async function seedAssets(audioExt = "wav"): Promise<Array<{ slot_id: string; asset_id: string }>> {
  const slots: Array<{ slot_id: string; asset_id: string }> = [];
  for (const slot of fixture.slots) {
    const isAudio = slot.fill.kind === "sfx" || slot.fill.kind === "music";
    const asset = (await Asset.create({
      user_id: USER,
      name: `${slot.slot_id}.${isAudio ? audioExt : "png"}`,
      content_type: isAudio ? `audio/${audioExt}` : "image/png",
      metadata: { [SLOT_METADATA_KEY]: slot.fill }
    })) as Asset;
    bytes.set(asset.id, new Uint8Array(readFileSync(placeholderFor(slot.slot_id, slot.fill.kind))));
    slots.push({ slot_id: slot.slot_id, asset_id: asset.id });
  }
  return slots;
}

beforeEach(() => {
  initTestDb();
  dir = mkdtempSync(join(tmpdir(), "godot-cap-"));
  bytes = new Map();
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe("godot capability module", () => {
  it("is registered and drift-clean", async () => {
    const loaded = await loadCapabilityModule("godot");
    expect(loaded).toBe(godotModule);
    expect(capabilityModuleIssues("godot", loaded)).toEqual([]);
  });

  it("carries the three wire names and the gate's categories", () => {
    expect(GODOT_CAPABILITIES.map((e) => e.spec.name)).toEqual([
      "list_game_templates",
      "export_godot_project",
      "verify_godot_project"
    ]);
    for (const entry of GODOT_CAPABILITIES) {
      expect(entry.spec.category).toBe(permissionCategoryFor(entry.spec.name));
    }
  });

  it("renders as a Tool, spec for spec", () => {
    for (const entry of GODOT_CAPABILITIES) {
      const tool = toolForCapabilityName(entry.spec.name);
      expect(tool?.name).toBe(entry.spec.name);
    }
  });

  it("lists the templates with their slots", async () => {
    const result = (await run().invoke("list_game_templates", {})) as {
      templates: Array<{ id: string; slots: unknown[]; hooks: string[] }>;
    };
    const ids = result.templates.map((t) => t.id);
    expect(ids).toEqual(expect.arrayContaining(["platformer", "topdown", "shmup"]));
    const platformer = result.templates.find((t) => t.id === "platformer");
    expect(platformer?.slots).toHaveLength(8);
    expect(platformer?.hooks).toContain("scripts/player.gd");
  });
});

describe("export_godot_project", () => {
  it("refuses an unfilled manifest and names the missing slot", async () => {
    const slots = (await seedAssets()).filter((s) => s.slot_id !== "sfx.hurt");
    const result = (await run().invoke("export_godot_project", {
      template: "platformer",
      name: "Fox",
      slots,
      verify: false
    })) as { error: string; problems: Record<string, string[]> };
    expect(result.error).toMatch(/do not satisfy/);
    expect(result.problems["sfx.hurt"]).toEqual(["unfilled"]);
  });

  it("refuses an asset that carries no fill", async () => {
    const slots = await seedAssets();
    const bare = (await Asset.create({
      user_id: USER,
      name: "bare.png",
      content_type: "image/png"
    })) as Asset;
    slots[0] = { slot_id: slots[0].slot_id, asset_id: bare.id };
    const result = (await run().invoke("export_godot_project", {
      template: "platformer",
      name: "Fox",
      slots,
      verify: false
    })) as { error: string };
    expect(result.error).toMatch(/carries no slot fill/);
  });

  it("writes a project whose every res:// reference resolves", async () => {
    const slots = await seedAssets();
    const result = (await run().invoke("export_godot_project", {
      template: "platformer",
      name: "Fox Letters",
      slots,
      verify: false
    })) as {
      dir: string;
      ok: boolean;
      dangling_references: string[];
      references_rewritten: string[];
      assets_copied: string[];
    };
    expect(result.dir).toBe("godot/Fox_Letters");
    expect(result.dangling_references).toEqual([]);
    expect(result.references_rewritten).toEqual([]);
    expect(result.ok).toBe(true);

    const root = join(dir, "godot/Fox_Letters");
    const project = readFileSync(join(root, "project.godot"), "utf8");
    expect(project).toContain('config/name="Fox Letters"');
    expect(project).toContain("run/main_scene=");
    const frames = readFileSync(join(root, "assets/sprites/player.tres"), "utf8");
    expect(frames).toContain('type="SpriteFrames"');
    expect(frames).toContain('"name": &"run"');
    expect(existsSync(join(root, "assets/audio/sfx_jump.wav.import"))).toBe(true);
    expect(existsSync(join(root, "scripts/player.gd"))).toBe(true);
    expect(result.assets_copied).toContain("assets/sprites/player.png");
  });

  it("rewrites scene references when a filled audio extension differs from the placeholder", async () => {
    const slots = await seedAssets("ogg");
    const result = (await run().invoke("export_godot_project", {
      template: "platformer",
      name: "Fox",
      slots,
      verify: false
    })) as { dangling_references: string[]; references_rewritten: string[] };
    expect(result.dangling_references).toEqual([]);
    expect(result.references_rewritten.length).toBeGreaterThan(0);
    const root = join(dir, "godot/Fox");
    expect(existsSync(join(root, "assets/audio/sfx_jump.ogg"))).toBe(true);
    expect(existsSync(join(root, "assets/audio/sfx_jump.wav"))).toBe(false);
    const player = readFileSync(join(root, "scenes/player.tscn"), "utf8");
    expect(player).toContain("res://assets/audio/sfx_jump.ogg");
    expect(player).not.toContain("sfx_jump.wav");
  });

  it("reports why verification did not run when no Godot binary is present", async () => {
    const saved = process.env["GODOT_BIN"];
    const savedPath = process.env["PATH"];
    process.env["GODOT_BIN"] = join(dir, "no-such-godot");
    process.env["PATH"] = dir;
    try {
      const slots = await seedAssets();
      const result = (await run().invoke("export_godot_project", {
        template: "platformer",
        name: "Fox",
        slots
      })) as { ok: boolean; verification: { ran: boolean; reason?: string } };
      expect(result.verification.ran).toBe(false);
      expect(result.verification.reason).toMatch(/No Godot binary/);
      expect(result.ok).toBe(true);
    } finally {
      if (saved === undefined) delete process.env["GODOT_BIN"];
      else process.env["GODOT_BIN"] = saved;
      process.env["PATH"] = savedPath;
    }
  });

  const godot = findGodot();
  it.skipIf(!godot)(
    "imports, checks scripts, and runs the smoke scene under real Godot",
    async () => {
      const slots = await seedAssets();
      const result = (await run().invoke("export_godot_project", {
        template: "platformer",
        name: "Fox",
        slots
      })) as {
        ok: boolean;
        verification: {
          ran: boolean;
          ok?: boolean;
          scripts?: Array<{ script: string; code: number | null }>;
          smoke?: { code: number | null; stdout: string };
        };
      };
      expect(result.verification.ran).toBe(true);
      expect(result.verification.scripts?.every((s) => s.code === 0)).toBe(true);
      expect(result.verification.smoke?.stdout).toContain("SMOKE OK");
      expect(result.verification.ok).toBe(true);
      expect(result.ok).toBe(true);

      const verified = (await run().invoke("verify_godot_project", {
        dir: "godot/Fox"
      })) as { ok: boolean };
      expect(verified.ok).toBe(true);
    },
    180_000
  );

  it.skipIf(!godot)("fails verification after a hook script is broken", async () => {
    const slots = await seedAssets();
    await run().invoke("export_godot_project", {
      template: "platformer",
      name: "Fox",
      slots,
      verify: false
    });
    const workspace = createLocalWorkspace(dir);
    await workspace.write("godot/Fox/scripts/player.gd", "extends CharacterBody2D\nfunc _ready(:\n");
    const result = (await run().invoke("verify_godot_project", {
      dir: "godot/Fox"
    })) as { ok: boolean; verification: { scripts: Array<{ script: string; code: number | null }> } };
    expect(result.ok).toBe(false);
    const player = result.verification.scripts.find((s) => s.script.endsWith("player.gd"));
    expect(player?.code).not.toBe(0);
  }, 180_000);
});
