/**
 * Integration test for the `generate_media` RPC on the unified WebSocket.
 *
 * Regression guard: the sketch editor's direct text-to-image path must forward
 * the user-picked aspect ratio (and named resolution) to the provider. FAL's
 * image endpoints shape output via a size enum and ignore a raw {width,height}
 * dict, so without the aspect ratio the request falls back to a square default
 * — the "aspect ratio not honored" bug. This asserts the values reach
 * `textToImages` in the provider params.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { unpack } from "msgpackr";
import {
  UnifiedWebSocketRunner,
  type WebSocketConnection,
  type WebSocketReceiveFrame
} from "../src/unified-websocket-runner.js";
import type { TextToImageParams } from "@nodetool-ai/runtime";

// The RPC stores the generated bytes as an asset; make that a no-op.
vi.mock("../src/lib/thumbnail.js", () => ({
  storeAssetWithThumbnail: vi.fn(async () => undefined)
}));

vi.mock("@nodetool-ai/models", async (orig) => {
  const actual = await orig<typeof import("@nodetool-ai/models")>();
  class FakeAsset {
    id = "asset-1";
    size = 0;
    async save(): Promise<void> {}
    static find = vi.fn();
  }
  return { ...actual, Asset: FakeAsset };
});

class MockWebSocket implements WebSocketConnection {
  clientState: "connected" | "disconnected" = "connected";
  applicationState: "connected" | "disconnected" = "connected";
  sentBytes: Uint8Array[] = [];
  sentText: string[] = [];
  queue: Array<WebSocketReceiveFrame> = [];

  async accept(): Promise<void> {
    return;
  }
  async receive(): Promise<WebSocketReceiveFrame> {
    const next = this.queue.shift();
    if (!next) return { type: "websocket.disconnect" };
    return next;
  }
  async sendBytes(data: Uint8Array): Promise<void> {
    this.sentBytes.push(data);
  }
  async sendText(data: string): Promise<void> {
    this.sentText.push(data);
  }
  async close(): Promise<void> {
    this.clientState = "disconnected";
    this.applicationState = "disconnected";
  }
}

type ResolveProvider = ConstructorParameters<
  typeof UnifiedWebSocketRunner
>[0]["resolveProvider"];

async function makeRunner(
  ws: MockWebSocket,
  resolveProvider: ResolveProvider
): Promise<UnifiedWebSocketRunner> {
  const runner = new UnifiedWebSocketRunner({
    resolveExecutor: () => ({
      async process() {
        return {};
      }
    }),
    resolveProvider,
    nodeRegistry: {
      listMetadata: () => [],
      has: () => false,
      resolve: () => ({ async process() { return {}; } }),
      getMetadata: () => undefined,
      createNodeValidator: () => () => undefined
    } as never,
    apiOptions: {
      metadataRoots: [],
      registry: {} as never,
      storage: {}
    } as never,
    pythonBridge: {} as never,
    getPythonBridgeReady: () => true
  });
  await runner.connect(ws);
  return runner;
}

function decodeFrame(ws: MockWebSocket, idx: number): Record<string, unknown> {
  if (ws.sentBytes[idx]) {
    return unpack(ws.sentBytes[idx]) as Record<string, unknown>;
  }
  return JSON.parse(ws.sentText[idx]) as Record<string, unknown>;
}

async function runOne(
  ws: MockWebSocket,
  runner: UnifiedWebSocketRunner,
  frame: Record<string, unknown>
): Promise<Record<string, unknown>> {
  ws.queue.push({ type: "websocket.message", text: JSON.stringify(frame) });
  ws.queue.push({ type: "websocket.disconnect" });
  await runner.receiveMessages();
  return decodeFrame(ws, 0);
}

describe("generate_media RPC (text-to-image)", () => {
  let ws: MockWebSocket;

  beforeEach(() => {
    vi.clearAllMocks();
    ws = new MockWebSocket();
  });

  afterEach(() => {
    ws.queue.length = 0;
  });

  it("forwards aspect ratio and resolution to the provider", async () => {
    const calls: TextToImageParams[] = [];
    const provider = {
      provider: "fake",
      async textToImages(params: TextToImageParams): Promise<Uint8Array[]> {
        calls.push(params);
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      }
    };
    const runner = await makeRunner(ws, async () => provider as never);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "g-1",
      data: {
        mode: "image",
        provider: "fake",
        model: "fal-ai/flux/dev",
        prompt: "a cat",
        width: 1820,
        height: 1024,
        aspect_ratio: "16:9",
        resolution: "1K"
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(calls).toHaveLength(1);
    expect(calls[0].aspectRatio).toBe("16:9");
    expect(calls[0].resolution).toBe("1K");
    expect(calls[0].width).toBe(1820);
    expect(calls[0].height).toBe(1024);

    await runner.disconnect();
  });
});
