/**
 * Integration test for the `generate_media` RPC on the unified WebSocket.
 *
 * Regression guard: the sketch editor's direct text-to-image path must forward
 * the user-picked aspect ratio (and named resolution) to the provider. FAL's
 * image endpoints shape output via a size enum and ignore a raw {width,height}
 * dict, so without the aspect ratio the request falls back to a square default
 * — the "aspect ratio not honored" bug. This asserts the values reach
 * `textToImages` in the provider params.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { unpack } from "msgpackr";
import {
  UnifiedWebSocketRunner,
  type WebSocketConnection,
  type WebSocketReceiveFrame
} from "../src/unified-websocket-runner.js";
import { Asset } from "@nodetool-ai/models";
import type {
  TextToImageParams,
  ImageToImageParams,
  TextToVideoParams,
  ImageToVideoParams
} from "@nodetool-ai/runtime";

// The RPC stores the generated bytes as an asset; make that a no-op.
vi.mock("../src/lib/thumbnail.js", () => ({
  storeAssetWithThumbnail: vi.fn(async () => undefined)
}));

vi.mock("@nodetool-ai/models", async (orig) => {
  const actual = await orig<typeof import("@nodetool-ai/models")>();
  class FakeAsset {
    id = "asset-1";
    size = 0;
    async save(): Promise<void> {}
    static find = vi.fn();
  }
  return { ...actual, Asset: FakeAsset };
});

vi.mock("../src/lib/asset-paths.js", async (orig) => {
  const actual =
    await orig<typeof import("../src/lib/asset-paths.js")>();
  return {
    ...actual,
    retrieveAssetBytes: vi.fn(
      async (
        _adapter: unknown,
        _userId: string,
        assetId: string,
        _contentType: string
      ) => REF_BYTES[assetId] ?? null
    )
  };
});

/** Bytes served per asset id by the mocked retrieveAssetBytes. */
const REF_BYTES: Record<string, Uint8Array> = {};

const ENTITY_MARKER = {
  nodetool_entity: {
    kind: "character",
    name: "Marta",
    descriptor: "red-haired detective in a beige trench coat"
  }
};

function makeAssetRow(id: string, metadata: Record<string, unknown> | null) {
  return {
    id,
    user_id: "1",
    name: `${id}.png`,
    content_type: "image/png",
    metadata
  };
}

class MockWebSocket implements WebSocketConnection {
  clientState: "connected" | "disconnected" = "connected";
  applicationState: "connected" | "disconnected" = "connected";
  sentBytes: Uint8Array[] = [];
  sentText: string[] = [];
  queue: Array<WebSocketReceiveFrame> = [];

  async accept(): Promise<void> {
    return;
  }
  async receive(): Promise<WebSocketReceiveFrame> {
    const next = this.queue.shift();
    if (!next) return { type: "websocket.disconnect" };
    return next;
  }
  async sendBytes(data: Uint8Array): Promise<void> {
    this.sentBytes.push(data);
  }
  async sendText(data: string): Promise<void> {
    this.sentText.push(data);
  }
  async close(): Promise<void> {
    this.clientState = "disconnected";
    this.applicationState = "disconnected";
  }
}

type ResolveProvider = ConstructorParameters<
  typeof UnifiedWebSocketRunner
>[0]["resolveProvider"];

async function makeRunner(
  ws: MockWebSocket,
  resolveProvider: ResolveProvider
): Promise<UnifiedWebSocketRunner> {
  const runner = new UnifiedWebSocketRunner({
    resolveExecutor: () => ({
      async process() {
        return {};
      }
    }),
    resolveProvider,
    nodeRegistry: {
      listMetadata: () => [],
      has: () => false,
      resolve: () => ({ async process() { return {}; } }),
      getMetadata: () => undefined,
      createNodeValidator: () => () => undefined
    } as never,
    apiOptions: {
      metadataRoots: [],
      registry: {} as never,
      storage: {}
    } as never,
    pythonBridge: {} as never,
    getPythonBridgeReady: () => true
  });
  await runner.connect(ws);
  return runner;
}

function decodeFrame(ws: MockWebSocket, idx: number): Record<string, unknown> {
  if (ws.sentBytes[idx]) {
    return unpack(ws.sentBytes[idx]) as Record<string, unknown>;
  }
  return JSON.parse(ws.sentText[idx]) as Record<string, unknown>;
}

async function runOne(
  ws: MockWebSocket,
  runner: UnifiedWebSocketRunner,
  frame: Record<string, unknown>
): Promise<Record<string, unknown>> {
  ws.queue.push({ type: "websocket.message", text: JSON.stringify(frame) });
  ws.queue.push({ type: "websocket.disconnect" });
  await runner.receiveMessages();
  return decodeFrame(ws, 0);
}

describe("generate_media RPC (text-to-image)", () => {
  let ws: MockWebSocket;

  beforeEach(() => {
    vi.clearAllMocks();
    ws = new MockWebSocket();
  });

  afterEach(() => {
    ws.queue.length = 0;
  });

  it("forwards aspect ratio and resolution to the provider", async () => {
    const calls: TextToImageParams[] = [];
    const provider = {
      provider: "fake",
      async textToImages(params: TextToImageParams): Promise<Uint8Array[]> {
        calls.push(params);
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      }
    };
    const runner = await makeRunner(ws, async () => provider as never);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "g-1",
      data: {
        mode: "image",
        provider: "fake",
        model: "fal-ai/flux/dev",
        prompt: "a cat",
        width: 1820,
        height: 1024,
        aspect_ratio: "16:9",
        resolution: "1K"
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(calls).toHaveLength(1);
    expect(calls[0].aspectRatio).toBe("16:9");
    expect(calls[0].resolution).toBe("1K");
    expect(calls[0].width).toBe(1820);
    expect(calls[0].height).toBe(1024);

    await runner.disconnect();
  });
});

describe("generate_media RPC (entity mentions)", () => {
  let ws: MockWebSocket;
  const textCalls: TextToImageParams[] = [];
  const editCalls: Array<{ images: Uint8Array[]; params: ImageToImageParams }> =
    [];

  const configureAssets = (
    rows: Array<Parameters<typeof makeAssetRow>[0] | "unknown">
  ): void => {
    const byId = new Map<string, ReturnType<typeof makeAssetRow>>();
    for (const id of rows) {
      if (id === "unknown") continue;
      byId.set(
        id,
        makeAssetRow(id, id === "src-1" ? null : ENTITY_MARKER)
      );
      REF_BYTES[id] = new Uint8Array([0xa1, ...Buffer.from(id)]);
    }
    (Asset as unknown as { find: typeof vi.fn }).find.mockImplementation(
      async (_userId: string, assetId: string) => byId.get(assetId) ?? null
    );
  };

  const makeProvider = (): never =>
    ({
      provider: "fake",
      async textToImages(params: TextToImageParams): Promise<Uint8Array[]> {
        textCalls.push(params);
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      },
      async imageToImages(
        images: Uint8Array[],
        params: ImageToImageParams
      ): Promise<Uint8Array[]> {
        editCalls.push({ images, params });
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      }
    }) as never;

  beforeEach(() => {
    vi.clearAllMocks();
    ws = new MockWebSocket();
    textCalls.length = 0;
    editCalls.length = 0;
    for (const key of Object.keys(REF_BYTES)) delete REF_BYTES[key];
  });

  afterEach(() => {
    ws.queue.length = 0;
  });

  it("routes an entity's reference image through imageToImages with the seasoned prompt", async () => {
    configureAssets(["ent-1"]);
    const runner = await makeRunner(ws, makeProvider);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "g-e1",
      data: {
        mode: "image",
        provider: "fake",
        model: "fal-ai/flux/dev",
        prompt: "a portrait of entity://ent-1 at dusk",
        aspect_ratio: "16:9"
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(textCalls).toHaveLength(0);
    expect(editCalls).toHaveLength(1);
    expect(editCalls[0].images).toEqual([REF_BYTES["ent-1"]]);
    expect(editCalls[0].params.prompt).toBe(
      "a portrait of Marta at dusk\n\n" +
        "Consistency references:\n" +
        "- Marta: red-haired detective in a beige trench coat"
    );

    await runner.disconnect();
  });

  it("appends entity images after the source on image_edit", async () => {
    configureAssets(["src-1", "ent-1"]);
    const runner = await makeRunner(ws, makeProvider);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "g-e2",
      data: {
        mode: "image_edit",
        provider: "fake",
        model: "openai/gpt-image-2/edit",
        prompt: "restyle with entity://ent-1",
        source_asset_id: "src-1"
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(editCalls).toHaveLength(1);
    expect(editCalls[0].images).toEqual([REF_BYTES["src-1"], REF_BYTES["ent-1"]]);
    expect(textCalls).toHaveLength(0);

    await runner.disconnect();
  });

  it("stays on text-to-image when the mention resolves to no entity", async () => {
    configureAssets(["unknown"]);
    const runner = await makeRunner(ws, makeProvider);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "g-e3",
      data: {
        mode: "image",
        provider: "fake",
        model: "fal-ai/flux/dev",
        prompt: "see entity://missing here"
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(textCalls).toHaveLength(1);
    // The dropped mention leaves no dangling token in the provider prompt.
    expect(textCalls[0].prompt).toBe("see here");
    expect(editCalls).toHaveLength(0);

    await runner.disconnect();
  });
});

describe("generate_media RPC (video modes)", () => {
  let ws: MockWebSocket;
  const t2vCalls: TextToVideoParams[] = [];
  const i2vCalls: Array<{ images: Uint8Array[]; params: ImageToVideoParams }> =
    [];
  const v2vCalls: Array<{ video: Uint8Array; params: ImageToVideoParams & { strength?: number | null } }> =
    [];

  const configureAssets = (ids: string[]): void => {
    const byId = new Map<string, ReturnType<typeof makeAssetRow>>();
    for (const id of ids) {
      byId.set(id, makeAssetRow(id, null));
      REF_BYTES[id] = new Uint8Array([0xb1, ...Buffer.from(id)]);
    }
    (Asset as unknown as { find: typeof vi.fn }).find.mockImplementation(
      async (_userId: string, assetId: string) => byId.get(assetId) ?? null
    );
  };

  const makeProvider = (): never =>
    ({
      provider: "fake",
      async textToVideo(params: TextToVideoParams): Promise<Uint8Array> {
        t2vCalls.push(params);
        return new Uint8Array([0x00, 0x00, 0x00, 0x18]);
      },
      async imageToVideo(
        images: Uint8Array[],
        params: ImageToVideoParams
      ): Promise<Uint8Array> {
        i2vCalls.push({ images, params });
        return new Uint8Array([0x00, 0x00, 0x00, 0x18]);
      },
      async videoToVideo(
        video: Uint8Array,
        params: ImageToVideoParams & { strength?: number | null }
      ): Promise<Uint8Array> {
        v2vCalls.push({ video, params });
        return new Uint8Array([0x00, 0x00, 0x00, 0x18]);
      }
    }) as never;

  beforeEach(() => {
    vi.clearAllMocks();
    ws = new MockWebSocket();
    t2vCalls.length = 0;
    i2vCalls.length = 0;
    v2vCalls.length = 0;
    for (const key of Object.keys(REF_BYTES)) delete REF_BYTES[key];
  });

  afterEach(() => {
    ws.queue.length = 0;
  });

  it("routes a source asset through imageToVideo with the requested duration", async () => {
    configureAssets(["srcv-1"]);
    const runner = await makeRunner(ws, makeProvider);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "gv-1",
      data: {
        mode: "video",
        provider: "fake",
        model: "fal-ai/kling/v2",
        prompt: "slow push in",
        source_asset_id: "srcv-1",
        aspect_ratio: "16:9",
        duration: 5
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(t2vCalls).toHaveLength(0);
    expect(i2vCalls).toHaveLength(1);
    expect(i2vCalls[0].images).toEqual([REF_BYTES["srcv-1"]]);
    expect(i2vCalls[0].params.prompt).toBe("slow push in");
    expect(i2vCalls[0].params.durationSeconds).toBe(5);
    expect(i2vCalls[0].params.aspectRatio).toBe("16:9");

    await runner.disconnect();
  });

  it("keeps text-to-video when no source asset is given", async () => {
    const runner = await makeRunner(ws, makeProvider);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "gv-2",
      data: {
        mode: "video",
        provider: "fake",
        model: "fal-ai/kling/v2",
        prompt: "drifting clouds",
        duration: 4
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(t2vCalls).toHaveLength(1);
    expect(t2vCalls[0].prompt).toBe("drifting clouds");
    expect(t2vCalls[0].durationSeconds).toBe(4);
    expect(i2vCalls).toHaveLength(0);

    await runner.disconnect();
  });

  it("routes video_edit through videoToVideo", async () => {
    configureAssets(["clipv-1"]);
    const runner = await makeRunner(ws, makeProvider);

    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "gv-3",
      data: {
        mode: "video_edit",
        provider: "fake",
        model: "fal-ai/video-restyle",
        prompt: "more fog",
        source_asset_id: "clipv-1",
        strength: 0.7
      }
    });

    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    expect(v2vCalls).toHaveLength(1);
    expect(v2vCalls[0].video).toEqual(REF_BYTES["clipv-1"]);
    expect(v2vCalls[0].params.prompt).toBe("more fog");
    expect(v2vCalls[0].params.strength).toBe(0.7);

    await runner.disconnect();
  });
});

describe("generate_media RPC (parameter passthrough)", () => {
  let ws: MockWebSocket;
  const captured = {
    textToImages: [] as Array<{ params: TextToImageParams; variations: number }>,
    imageToImages: [] as Array<{
      images: Uint8Array[];
      params: ImageToImageParams;
      variations: number;
    }>,
    inpaintImages: [] as Array<{
      images: Uint8Array[];
      params: Record<string, unknown>;
      variations: number;
    }>,
    ttsEncoded: [] as Array<Record<string, unknown>>
  };

  const configureAssets = (ids: string[]): void => {
    const byId = new Map<string, ReturnType<typeof makeAssetRow>>();
    for (const id of ids) {
      byId.set(id, makeAssetRow(id, null));
      REF_BYTES[id] = new Uint8Array([0xc1, ...Buffer.from(id)]);
    }
    (Asset as unknown as { find: typeof vi.fn }).find.mockImplementation(
      async (_userId: string, assetId: string) => byId.get(assetId) ?? null
    );
  };

  const makeProvider = (): never =>
    ({
      provider: "fake",
      async textToImages(
        params: TextToImageParams,
        variations = 1
      ): Promise<Uint8Array[]> {
        captured.textToImages.push({ params, variations });
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      },
      async imageToImages(
        images: Uint8Array[],
        params: ImageToImageParams,
        variations = 1
      ): Promise<Uint8Array[]> {
        captured.imageToImages.push({ images, params, variations });
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      },
      async inpaintImages(
        images: Uint8Array[],
        params: unknown,
        variations = 1
      ): Promise<Uint8Array[]> {
        captured.inpaintImages.push({
          images,
          params: params as Record<string, unknown>,
          variations
        });
        return [new Uint8Array([0x89, 0x50, 0x4e, 0x47])];
      },
      async textToSpeechEncoded(
        args: Record<string, unknown>
      ): Promise<{ data: Uint8Array; mimeType: string }> {
        captured.ttsEncoded.push(args);
        return { data: new Uint8Array([0xff, 0xf3]), mimeType: "audio/mpeg" };
      }
    }) as never;

  beforeEach(() => {
    vi.clearAllMocks();
    ws = new MockWebSocket();
    captured.textToImages.length = 0;
    captured.imageToImages.length = 0;
    captured.inpaintImages.length = 0;
    captured.ttsEncoded.length = 0;
  });

  afterEach(() => {
    ws.queue.length = 0;
  });

  it("image: forwards width, height, aspect ratio, resolution and variations", async () => {
    const runner = await makeRunner(ws, makeProvider);
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "p-1",
      data: {
        mode: "image",
        provider: "fake",
        model: "m",
        prompt: "a cat",
        width: 1024,
        height: 640,
        aspect_ratio: "16:9",
        resolution: "2K",
        variations: 3
      }
    });
    expect(out.error).toBeUndefined();
    const call = captured.textToImages[0];
    expect(call.params.width).toBe(1024);
    expect(call.params.height).toBe(640);
    expect(call.params.aspectRatio).toBe("16:9");
    expect(call.params.resolution).toBe("2K");
    expect(call.params.prompt).toBe("a cat");
    expect(call.variations).toBe(3);
    await runner.disconnect();
  });

  it("image_edit: forwards source, target size, strength, steps and variations", async () => {
    configureAssets(["src-p2"]);
    const runner = await makeRunner(ws, makeProvider);
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "p-2",
      data: {
        mode: "image_edit",
        provider: "fake",
        model: "m",
        prompt: "restyle",
        source_asset_id: "src-p2",
        width: 800,
        height: 600,
        strength: 0.8,
        num_inference_steps: 30,
        variations: 2
      }
    });
    expect(out.error).toBeUndefined();
    const call = captured.imageToImages[0];
    expect(call.images).toEqual([REF_BYTES["src-p2"]]);
    expect(call.params.prompt).toBe("restyle");
    expect(call.params.targetWidth).toBe(800);
    expect(call.params.targetHeight).toBe(600);
    expect(call.params.strength).toBe(0.8);
    expect(call.params.numInferenceSteps).toBe(30);
    expect(call.variations).toBe(2);
    await runner.disconnect();
  });

  it("inpaint: forwards source and mask bytes plus strength and steps", async () => {
    configureAssets(["src-p3", "mask-p3"]);
    const runner = await makeRunner(ws, makeProvider);
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "p-3",
      data: {
        mode: "inpaint",
        provider: "fake",
        model: "m",
        prompt: "fill the sky",
        source_asset_id: "src-p3",
        mask_asset_id: "mask-p3",
        width: 512,
        height: 512,
        strength: 0.9,
        num_inference_steps: 20
      }
    });
    expect(out.error).toBeUndefined();
    const call = captured.inpaintImages[0];
    expect(call.images).toEqual([REF_BYTES["src-p3"]]);
    expect((call.params as { mask?: Uint8Array }).mask).toEqual(
      REF_BYTES["mask-p3"]
    );
    expect(call.params.prompt).toBe("fill the sky");
    expect(call.params.strength).toBe(0.9);
    expect(call.params.numInferenceSteps).toBe(20);
    await runner.disconnect();
  });

  it("image: derives pixel size from resolution + aspect ratio when none sent", async () => {
    const runner = await makeRunner(ws, makeProvider);
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "p-5",
      data: {
        mode: "image",
        provider: "fake",
        model: "m",
        prompt: "wide scene",
        aspect_ratio: "16:9",
        resolution: "1K"
      }
    });
    expect(out.error).toBeUndefined();
    // 1K short edge; 16:9 scales the long edge — the node layer's arithmetic.
    expect(captured.textToImages[0].params.width).toBe(1820);
    expect(captured.textToImages[0].params.height).toBe(1024);
    await runner.disconnect();
  });

  it("image_edit: derives target size from resolution + aspect ratio", async () => {
    configureAssets(["src-p6"]);
    const runner = await makeRunner(ws, makeProvider);
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "p-6",
      data: {
        mode: "image_edit",
        provider: "fake",
        model: "m",
        prompt: "widen",
        source_asset_id: "src-p6",
        aspect_ratio: "9:16",
        resolution: "2K"
      }
    });
    expect(out.error).toBeUndefined();
    // Portrait: the tier sets the short edge (width), ratio scales the other.
    expect(captured.imageToImages[0].params.targetWidth).toBe(2048);
    expect(captured.imageToImages[0].params.targetHeight).toBe(3641);
    await runner.disconnect();
  });

  it("audio: forwards voice, speed and audio format", async () => {
    const runner = await makeRunner(ws, makeProvider);
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "p-4",
      data: {
        mode: "audio",
        provider: "fake",
        model: "tts-1",
        prompt: "We are closed.",
        voice: "alloy",
        speed: 1.2,
        audio_format: "mp3"
      }
    });
    expect(out.error).toBeUndefined();
    expect(captured.ttsEncoded[0]).toEqual({
      text: "We are closed.",
      model: "tts-1",
      voice: "alloy",
      speed: 1.2,
      audioFormat: "mp3"
    });
    await runner.disconnect();
  });
});
