/**
 * Coverage tests for the RPC command surface of the unified WebSocket runner:
 * the `handleCommand` dispatch table (set_mode / stop / cancel_job /
 * stream_input / update_node_properties / unknown-command / envelope edge
 * cases), the `generate_media` branches not exercised by `generate-media-rpc`
 * (video, audio-encoded, audio-PCM→WAV, audio raw-pcm, image_edit, inpaint,
 * and their error paths), the `transcribe_audio` provider/validation errors,
 * and the small synchronous helpers `getStatus` / `cancelJob` / `clearModels`.
 *
 * Drives the runner through a MockWebSocket (no real sockets), with fake
 * providers and a stubbed Asset/storage layer, and asserts the exact frames
 * that reach the client.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { unpack } from "msgpackr";
import {
  UnifiedWebSocketRunner,
  type WebSocketConnection,
  type WebSocketReceiveFrame
} from "../src/unified-websocket-runner.js";

// Storing generated bytes as assets is a no-op in these tests.
vi.mock("../src/lib/thumbnail.js", () => ({
  storeAssetWithThumbnail: vi.fn(async () => undefined)
}));

// Asset: unique id per instance so asset_ids arrays are distinguishable, plus
// a mockable static `find` for source/mask/audio lookups.
let assetCounter = 0;
vi.mock("@nodetool-ai/models", async (orig) => {
  const actual = await orig<typeof import("@nodetool-ai/models")>();
  class FakeAsset {
    id: string;
    size = 0;
    content_type: string;
    constructor(args: { content_type?: string } = {}) {
      this.id = `asset-${++assetCounter}`;
      this.content_type = args.content_type ?? "application/octet-stream";
    }
    async save(): Promise<void> {}
    static find = vi.fn();
  }
  return { ...actual, Asset: FakeAsset };
});

// Asset adapter used by image_edit / inpaint / transcribe to fetch source bytes.
let retrieveImpl: (uri: string) => Promise<Uint8Array | null> = async () =>
  new Uint8Array([1, 2, 3, 4]);
vi.mock("../src/lib/storage.js", async (orig) => {
  const actual = await orig<typeof import("../src/lib/storage.js")>();
  return {
    ...actual,
    getAssetAdapter: vi.fn(() => ({
      uriForKey: (key: string) => `mem://${key}`,
      retrieve: (uri: string) => retrieveImpl(uri)
    }))
  };
});

import { Asset } from "@nodetool-ai/models";

class MockWebSocket implements WebSocketConnection {
  clientState: "connected" | "disconnected" = "connected";
  applicationState: "connected" | "disconnected" = "connected";
  sentBytes: Uint8Array[] = [];
  sentText: string[] = [];
  queue: Array<WebSocketReceiveFrame> = [];

  async accept(): Promise<void> {
    return;
  }
  async receive(): Promise<WebSocketReceiveFrame> {
    const next = this.queue.shift();
    if (!next) return { type: "websocket.disconnect" };
    return next;
  }
  async sendBytes(data: Uint8Array): Promise<void> {
    this.sentBytes.push(data);
  }
  async sendText(data: string): Promise<void> {
    this.sentText.push(data);
  }
  async close(): Promise<void> {
    this.clientState = "disconnected";
    this.applicationState = "disconnected";
  }
}

type ResolveProvider = ConstructorParameters<
  typeof UnifiedWebSocketRunner
>[0]["resolveProvider"];

async function makeRunner(
  ws: MockWebSocket,
  opts: { resolveProvider?: ResolveProvider; withProvider?: boolean } = {}
): Promise<UnifiedWebSocketRunner> {
  const runner = new UnifiedWebSocketRunner({
    resolveExecutor: () => ({
      async process() {
        return {};
      }
    }),
    ...(opts.withProvider === false
      ? {}
      : { resolveProvider: opts.resolveProvider ?? (async () => ({}) as never) }),
    nodeRegistry: {
      listMetadata: () => [],
      has: () => false,
      resolve: () => ({ async process() { return {}; } }),
      getMetadata: () => undefined,
      createNodeValidator: () => () => undefined
    } as never,
    apiOptions: {
      metadataRoots: [],
      registry: {} as never,
      storage: {}
    } as never,
    pythonBridge: {} as never,
    getPythonBridgeReady: () => true
  });
  await runner.connect(ws);
  return runner;
}

function decodeFrame(ws: MockWebSocket, idx: number): Record<string, unknown> {
  if (ws.sentBytes[idx]) {
    return unpack(ws.sentBytes[idx]) as Record<string, unknown>;
  }
  return JSON.parse(ws.sentText[idx]) as Record<string, unknown>;
}

/** All frames sent so far (binary come first in this harness). */
function allFrames(ws: MockWebSocket): Record<string, unknown>[] {
  return [
    ...ws.sentBytes.map((b) => unpack(b) as Record<string, unknown>),
    ...ws.sentText.map((t) => JSON.parse(t) as Record<string, unknown>)
  ];
}

async function runOne(
  ws: MockWebSocket,
  runner: UnifiedWebSocketRunner,
  frame: Record<string, unknown>
): Promise<Record<string, unknown>> {
  ws.queue.push({ type: "websocket.message", text: JSON.stringify(frame) });
  ws.queue.push({ type: "websocket.disconnect" });
  await runner.receiveMessages();
  return decodeFrame(ws, 0);
}

/** A provider fake with only the media methods a given test needs. */
function makeProvider(over: Record<string, unknown> = {}) {
  return { provider: "fake", ...over } as never;
}

describe("handleCommand dispatch (non-RPC branches)", () => {
  let ws: MockWebSocket;
  beforeEach(() => {
    vi.clearAllMocks();
    assetCounter = 0;
    ws = new MockWebSocket();
  });
  afterEach(() => {
    ws.queue.length = 0;
  });

  it("clear_models returns the provider-managed message", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, { command: "clear_models" });
    expect(String(out.message)).toContain("Model clearing is managed");
    await runner.disconnect();
  });

  it("set_mode rejects an invalid mode", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, {
      command: "set_mode",
      data: { mode: "bogus" }
    });
    expect(out.error).toBe("mode must be binary or text");
    await runner.disconnect();
  });

  it("set_mode accepts a valid mode", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, {
      command: "set_mode",
      data: { mode: "text" }
    });
    expect(String(out.message)).toContain("Mode set to text");
    await runner.disconnect();
  });

  it("returns Unknown command for an unrecognized command", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, { command: "not_a_real_command" });
    expect(out.error).toBe("Unknown command");
    await runner.disconnect();
  });

  it("chat_message requires a thread_id", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, {
      command: "chat_message",
      data: {}
    });
    expect(out.error).toBe("thread_id is required for chat_message command");
    await runner.disconnect();
  });

  it("reconnect_job / resume_job require a job_id", async () => {
    const runner = await makeRunner(ws);
    const a = await runOne(ws, runner, { command: "reconnect_job", data: {} });
    expect(a.error).toBe("job_id is required");
    ws.sentBytes.length = 0;
    ws.sentText.length = 0;
    const b = await runOne(ws, runner, { command: "resume_job", data: {} });
    expect(b.error).toBe("job_id is required");
    await runner.disconnect();
  });

  it("cancel_job requires a job_id", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, { command: "cancel_job", data: {} });
    expect(out.error).toBe("job_id is required");
    await runner.disconnect();
  });

  it("stream_input errors without a job_id, then without an active job", async () => {
    const runner = await makeRunner(ws);
    const noId = await runOne(ws, runner, {
      command: "stream_input",
      data: { input: "x" }
    });
    expect(noId.error).toBe("job_id is required");
    ws.sentBytes.length = 0;
    ws.sentText.length = 0;
    const noJob = await runOne(ws, runner, {
      command: "stream_input",
      data: { job_id: "j1", input: "x" }
    });
    expect(noJob.error).toBe("No active job/context");
    await runner.disconnect();
  });

  it("stream_input rejects an empty input name", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, {
      command: "stream_input",
      data: { job_id: "j1", input: "   " }
    });
    // Missing active job is checked before the input-name guard.
    expect(out.error).toBe("No active job/context");
    await runner.disconnect();
  });

  it("end_input_stream errors without an active job", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, {
      command: "end_input_stream",
      data: { job_id: "j1", input: "x" }
    });
    expect(out.error).toBe("No active job/context");
    await runner.disconnect();
  });

  it("update_node_properties validates job_id, node_id and properties shape", async () => {
    const runner = await makeRunner(ws);
    const noJob = await runOne(ws, runner, {
      command: "update_node_properties",
      data: {}
    });
    expect(noJob.error).toBe("job_id is required");

    ws.sentBytes.length = 0;
    ws.sentText.length = 0;
    const noNode = await runOne(ws, runner, {
      command: "update_node_properties",
      data: { job_id: "j1", properties: {} }
    });
    expect(noNode.error).toBe("node_id is required");

    ws.sentBytes.length = 0;
    ws.sentText.length = 0;
    const badProps = await runOne(ws, runner, {
      command: "update_node_properties",
      data: { job_id: "j1", node_id: "n1", properties: "nope" }
    });
    expect(badProps.error).toBe("properties must be an object");

    ws.sentBytes.length = 0;
    ws.sentText.length = 0;
    const noActive = await runOne(ws, runner, {
      command: "update_node_properties",
      data: { job_id: "j1", node_id: "n1", properties: { a: 1 } }
    });
    expect(noActive.applied).toBe(false);
    await runner.disconnect();
  });

  it("get_status reports not_found for an unknown job and empty active list", async () => {
    const runner = await makeRunner(ws);
    const perJob = await runOne(ws, runner, {
      command: "get_status",
      data: { job_id: "nope" }
    });
    expect(perJob.status).toBe("not_found");
    expect(perJob.job_id).toBe("nope");

    ws.sentBytes.length = 0;
    ws.sentText.length = 0;
    const all = await runOne(ws, runner, { command: "get_status", data: {} });
    expect(all.active_jobs).toEqual([]);
    await runner.disconnect();
  });

  it("stop emits generation_stopped then a processed ack", async () => {
    const runner = await makeRunner(ws);
    ws.queue.push({
      type: "websocket.message",
      text: JSON.stringify({
        command: "stop",
        data: { thread_id: "th-1" }
      })
    });
    ws.queue.push({ type: "websocket.disconnect" });
    await runner.receiveMessages();

    const frames = allFrames(ws);
    const stopped = frames.find((f) => f.type === "generation_stopped");
    expect(stopped).toBeTruthy();
    expect(stopped?.thread_id).toBe("th-1");
    const ack = frames.find(
      (f) => typeof f.message === "string" && f.message === "Stop command processed"
    );
    expect(ack).toBeTruthy();
    await runner.disconnect();
  });

  it("routes a message with no command to invalid_message", async () => {
    const runner = await makeRunner(ws);
    const out = await runOne(ws, runner, { type: "not_a_command", foo: 1 });
    expect(out.error).toBe("invalid_message");
    await runner.disconnect();
  });

  it("responds to a ping frame with a pong", async () => {
    const runner = await makeRunner(ws);
    ws.queue.push({
      type: "websocket.message",
      text: JSON.stringify({ type: "ping" })
    });
    ws.queue.push({ type: "websocket.disconnect" });
    await runner.receiveMessages();
    const frames = allFrames(ws);
    expect(frames.some((f) => f.type === "pong")).toBe(true);
    await runner.disconnect();
  });
});

describe("generate_media RPC — non-image branches", () => {
  let ws: MockWebSocket;
  beforeEach(() => {
    vi.clearAllMocks();
    assetCounter = 0;
    retrieveImpl = async () => new Uint8Array([1, 2, 3, 4]);
    ws = new MockWebSocket();
    (Asset.find as ReturnType<typeof vi.fn>).mockReset();
  });
  afterEach(() => {
    ws.queue.length = 0;
  });

  it("text-to-video stores a single mp4 asset", async () => {
    const calls: unknown[] = [];
    const provider = makeProvider({
      async textToVideo(params: unknown) {
        calls.push(params);
        return new Uint8Array([0, 1, 2, 3]);
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "v-1",
      data: { mode: "video", provider: "fake", model: "veo", prompt: "a dog" }
    });
    expect(out.type).toBe("rpc_response");
    expect(out.error).toBeUndefined();
    const result = out.result as { asset_ids: string[] };
    expect(result.asset_ids).toHaveLength(1);
    expect(calls).toHaveLength(1);
    await runner.disconnect();
  });

  it("audio uses the encoded path when the provider returns encoded bytes", async () => {
    const provider = makeProvider({
      async textToSpeechEncoded() {
        return { data: new Uint8Array([9, 9]), mimeType: "audio/mpeg" };
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "a-1",
      data: { mode: "audio", provider: "fake", model: "tts", prompt: "hi" }
    });
    const result = out.result as { asset_ids: string[] };
    expect(result.asset_ids).toHaveLength(1);
    await runner.disconnect();
  });

  it("audio wraps streamed PCM in a WAV container when nothing is encoded", async () => {
    const provider = makeProvider({
      async textToSpeechEncoded() {
        return null;
      },
      async *textToSpeech() {
        yield { samples: new Int16Array([1, 2, 3, 4]), sampleRate: 16000 };
        yield { samples: new Int16Array([5, 6]), sampleRate: 16000 };
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "a-2",
      data: { mode: "audio", provider: "fake", model: "tts", prompt: "hi" }
    });
    expect(out.error).toBeUndefined();
    const result = out.result as { asset_ids: string[] };
    expect(result.asset_ids).toHaveLength(1);
    await runner.disconnect();
  });

  it("audio returns raw pcm when audio_format=pcm and nothing is encoded", async () => {
    const provider = makeProvider({
      async textToSpeechEncoded() {
        return null;
      },
      async *textToSpeech() {
        yield { samples: new Int16Array([1, 2]), sampleRate: 24000 };
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "a-3",
      data: {
        mode: "audio",
        provider: "fake",
        model: "tts",
        prompt: "hi",
        audio_format: "pcm"
      }
    });
    expect(out.error).toBeUndefined();
    const result = out.result as { asset_ids: string[] };
    expect(result.asset_ids).toHaveLength(1);
    await runner.disconnect();
  });

  it("image_edit errors when source_asset_id is missing", async () => {
    const provider = makeProvider({
      async imageToImages() {
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "ie-1",
      data: { mode: "image_edit", provider: "fake", model: "m", prompt: "x" }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/source_asset_id is required/);
    await runner.disconnect();
  });

  it("image_edit errors when the source asset row is not found", async () => {
    (Asset.find as ReturnType<typeof vi.fn>).mockResolvedValue(null);
    const provider = makeProvider({
      async imageToImages() {
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "ie-2",
      data: {
        mode: "image_edit",
        provider: "fake",
        model: "m",
        prompt: "x",
        source_asset_id: "src-missing"
      }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/Source asset not found/);
    await runner.disconnect();
  });

  it("image_edit succeeds and forwards source bytes to imageToImages", async () => {
    (Asset.find as ReturnType<typeof vi.fn>).mockResolvedValue({
      id: "src-1",
      content_type: "image/png"
    });
    const seen: { images: Uint8Array[]; variations: number }[] = [];
    const provider = makeProvider({
      async imageToImages(images: Uint8Array[], _p: unknown, variations: number) {
        seen.push({ images, variations });
        return [new Uint8Array([1]), new Uint8Array([2])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "ie-3",
      data: {
        mode: "image_edit",
        provider: "fake",
        model: "m",
        prompt: "x",
        source_asset_id: "src-1",
        variations: 2
      }
    });
    expect(out.error).toBeUndefined();
    const result = out.result as { asset_ids: string[] };
    expect(result.asset_ids).toHaveLength(2);
    expect(seen[0].variations).toBe(2);
    expect(Array.from(seen[0].images[0])).toEqual([1, 2, 3, 4]);
    await runner.disconnect();
  });

  it("inpaint errors when the mask asset id is missing", async () => {
    const provider = makeProvider({
      async inpaintImages() {
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "in-1",
      data: {
        mode: "inpaint",
        provider: "fake",
        model: "m",
        prompt: "x",
        source_asset_id: "src-1"
      }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/mask_asset_id is required/);
    await runner.disconnect();
  });

  it("inpaint succeeds with source + mask bytes", async () => {
    (Asset.find as ReturnType<typeof vi.fn>).mockImplementation(
      async (_u: string, id: string) => ({ id, content_type: "image/png" })
    );
    const provider = makeProvider({
      async inpaintImages(images: Uint8Array[], _p: unknown, variations: number) {
        void images;
        void variations;
        return [new Uint8Array([7])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "in-2",
      data: {
        mode: "inpaint",
        provider: "fake",
        model: "m",
        prompt: "x",
        source_asset_id: "src-1",
        mask_asset_id: "mask-1"
      }
    });
    expect(out.error).toBeUndefined();
    const result = out.result as { asset_ids: string[] };
    expect(result.asset_ids).toHaveLength(1);
    await runner.disconnect();
  });

  it("clamps variations above 8 down to 8 for text-to-image", async () => {
    let seenVariations = -1;
    const provider = makeProvider({
      async textToImages(_p: unknown, variations: number) {
        seenVariations = variations;
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    await runOne(ws, runner, {
      command: "generate_media",
      request_id: "clamp-1",
      data: {
        mode: "image",
        provider: "fake",
        model: "m",
        prompt: "x",
        variations: 100
      }
    });
    expect(seenVariations).toBe(8);
    await runner.disconnect();
  });

  it("errors when model is an explicit empty string", async () => {
    const provider = makeProvider({
      async textToImages() {
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "err-1",
      data: { mode: "image", provider: "fake", model: "", prompt: "x" }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/model is required/);
    await runner.disconnect();
  });

  it("errors when prompt is blank", async () => {
    const provider = makeProvider({
      async textToImages() {
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "err-2",
      data: { mode: "image", provider: "fake", model: "m", prompt: "   " }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/prompt is required/);
    await runner.disconnect();
  });

  it("errors when no provider resolver is configured", async () => {
    const runner = await makeRunner(ws, { withProvider: false });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      request_id: "err-3",
      data: { mode: "image", provider: "fake", model: "m", prompt: "x" }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/No provider resolver configured/);
    await runner.disconnect();
  });

  it("returns a legacy error when request_id is missing on generate_media", async () => {
    const provider = makeProvider({
      async textToImages() {
        return [new Uint8Array([1])];
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "generate_media",
      data: { mode: "image", provider: "fake", model: "m", prompt: "x" }
    });
    expect(out.type).toBeUndefined();
    expect(String(out.error)).toContain("request_id is required");
    await runner.disconnect();
  });
});

describe("transcribe_audio RPC — error branches", () => {
  let ws: MockWebSocket;
  beforeEach(() => {
    vi.clearAllMocks();
    assetCounter = 0;
    retrieveImpl = async () => new Uint8Array([1, 2, 3, 4]);
    ws = new MockWebSocket();
    (Asset.find as ReturnType<typeof vi.fn>).mockReset();
  });
  afterEach(() => {
    ws.queue.length = 0;
  });

  it("errors when no provider resolver is configured", async () => {
    const runner = await makeRunner(ws, { withProvider: false });
    const out = await runOne(ws, runner, {
      command: "transcribe_audio",
      request_id: "tr-1",
      data: { provider: "fake", model: "whisper", asset_id: "a1" }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/No provider resolver configured/);
    await runner.disconnect();
  });

  it("errors when the audio asset bytes cannot be retrieved", async () => {
    (Asset.find as ReturnType<typeof vi.fn>).mockResolvedValue({
      id: "a1",
      content_type: "audio/wav"
    });
    retrieveImpl = async () => null;
    const provider = makeProvider({
      async automaticSpeechRecognition() {
        return { text: "", chunks: [] };
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "transcribe_audio",
      request_id: "tr-2",
      data: { provider: "fake", model: "whisper", asset_id: "a1" }
    });
    const error = out.error as { message?: string };
    expect(error?.message).toMatch(/Audio asset bytes not found/);
    await runner.disconnect();
  });

  it("forwards language and returns text with no chunks as empty words", async () => {
    (Asset.find as ReturnType<typeof vi.fn>).mockResolvedValue({
      id: "a1",
      content_type: "audio/mpeg"
    });
    const calls: Array<Record<string, unknown>> = [];
    const provider = makeProvider({
      async automaticSpeechRecognition(args: Record<string, unknown>) {
        calls.push(args);
        return { text: "bonjour" };
      }
    });
    const runner = await makeRunner(ws, { resolveProvider: async () => provider });
    const out = await runOne(ws, runner, {
      command: "transcribe_audio",
      request_id: "tr-3",
      data: {
        provider: "fake",
        model: "whisper",
        asset_id: "a1",
        language: "fr"
      }
    });
    expect(out.result).toEqual({ text: "bonjour", words: [] });
    expect(calls[0].language).toBe("fr");
    expect(calls[0].word_timestamps).toBe(true);
    await runner.disconnect();
  });
});

describe("synchronous helpers", () => {
  let ws: MockWebSocket;
  beforeEach(() => {
    vi.clearAllMocks();
    ws = new MockWebSocket();
  });

  it("clearModels resolves with the managed message", async () => {
    const runner = await makeRunner(ws);
    const res = await runner.clearModels();
    expect(String(res.message)).toContain("Model clearing is managed");
    await runner.disconnect();
  });

  it("getStatus returns not_found for an unknown job", async () => {
    const runner = await makeRunner(ws);
    expect(runner.getStatus("ghost")).toEqual({
      status: "not_found",
      job_id: "ghost"
    });
    await runner.disconnect();
  });

  it("getStatus with no id returns an empty active-jobs list", async () => {
    const runner = await makeRunner(ws);
    expect(runner.getStatus()).toEqual({ active_jobs: [] });
    await runner.disconnect();
  });

  it("cancelJob returns an error object for an empty job id", async () => {
    const runner = await makeRunner(ws);
    expect(await runner.cancelJob("")).toEqual({ error: "No job_id provided" });
    await runner.disconnect();
  });

  it("cancelJob reports not-found for an unknown, unqueued job", async () => {
    const runner = await makeRunner(ws);
    const res = await runner.cancelJob("unknown-job", "wf-9");
    expect(res.error).toBe("Job not found or already completed");
    expect(res.job_id).toBe("unknown-job");
    expect(res.workflow_id).toBe("wf-9");
    await runner.disconnect();
  });
});
