export const QUICK_ACTION_NODE_TYPES = [
  "nodetool.agents.Agent",
  "nodetool.code.Code",
  "nodetool.image.TextToImage",
  "nodetool.image.ImageToImage",
  "nodetool.video.TextToVideo",
  "nodetool.video.ImageToVideo",
  "nodetool.audio.TextToSpeech",
  "nodetool.text.AutomaticSpeechRecognition",
  "fal.DynamicFal",
  "kie.dynamic_schema.KieAI",
  "replicate.DynamicReplicate",
  "nodetool.constant.Bool",
  "nodetool.constant.DataFrame",
  "nodetool.constant.Date",
  "nodetool.constant.DateTime",
  "nodetool.constant.Dict",
  "nodetool.constant.Audio",
  "nodetool.constant.Document",
  "nodetool.constant.Float",
  "nodetool.constant.Image",
  "nodetool.constant.Integer",
  "nodetool.constant.JSON",
  "nodetool.constant.List",
  "nodetool.constant.Model3D",
  "nodetool.constant.String",
  "nodetool.constant.Video"
] as const;
