source "https://rubygems.org"

gem "csv"
gem "logger"
gem "base64"

gem "jekyll", "~> 4.3.0"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
