// AUTO-GENERATED by marketing/scripts/generate-calculator-pricing.mjs — do not edit by hand.
// Regenerate: node marketing/scripts/generate-calculator-pricing.mjs
//
// Unit prices behind the BYOK calculator, read from the same generated
// GenSpend catalog NodeTool bills a run against
// (packages/model-pricing/src/generated/genspend-pricing.json). Picked to
// span each modality's price range, not to flatter it: the cheapest and the
// most expensive model in the catalog are both in the list.

/** What a model charges for. */
export type CalculatorModality = "image" | "video" | "speech";

export interface CalculatorModel {
  /** `provider:model:modality` — stable across regenerations. */
  id: string;
  /** Runtime provider id; look up display metadata in PROVIDER_DISPLAY. */
  provider: string;
  modality: CalculatorModality;
  name: string;
  /** USD per image, per video second, or per million characters. */
  unitPrice: number;
  /** The provider page the price was read from, when the catalog names one. */
  sourceUrl: string | null;
}

/** GenSpend's licence asks for this line wherever its prices are shown. */
export const PRICING_ATTRIBUTION = "Prices via genspend.io";

/** When the upstream catalog was last refreshed (ISO 8601). */
export const PRICING_UPDATED_AT = "2026-08-23T09:34:58.617Z";

/** Priced (provider, model) pairs the catalog holds across the three modalities. */
export const PRICED_MODEL_COUNT = 130;

export const CALCULATOR_MODELS: Record<CalculatorModality, CalculatorModel[]> = {
  "image": [
    {
      "id": "together:flux-1-schnell:image",
      "provider": "together",
      "modality": "image",
      "name": "Flux 1 Schnell",
      "unitPrice": 0.0027,
      "sourceUrl": "https://www.together.ai/pricing"
    },
    {
      "id": "atlascloud:z-image-turbo:image",
      "provider": "atlascloud",
      "modality": "image",
      "name": "Z Image Turbo",
      "unitPrice": 0.005,
      "sourceUrl": "https://www.atlascloud.ai/models/z-image/turbo"
    },
    {
      "id": "atlascloud:gpt-image-2:image",
      "provider": "atlascloud",
      "modality": "image",
      "name": "GPT Image 2",
      "unitPrice": 0.009,
      "sourceUrl": "https://www.atlascloud.ai/models/openai/gpt-image-2/text-to-image"
    },
    {
      "id": "kie:gemini-2.5-flash-image:image",
      "provider": "kie",
      "modality": "image",
      "name": "Gemini 2.5 Flash Image",
      "unitPrice": 0.02,
      "sourceUrl": "https://kie.ai/nano-banana"
    },
    {
      "id": "fal_ai:recraft-20b:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Recraft 20b",
      "unitPrice": 0.022,
      "sourceUrl": "https://fal.ai/models/fal-ai/recraft-20b"
    },
    {
      "id": "kie:seedream-5-lite:image",
      "provider": "kie",
      "modality": "image",
      "name": "Seedream 5 Lite",
      "unitPrice": 0.0275,
      "sourceUrl": "https://kie.ai/seedream5-0-lite"
    },
    {
      "id": "fal_ai:kling-image-o3:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Kling Image O3",
      "unitPrice": 0.028,
      "sourceUrl": "https://fal.ai/models/fal-ai/kling-image/o3/image-to-image"
    },
    {
      "id": "fal_ai:ideogram-v3:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Ideogram v3",
      "unitPrice": 0.03,
      "sourceUrl": "https://fal.ai/models/fal-ai/ideogram/v3"
    },
    {
      "id": "together:seedream-4:image",
      "provider": "together",
      "modality": "image",
      "name": "Seedream 4",
      "unitPrice": 0.03,
      "sourceUrl": "https://www.together.ai/pricing"
    },
    {
      "id": "fal_ai:recraft-v4-1:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Recraft v4 1",
      "unitPrice": 0.035,
      "sourceUrl": "https://fal.ai/models/fal-ai/recraft/v4.1/text-to-image"
    },
    {
      "id": "fal_ai:bria-fibo:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Bria Fibo",
      "unitPrice": 0.04,
      "sourceUrl": "https://fal.ai/models/bria/fibo/generate"
    },
    {
      "id": "fal_ai:imagen-4:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Imagen 4",
      "unitPrice": 0.04,
      "sourceUrl": "https://fal.ai/models/fal-ai/imagen4/preview"
    },
    {
      "id": "kie:gemini-3.1-flash-image:image",
      "provider": "kie",
      "modality": "image",
      "name": "Gemini 3.1 Flash Image",
      "unitPrice": 0.04,
      "sourceUrl": "https://kie.ai/nano-banana-2"
    },
    {
      "id": "together:flux-1-kontext-pro:image",
      "provider": "together",
      "modality": "image",
      "name": "Flux 1 Kontext Pro",
      "unitPrice": 0.04,
      "sourceUrl": "https://www.together.ai/pricing"
    },
    {
      "id": "fal_ai:flux-2-flex:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Flux 2 Flex",
      "unitPrice": 0.05,
      "sourceUrl": "https://fal.ai/models/fal-ai/flux-2-flex"
    },
    {
      "id": "fal_ai:qwen-image-max:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Qwen Image Max",
      "unitPrice": 0.075,
      "sourceUrl": "https://fal.ai/models/fal-ai/qwen-image-max/edit"
    },
    {
      "id": "replicate:ideogram-v3:image",
      "provider": "replicate",
      "modality": "image",
      "name": "Ideogram v3",
      "unitPrice": 0.09,
      "sourceUrl": "https://replicate.com/pricing"
    },
    {
      "id": "fal_ai:gemini-3-pro-image:image",
      "provider": "fal_ai",
      "modality": "image",
      "name": "Gemini 3 Pro Image",
      "unitPrice": 0.15,
      "sourceUrl": "https://fal.ai/models/fal-ai/gemini-3-pro-image-preview/edit"
    }
  ],
  "video": [
    {
      "id": "kie:infinitalk:video",
      "provider": "kie",
      "modality": "video",
      "name": "Infinitalk",
      "unitPrice": 0.015,
      "sourceUrl": "https://kie.ai/infinitalk"
    },
    {
      "id": "kie:grok-imagine-video:video",
      "provider": "kie",
      "modality": "video",
      "name": "Grok Imagine Video",
      "unitPrice": 0.0225,
      "sourceUrl": "https://kie.ai/grok-imagine-video-1.5"
    },
    {
      "id": "atlascloud:veo-3.1-lite:video",
      "provider": "atlascloud",
      "modality": "video",
      "name": "Veo 3.1 Lite",
      "unitPrice": 0.05,
      "sourceUrl": "https://www.atlascloud.ai/models/google/veo3.1-lite/text-to-video"
    },
    {
      "id": "replicate:seedance-1-pro:video",
      "provider": "replicate",
      "modality": "video",
      "name": "Seedance 1 Pro",
      "unitPrice": 0.06,
      "sourceUrl": "https://replicate.com/bytedance/seedance-1-pro"
    },
    {
      "id": "kie:kling-3.0-standard:video",
      "provider": "kie",
      "modality": "video",
      "name": "Kling 3.0 Standard",
      "unitPrice": 0.07,
      "sourceUrl": "https://kie.ai/kling-3-0"
    },
    {
      "id": "atlascloud:kling-3.0-standard:video",
      "provider": "atlascloud",
      "modality": "video",
      "name": "Kling 3.0 Standard",
      "unitPrice": 0.071,
      "sourceUrl": "https://www.atlascloud.ai/models/kwaivgi/kling-v3.0-std/text-to-video"
    },
    {
      "id": "atlascloud:veo-3.1-fast:video",
      "provider": "atlascloud",
      "modality": "video",
      "name": "Veo 3.1 Fast",
      "unitPrice": 0.08,
      "sourceUrl": "https://www.atlascloud.ai/models/google/veo3.1-fast/text-to-video"
    },
    {
      "id": "kie:wan-2.7:video",
      "provider": "kie",
      "modality": "video",
      "name": "Wan 2.7",
      "unitPrice": 0.08,
      "sourceUrl": "https://kie.ai/wan-2-7-video"
    },
    {
      "id": "atlascloud:kling-3.0-turbo:video",
      "provider": "atlascloud",
      "modality": "video",
      "name": "Kling 3.0 Turbo",
      "unitPrice": 0.095,
      "sourceUrl": "https://www.atlascloud.ai/models/kwaivgi/kling-v3.0-turbo/text-to-video"
    },
    {
      "id": "fal_ai:wan-2.7:video",
      "provider": "fal_ai",
      "modality": "video",
      "name": "Wan 2.7",
      "unitPrice": 0.1,
      "sourceUrl": "https://fal.ai/models/fal-ai/wan/v2.7/image-to-video"
    },
    {
      "id": "kie:kling-motion-control-3:video",
      "provider": "kie",
      "modality": "video",
      "name": "Kling Motion Control 3",
      "unitPrice": 0.1,
      "sourceUrl": "https://kie.ai/kling-3-motion-control"
    },
    {
      "id": "together:sora-2:video",
      "provider": "together",
      "modality": "video",
      "name": "Sora 2",
      "unitPrice": 0.1,
      "sourceUrl": "https://www.together.ai/pricing"
    },
    {
      "id": "kie:happyhorse-1-1:video",
      "provider": "kie",
      "modality": "video",
      "name": "Happyhorse 1 1",
      "unitPrice": 0.1125,
      "sourceUrl": "https://kie.ai/happyhorse-1-1"
    },
    {
      "id": "fal_ai:happyhorse-1-1:video",
      "provider": "fal_ai",
      "modality": "video",
      "name": "Happyhorse 1 1",
      "unitPrice": 0.14,
      "sourceUrl": "https://fal.ai/models/alibaba/happy-horse/v1.1/image-to-video"
    },
    {
      "id": "replicate:veo-3-fast:video",
      "provider": "replicate",
      "modality": "video",
      "name": "Veo 3 Fast",
      "unitPrice": 0.15,
      "sourceUrl": "https://replicate.com/google/veo-3-fast"
    },
    {
      "id": "replicate:luma-ray-2:video",
      "provider": "replicate",
      "modality": "video",
      "name": "Luma Ray 2",
      "unitPrice": 0.18,
      "sourceUrl": "https://replicate.com/luma/ray-2-720p"
    },
    {
      "id": "kie:seedance-2:video",
      "provider": "kie",
      "modality": "video",
      "name": "Seedance 2",
      "unitPrice": 0.205,
      "sourceUrl": "https://kie.ai/seedance-2-0"
    },
    {
      "id": "replicate:veo-3:video",
      "provider": "replicate",
      "modality": "video",
      "name": "Veo 3",
      "unitPrice": 0.4,
      "sourceUrl": "https://replicate.com/google/veo-3"
    }
  ],
  "speech": [
    {
      "id": "together:kokoro-82m:speech",
      "provider": "together",
      "modality": "speech",
      "name": "Kokoro 82m",
      "unitPrice": 4,
      "sourceUrl": "https://www.together.ai/pricing"
    },
    {
      "id": "together:orpheus-3b:speech",
      "provider": "together",
      "modality": "speech",
      "name": "Orpheus 3b",
      "unitPrice": 15,
      "sourceUrl": "https://www.together.ai/pricing"
    },
    {
      "id": "fal_ai:kokoro-82m:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Kokoro 82m",
      "unitPrice": 20,
      "sourceUrl": "https://fal.ai/models/fal-ai/kokoro/american-english"
    },
    {
      "id": "fal_ai:chatterbox:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Chatterbox",
      "unitPrice": 25,
      "sourceUrl": "https://fal.ai/models/fal-ai/chatterbox/text-to-speech"
    },
    {
      "id": "replicate:chatterbox:speech",
      "provider": "replicate",
      "modality": "speech",
      "name": "Chatterbox",
      "unitPrice": 25,
      "sourceUrl": "https://replicate.com/resemble-ai/chatterbox"
    },
    {
      "id": "fal_ai:seed-tts-2:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Seed TTS 2",
      "unitPrice": 30,
      "sourceUrl": "https://fal.ai/models/fal-ai/bytedance/seed-speech/tts/v2"
    },
    {
      "id": "elevenlabs:eleven-flash-v2.5:speech",
      "provider": "elevenlabs",
      "modality": "speech",
      "name": "Eleven Flash v2.5",
      "unitPrice": 50,
      "sourceUrl": "https://elevenlabs.io/pricing/api"
    },
    {
      "id": "elevenlabs:eleven-turbo-v2.5:speech",
      "provider": "elevenlabs",
      "modality": "speech",
      "name": "Eleven Turbo v2.5",
      "unitPrice": 50,
      "sourceUrl": "https://elevenlabs.io/pricing/api"
    },
    {
      "id": "fal_ai:eleven-turbo-v2.5:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Eleven Turbo v2.5",
      "unitPrice": 50,
      "sourceUrl": "https://fal.ai/models/fal-ai/elevenlabs/tts/turbo-v2.5"
    },
    {
      "id": "fal_ai:gemini-3.1-flash-tts:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Gemini 3.1 Flash TTS",
      "unitPrice": 50,
      "sourceUrl": "https://fal.ai/models/fal-ai/gemini-3.1-flash-tts"
    },
    {
      "id": "fal_ai:orpheus-3b:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Orpheus 3b",
      "unitPrice": 50,
      "sourceUrl": "https://fal.ai/models/fal-ai/orpheus-tts"
    },
    {
      "id": "kie:eleven-multilingual-v2:speech",
      "provider": "kie",
      "modality": "speech",
      "name": "Eleven Multilingual v2",
      "unitPrice": 60,
      "sourceUrl": "https://kie.ai/elevenlabs-tts"
    },
    {
      "id": "fal_ai:qwen3-tts:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Qwen3 TTS",
      "unitPrice": 90,
      "sourceUrl": "https://fal.ai/models/fal-ai/qwen-3-tts/text-to-speech/1.7b"
    },
    {
      "id": "elevenlabs:eleven-multilingual-v2:speech",
      "provider": "elevenlabs",
      "modality": "speech",
      "name": "Eleven Multilingual v2",
      "unitPrice": 100,
      "sourceUrl": "https://elevenlabs.io/pricing/api"
    },
    {
      "id": "elevenlabs:eleven-v3:speech",
      "provider": "elevenlabs",
      "modality": "speech",
      "name": "Eleven v3",
      "unitPrice": 100,
      "sourceUrl": "https://elevenlabs.io/pricing/api"
    },
    {
      "id": "fal_ai:eleven-v3:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Eleven v3",
      "unitPrice": 100,
      "sourceUrl": "https://fal.ai/models/fal-ai/elevenlabs/text-to-dialogue/eleven-v3"
    },
    {
      "id": "fal_ai:minimax-speech-02-hd:speech",
      "provider": "fal_ai",
      "modality": "speech",
      "name": "Minimax Speech 02 HD",
      "unitPrice": 100,
      "sourceUrl": "https://fal.ai/models/fal-ai/minimax/speech-02-hd"
    }
  ]
};
