// AUTO-GENERATED by marketing/scripts/generate-miniapp-entries.mjs — do not edit by hand.
// Regenerate: npm run gen:apps
import type { MiniAppEntry } from "./miniApps";

export const miniAppEntries: MiniAppEntry[] = [
  {
    "route": "/apps/ask-your-documents",
    "title": "Ask Your Documents — Free AI Mini App | NodeTool",
    "description": "Ask your own documents — with a local mode that never leaves your machine.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "ask-your-documents",
    "name": "Ask Your Documents",
    "summary": "Retrieval-augmented answers with citations, and a fully local fallback that reads one pasted document instead of the vector store.",
    "featured": false,
    "note": "🖥️ The retrieval mode embeds with Ollama nomic-embed-text and answers with OpenAI, so it needs both. Local mode needs only Ollama.",
    "workflows": [
      {
        "name": "Chat With Your Documents",
        "slug": "chat-with-your-documents",
        "route": "/templates/chat-with-your-documents"
      },
      {
        "name": "Private Assistant",
        "slug": "private-assistant",
        "route": "/templates/private-assistant"
      }
    ],
    "templateRoute": "/templates/chat-with-your-documents",
    "screenshot": "/apps/ask-your-documents.png",
    "tags": [
      "assistant",
      "citations",
      "llm",
      "local",
      "offline",
      "ollama",
      "privacy",
      "rag",
      "retrieval",
      "vectorstore"
    ],
    "heading": "📄 Ask Your Documents",
    "tagline": "Ask your own documents — with a local mode that never leaves your machine.",
    "buttonLabel": "Search my documents",
    "inputs": [
      {
        "label": "Your question",
        "kind": "text"
      },
      {
        "label": "Local only (no cloud)",
        "kind": "toggle"
      },
      {
        "label": "Search keyword",
        "kind": "text"
      },
      {
        "label": "Or paste one document",
        "kind": "text"
      },
      {
        "label": "Answer tone",
        "kind": "choice"
      },
      {
        "label": "Document: specs",
        "kind": "text"
      },
      {
        "label": "Document: charging",
        "kind": "text"
      },
      {
        "label": "Document: warranty",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Answer",
        "kind": "text"
      },
      {
        "label": "Sources used",
        "kind": "text"
      },
      {
        "label": "Local answer",
        "kind": "text"
      }
    ],
    "widgetCount": 25
  },
  {
    "route": "/apps/brand-and-social",
    "title": "Brand & Social — Free AI Mini App | NodeTool",
    "description": "One brand identity drives three deliverables.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "brand-and-social",
    "name": "Brand & Social",
    "summary": "Fill in your brand once — the asset kit, the thumbnail factory, and the content calendar all read the same values.",
    "featured": true,
    "note": "🔑 Needs OpenAI and FAL keys. Your brand name, audience, and voice persist between sessions.",
    "workflows": [
      {
        "name": "Brand Asset Generator",
        "slug": "brand-asset-generator",
        "route": "/templates/brand-asset-generator"
      },
      {
        "name": "Hook & Thumbnail Factory",
        "slug": "hook-and-thumbnail-factory",
        "route": "/templates/hook-and-thumbnail-factory"
      },
      {
        "name": "Social Media Calendar Filler",
        "slug": "social-media-calendar-filler",
        "route": "/templates/social-media-calendar-filler"
      }
    ],
    "templateRoute": "/templates/brand-asset-generator",
    "screenshot": "/apps/brand-and-social.png",
    "tags": [
      "brand-asset",
      "branding",
      "content",
      "design",
      "example",
      "image",
      "images",
      "marketing",
      "planning",
      "social",
      "social media",
      "video"
    ],
    "heading": "🎨 Brand & Social",
    "tagline": "One brand identity drives three deliverables.",
    "buttonLabel": "Generate brand assets",
    "inputs": [
      {
        "label": "Brand name",
        "kind": "text"
      },
      {
        "label": "Who is it for?",
        "kind": "text"
      },
      {
        "label": "Brand voice",
        "kind": "text"
      },
      {
        "label": "Describe your brand",
        "kind": "text"
      },
      {
        "label": "Tagline",
        "kind": "text"
      },
      {
        "label": "Primary color",
        "kind": "color"
      },
      {
        "label": "What's your video about?",
        "kind": "text"
      },
      {
        "label": "How many hooks?",
        "kind": "number"
      },
      {
        "label": "This month's theme",
        "kind": "text"
      },
      {
        "label": "Posts per week",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Your brand assets",
        "kind": "image"
      },
      {
        "label": "Brand brief",
        "kind": "text"
      },
      {
        "label": "Thumbnail gallery",
        "kind": "image"
      },
      {
        "label": "Hook ideas",
        "kind": "text"
      },
      {
        "label": "Featured thumbnail",
        "kind": "image"
      },
      {
        "label": "Content calendar",
        "kind": "data"
      },
      {
        "label": "Post visuals",
        "kind": "image"
      },
      {
        "label": "Captions & hashtags",
        "kind": "text"
      }
    ],
    "widgetCount": 44
  },
  {
    "route": "/apps/concept-studio",
    "title": "Concept Studio — Free AI Mini App | NodeTool",
    "description": "Generate a gallery, pick one, polish it.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "concept-studio",
    "name": "Concept Studio",
    "summary": "The creative iteration loop: fan a brief into concept art, mix animals into creatures, then run the picked image through a keyless filter chain.",
    "featured": true,
    "note": "🎨 Generating needs OpenAI and FAL keys. Polishing is GPU-only and runs with no keys.",
    "workflows": [
      {
        "name": "Concept Art Iteration Board",
        "slug": "concept-art-iteration-board",
        "route": "/templates/concept-art-iteration-board"
      },
      {
        "name": "Pokemon Maker",
        "slug": "pokemon-maker",
        "route": "/templates/pokemon-maker"
      },
      {
        "name": "Image Enhance",
        "slug": "image-enhance",
        "route": "/templates/image-enhance"
      }
    ],
    "templateRoute": "/templates/concept-art-iteration-board",
    "screenshot": "/apps/concept-studio.png",
    "tags": [
      "concept-art",
      "example",
      "image",
      "planning",
      "start"
    ],
    "heading": "🖌️ Concept Studio",
    "tagline": "Generate a gallery, pick one, polish it.",
    "buttonLabel": "Generate concept art",
    "inputs": [
      {
        "label": "Creative brief",
        "kind": "text"
      },
      {
        "label": "Art style",
        "kind": "choice"
      },
      {
        "label": "Mood keywords",
        "kind": "text"
      },
      {
        "label": "How many variations?",
        "kind": "number"
      },
      {
        "label": "Mix these animals",
        "kind": "text"
      },
      {
        "label": "Style",
        "kind": "choice"
      },
      {
        "label": "The image you picked",
        "kind": "image"
      },
      {
        "label": "Denoise",
        "kind": "number"
      },
      {
        "label": "Brightness",
        "kind": "number"
      },
      {
        "label": "Contrast",
        "kind": "number"
      },
      {
        "label": "Saturation",
        "kind": "number"
      },
      {
        "label": "Sharpen",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Concept art",
        "kind": "image"
      },
      {
        "label": "Your creatures",
        "kind": "image"
      },
      {
        "label": "Polished",
        "kind": "image"
      }
    ],
    "widgetCount": 36
  },
  {
    "route": "/apps/dataset-builder",
    "title": "Dataset Builder — Free AI Mini App | NodeTool",
    "description": "Describe the dataset you need — get it as a table.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "dataset-builder",
    "name": "Dataset Builder",
    "summary": "The smallest app in the set, and the reference for the Table widget: a dataframe reads better as rows than as a Preview node.",
    "featured": false,
    "note": "🔑 Needs an OpenAI key.",
    "workflows": [
      {
        "name": "Data Generator",
        "slug": "data-generator",
        "route": "/templates/data-generator"
      }
    ],
    "templateRoute": "/templates/data-generator",
    "screenshot": "/apps/dataset-builder.png",
    "tags": [
      "agents"
    ],
    "heading": "🧮 Dataset Builder",
    "tagline": "Describe the dataset you need — get it as a table.",
    "buttonLabel": "Generate data",
    "inputs": [
      {
        "label": "What data do you need?",
        "kind": "text"
      },
      {
        "label": "How many rows?",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Generated dataset",
        "kind": "data"
      }
    ],
    "widgetCount": 12
  },
  {
    "route": "/apps/film-studio",
    "title": "Film Studio — Free AI Mini App | NodeTool",
    "description": "Brief → direction → storyboard → cut → key art.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "film-studio",
    "name": "Film Studio",
    "summary": "The showcase run: one brief drives a directed short, an editable rough cut, and the poster that sells it.",
    "featured": true,
    "note": "💸 This app spends real money — Veo 3.1 video and Replicate MusicGen. Run it once, deliberately.",
    "workflows": [
      {
        "name": "Script to Screen",
        "slug": "script-to-screen",
        "route": "/templates/script-to-screen"
      },
      {
        "name": "Directed Film to Timeline",
        "slug": "directed-film-to-timeline",
        "route": "/templates/directed-film-to-timeline"
      },
      {
        "name": "Movie Posters",
        "slug": "movie-posters",
        "route": "/templates/movie-posters"
      }
    ],
    "templateRoute": "/templates/script-to-screen",
    "screenshot": "/apps/film-studio.png",
    "tags": [
      "ai",
      "creative",
      "director",
      "example",
      "generation",
      "image",
      "start",
      "storyboard",
      "storytelling",
      "timeline",
      "video"
    ],
    "heading": "🎬 Film Studio",
    "tagline": "Brief → direction → storyboard → cut → key art.",
    "buttonLabel": "Shoot my film",
    "inputs": [
      {
        "label": "Your film in one line",
        "kind": "text"
      },
      {
        "label": "Visual style",
        "kind": "text"
      },
      {
        "label": "Number of shots",
        "kind": "text"
      },
      {
        "label": "Movie title",
        "kind": "text"
      },
      {
        "label": "Genre",
        "kind": "choice"
      }
    ],
    "outputs": [
      {
        "label": "Direction document",
        "kind": "text"
      },
      {
        "label": "Storyboard keyframes",
        "kind": "image"
      },
      {
        "label": "Finished film",
        "kind": "video"
      },
      {
        "label": "Editable rough cut",
        "kind": "video"
      },
      {
        "label": "Your poster",
        "kind": "image"
      }
    ],
    "widgetCount": 31
  },
  {
    "route": "/apps/meeting-room",
    "title": "Meeting Room — Free AI Mini App | NodeTool",
    "description": "Recording in, minutes out — then question the transcript.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "meeting-room",
    "name": "Meeting Room",
    "summary": "Transcribe a recording, summarize it into notes and action items, then ask follow-up questions of the transcript on a local model.",
    "featured": true,
    "note": "🎙️ Transcription uses FAL Whisper and the summary uses OpenAI. The follow-up questions run on a local Ollama model, so they cost nothing.",
    "workflows": [
      {
        "name": "Transcribe Audio",
        "slug": "transcribe-audio",
        "route": "/templates/transcribe-audio"
      },
      {
        "name": "Meeting Transcript Summarizer",
        "slug": "meeting-transcript-summarizer",
        "route": "/templates/meeting-transcript-summarizer"
      },
      {
        "name": "Private Assistant",
        "slug": "private-assistant",
        "route": "/templates/private-assistant"
      }
    ],
    "templateRoute": "/templates/transcribe-audio",
    "screenshot": "/apps/meeting-room.png",
    "tags": [
      "asr",
      "assistant",
      "audio",
      "dataframe",
      "llm",
      "local",
      "offline",
      "ollama",
      "privacy",
      "start"
    ],
    "heading": "🎧 Meeting Room",
    "tagline": "Recording in, minutes out — then question the transcript.",
    "buttonLabel": "Transcribe",
    "inputs": [
      {
        "label": "Meeting recording",
        "kind": "audio"
      },
      {
        "label": "Your question",
        "kind": "text"
      },
      {
        "label": "Answer tone",
        "kind": "choice"
      }
    ],
    "outputs": [
      {
        "label": "Transcript",
        "kind": "text"
      },
      {
        "label": "Meeting notes",
        "kind": "text"
      },
      {
        "label": "Action items",
        "kind": "data"
      },
      {
        "label": "Transcript used",
        "kind": "text"
      },
      {
        "label": "Answer",
        "kind": "text"
      }
    ],
    "widgetCount": 31
  },
  {
    "route": "/apps/model-arena",
    "title": "Model Arena — Free AI Mini App | NodeTool",
    "description": "One brief, three frontier models, answered side by side.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "model-arena",
    "name": "Model Arena",
    "summary": "Three answers in three columns, each streaming independently. A missing provider key fails one column, not the run.",
    "featured": false,
    "note": "🔑 Needs OpenAI, Anthropic, and Google keys — one per column.",
    "workflows": [
      {
        "name": "Model Arena",
        "slug": "model-arena",
        "route": "/templates/model-arena"
      }
    ],
    "templateRoute": "/templates/model-arena",
    "screenshot": "/apps/model-arena.png",
    "tags": [
      "agents",
      "comparison",
      "example",
      "llm",
      "providers"
    ],
    "heading": "⚖️ Model Arena",
    "tagline": "One brief, three frontier models, answered side by side.",
    "buttonLabel": "Compare the models",
    "inputs": [
      {
        "label": "Your brief",
        "kind": "text"
      },
      {
        "label": "Extra context",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "OpenAI",
        "kind": "text"
      },
      {
        "label": "Anthropic",
        "kind": "text"
      },
      {
        "label": "Google",
        "kind": "text"
      }
    ],
    "widgetCount": 16
  },
  {
    "route": "/apps/photo-studio",
    "title": "Photo Studio — Free AI Mini App | NodeTool",
    "description": "Drag five sliders and watch the photo re-render — then run the same grade over a whole folder.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "photo-studio",
    "name": "Photo Studio",
    "summary": "A live photo editor and a batch retoucher behind one surface. The single-photo grade is pure GPU filters, so it runs with no API key at all.",
    "featured": true,
    "note": "✨ Enhance is GPU-only and needs no keys. Batch adds a FAL grading pass, so it needs a FAL key.",
    "workflows": [
      {
        "name": "Image Enhance",
        "slug": "image-enhance",
        "route": "/templates/image-enhance"
      },
      {
        "name": "Photo Enhancement Suite",
        "slug": "photo-enhancement-suite",
        "route": "/templates/photo-enhancement-suite"
      }
    ],
    "templateRoute": "/templates/image-enhance",
    "screenshot": "/apps/photo-studio.png",
    "tags": [
      "batch processing",
      "example",
      "image",
      "photo",
      "start"
    ],
    "heading": "📸 Photo Studio",
    "tagline": "Drag five sliders and watch the photo re-render — then run the same grade over a whole folder.",
    "buttonLabel": "Enhance my photo",
    "inputs": [
      {
        "label": "Your photo",
        "kind": "image"
      },
      {
        "label": "Denoise",
        "kind": "number"
      },
      {
        "label": "Brightness",
        "kind": "number"
      },
      {
        "label": "Contrast",
        "kind": "number"
      },
      {
        "label": "Saturation",
        "kind": "number"
      },
      {
        "label": "Sharpen",
        "kind": "number"
      },
      {
        "label": "Your photos",
        "kind": "image"
      },
      {
        "label": "Brightness",
        "kind": "number"
      },
      {
        "label": "Color boost",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Enhanced photo",
        "kind": "image"
      },
      {
        "label": "Enhanced photos",
        "kind": "image"
      }
    ],
    "widgetCount": 26
  },
  {
    "route": "/apps/product-launch-kit",
    "title": "Product Launch Kit — Free AI Mini App | NodeTool",
    "description": "One product photo in, mockups and a launch video out.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "product-launch-kit",
    "name": "Product Launch Kit",
    "summary": "Stage a product photo into lifestyle mockups, then — deliberately, because it costs real money — turn the same photo into a launch video.",
    "featured": false,
    "note": "💸 Mockups need OpenAI and FAL. The launch video runs on Veo and costs credits per run, so it has its own button.",
    "workflows": [
      {
        "name": "Product Mockup Generator",
        "slug": "product-mockup-generator",
        "route": "/templates/product-mockup-generator"
      },
      {
        "name": "Product Video Generator",
        "slug": "product-video-generator",
        "route": "/templates/product-video-generator"
      }
    ],
    "templateRoute": "/templates/product-mockup-generator",
    "screenshot": "/apps/product-launch-kit.png",
    "tags": [
      "business",
      "data",
      "design",
      "example",
      "mockup",
      "product-mockup",
      "video"
    ],
    "heading": "📦 Product Launch Kit",
    "tagline": "One product photo in, mockups and a launch video out.",
    "buttonLabel": "Generate mockups",
    "inputs": [
      {
        "label": "Product photo",
        "kind": "image"
      },
      {
        "label": "Who is it for?",
        "kind": "text"
      },
      {
        "label": "Product name",
        "kind": "text"
      },
      {
        "label": "Describe the product",
        "kind": "text"
      },
      {
        "label": "How many scenes?",
        "kind": "number"
      },
      {
        "label": "Campaign brief",
        "kind": "text"
      },
      {
        "label": "Key features",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Mockups",
        "kind": "image"
      },
      {
        "label": "Shot list",
        "kind": "text"
      },
      {
        "label": "Launch video",
        "kind": "video"
      }
    ],
    "widgetCount": 27
  },
  {
    "route": "/apps/research-desk",
    "title": "Research Desk — Free AI Mini App | NodeTool",
    "description": "One topic, three sources, three briefings side by side.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "research-desk",
    "name": "Research Desk",
    "summary": "A research agent, a Hacker News reader, and an RSS digest all take the same topic and stream into their own panel.",
    "featured": true,
    "note": "🔑 Needs an OpenAI key. All three briefings run in parallel from one button.",
    "workflows": [
      {
        "name": "Research Agent",
        "slug": "research-agent",
        "route": "/templates/research-agent"
      },
      {
        "name": "Hacker News Agent",
        "slug": "hacker-news-agent",
        "route": "/templates/hacker-news-agent"
      },
      {
        "name": "Summarize RSS",
        "slug": "summarize-rss",
        "route": "/templates/summarize-rss"
      }
    ],
    "templateRoute": "/templates/research-agent",
    "screenshot": "/apps/research-desk.png",
    "tags": [
      "agent",
      "analysis",
      "browser",
      "citations",
      "example",
      "hackernews",
      "news",
      "research",
      "search",
      "streaming"
    ],
    "heading": "🕵️ Research Desk",
    "tagline": "One topic, three sources, three briefings side by side.",
    "buttonLabel": "Run the desk",
    "inputs": [
      {
        "label": "Research topic",
        "kind": "text"
      },
      {
        "label": "Who is it for?",
        "kind": "choice"
      },
      {
        "label": "RSS feed",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Research brief",
        "kind": "text"
      },
      {
        "label": "Hacker News",
        "kind": "text"
      },
      {
        "label": "Feed digest",
        "kind": "text"
      }
    ],
    "widgetCount": 22
  },
  {
    "route": "/apps/study-buddy",
    "title": "Study Buddy — Free AI Mini App | NodeTool",
    "description": "A deck of flashcards and the concept behind it, side by side.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "study-buddy",
    "name": "Study Buddy",
    "summary": "Structured data an app renders better than a graph does: the cards land in a table, the explanation beside them.",
    "featured": false,
    "note": "🔑 Needs an OpenAI key. Your topic persists between sessions.",
    "workflows": [
      {
        "name": "Flashcard Generator",
        "slug": "flashcard-generator",
        "route": "/templates/flashcard-generator"
      },
      {
        "name": "Prompt Template",
        "slug": "prompt-template",
        "route": "/templates/prompt-template"
      }
    ],
    "templateRoute": "/templates/flashcard-generator",
    "screenshot": "/apps/study-buddy.png",
    "tags": [
      "ai",
      "beginner",
      "education",
      "example",
      "flashcards",
      "learning",
      "persistence",
      "start",
      "template",
      "tutorial"
    ],
    "heading": "🃏 Study Buddy",
    "tagline": "A deck of flashcards and the concept behind it, side by side.",
    "buttonLabel": "Make flashcards",
    "inputs": [
      {
        "label": "Study topic",
        "kind": "text"
      },
      {
        "label": "How many cards?",
        "kind": "number"
      },
      {
        "label": "Explain it to…",
        "kind": "choice"
      }
    ],
    "outputs": [
      {
        "label": "Flashcards",
        "kind": "data"
      },
      {
        "label": "The concept behind this deck",
        "kind": "text"
      }
    ],
    "widgetCount": 16
  }
];
