// AUTO-GENERATED by marketing/scripts/generate-miniapp-entries.mjs — do not edit by hand.
// Regenerate: npm run gen:apps
import type { MiniAppEntry } from "./miniApps";

export const miniAppEntries: MiniAppEntry[] = [
  {
    "route": "/apps/ad-creative-factory",
    "title": "Ad Creative Factory — Free AI Mini App | NodeTool",
    "description": "Turn one product photo and one offer into a batch of ready-to-test video ads.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "ad-creative-factory",
    "name": "Ad Creative Factory",
    "summary": "Turn one product photo and one offer into a batch of ready-to-test vertical video ads. A strategist agent plans a persona × angle test matrix, a list generator writes one spoken hook per cell, and every hook becomes a staged product scene, an animated 9:16 clip, and a voiceover mixed on top.",
    "templateRoute": "/templates/ad-creative-factory",
    "screenshot": "/apps/ad-creative-factory.png",
    "tags": [
      "marketing",
      "advertising",
      "video",
      "audio",
      "agents",
      "example"
    ],
    "heading": "🎬 Ad Creative Factory",
    "tagline": "Turn one product photo and one offer into a batch of ready-to-test video ads.",
    "buttonLabel": "Generate my ads",
    "inputs": [
      {
        "label": "Product & offer",
        "kind": "text"
      },
      {
        "label": "Who is it for?",
        "kind": "text"
      },
      {
        "label": "How many ad variants?",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Hooks",
        "kind": "text"
      },
      {
        "label": "Finished Ads",
        "kind": "video"
      }
    ],
    "widgetCount": 14
  },
  {
    "route": "/apps/agent-google-search",
    "title": "Agent Google Search — Free AI Mini App | NodeTool",
    "description": "Ask anything — an agent runs the Google searches and reports back.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "agent-google-search",
    "name": "Agent Google Search",
    "summary": "Demonstrates an Agent using dynamic outputs to perform Google searches and display results.",
    "templateRoute": "/templates/agent-google-search",
    "screenshot": "/apps/agent-google-search.png",
    "tags": [
      "agent",
      "google",
      "search",
      "dynamic-outputs",
      "example"
    ],
    "heading": "🔎 Agent Google Search",
    "tagline": "Ask anything — an agent runs the Google searches and reports back.",
    "buttonLabel": "Search with the agent",
    "inputs": [],
    "outputs": [
      {
        "label": "Results",
        "kind": "text"
      }
    ],
    "widgetCount": 6
  },
  {
    "route": "/apps/audio-to-image",
    "title": "Audio To Image — Free AI Mini App | NodeTool",
    "description": "Describe a scene out loud — get it back as a picture.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "audio-to-image",
    "name": "Audio To Image",
    "summary": "Transform spoken descriptions into images with this workflow. Record or upload audio, which is transcribed by Whisper and then visualized by Stable Diffusion. Perfect for quickly generating images from verbal ideas without typing.",
    "templateRoute": "/templates/audio-to-image",
    "screenshot": "/apps/audio-to-image.png",
    "tags": [
      "huggingface",
      "multimodal",
      "start",
      "example"
    ],
    "heading": "🎙️ Audio To Image",
    "tagline": "Describe a scene out loud — get it back as a picture.",
    "buttonLabel": "Turn my voice into art",
    "inputs": [],
    "outputs": [
      {
        "label": "Image",
        "kind": "image"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/brand-asset-generator",
    "title": "Brand Asset Generator — Free AI Mini App | NodeTool",
    "description": "Type your brand name and vibe — get logo-ready visuals in seconds.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "brand-asset-generator",
    "name": "Brand Asset Generator",
    "summary": "Generate brand assets for a given brand.",
    "templateRoute": "/templates/brand-asset-generator",
    "screenshot": "/apps/brand-asset-generator.png",
    "tags": [
      "brand-asset",
      "branding",
      "design",
      "example"
    ],
    "heading": "🎨 Brand Asset Generator",
    "tagline": "Type your brand name and vibe — get logo-ready visuals in seconds.",
    "buttonLabel": "Generate brand assets",
    "inputs": [
      {
        "label": "Tagline",
        "kind": "text"
      },
      {
        "label": "Brand name",
        "kind": "text"
      },
      {
        "label": "Primary color (hex)",
        "kind": "text"
      },
      {
        "label": "Describe your brand",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Brand Asset",
        "kind": "image"
      }
    ],
    "widgetCount": 11
  },
  {
    "route": "/apps/cold-outreach-co-pilot",
    "title": "Cold Outreach Co-Pilot — Free AI Mini App | NodeTool",
    "description": "An agent researches your prospect and writes a cold email that opens with a real, specific detail.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "cold-outreach-co-pilot",
    "name": "Cold Outreach Co-Pilot",
    "summary": "An autonomous agent researches a prospect on the web and writes a personalized cold email — opening with a real, specific detail — plus a follow-up. Personalization at scale without the copy-paste.",
    "templateRoute": "/templates/cold-outreach-co-pilot",
    "screenshot": "/apps/cold-outreach-co-pilot.png",
    "tags": [
      "agents",
      "sales",
      "outreach",
      "marketing",
      "example"
    ],
    "heading": "✉️ Cold Outreach Co-Pilot",
    "tagline": "An agent researches your prospect and writes a cold email that opens with a real, specific detail.",
    "buttonLabel": "Research & write my email",
    "inputs": [
      {
        "label": "Who are you reaching out to?",
        "kind": "text"
      },
      {
        "label": "What are you offering?",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Company Summary",
        "kind": "text"
      },
      {
        "label": "Pain Points",
        "kind": "text"
      },
      {
        "label": "Personalized Email",
        "kind": "text"
      }
    ],
    "widgetCount": 14
  },
  {
    "route": "/apps/color-boost-video",
    "title": "Color Boost Video — Free AI Mini App | NodeTool",
    "description": "Give any clip a cinematic color grade — no editor required.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "color-boost-video",
    "name": "Color Boost Video",
    "summary": "Grade a short video clip by splitting it into frames, applying exposure/contrast and saturation/vibrance adjustments per frame, then reassembling the result for cinematic color.",
    "templateRoute": "/templates/color-boost-video",
    "screenshot": "/apps/color-boost-video.png",
    "tags": [
      "video",
      "start"
    ],
    "heading": "🌈 Color Boost Video",
    "tagline": "Give any clip a cinematic color grade — no editor required.",
    "buttonLabel": "Boost my video",
    "inputs": [],
    "outputs": [
      {
        "label": "Graded Video",
        "kind": "video"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/concept-art-iteration-board",
    "title": "Concept Art Iteration Board — Free AI Mini App | NodeTool",
    "description": "Generate concept art from a brief, style, and mood.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "concept-art-iteration-board",
    "name": "Concept Art Iteration Board",
    "summary": "Turn a creative brief, style, and mood into concept art variations. An agent sets the art direction, then a batch of images is generated.",
    "templateRoute": "/templates/concept-art-iteration-board",
    "screenshot": "/apps/concept-art-iteration-board.png",
    "tags": [
      "concept-art",
      "planning",
      "example"
    ],
    "heading": "🎨 Concept Art Board",
    "tagline": "Generate concept art from a brief, style, and mood.",
    "buttonLabel": "Generate Concept Art",
    "inputs": [
      {
        "label": "Creative Brief",
        "kind": "text"
      },
      {
        "label": "Art Style",
        "kind": "text"
      },
      {
        "label": "Mood Keywords",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Concept Art",
        "kind": "image"
      }
    ],
    "widgetCount": 9
  },
  {
    "route": "/apps/conditional-logic-engine",
    "title": "Conditional Logic Engine — Free AI Mini App | NodeTool",
    "description": "Enter a value and see how the workflow routes it.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "conditional-logic-engine",
    "name": "Conditional Logic Engine",
    "summary": "Workflow that demonstrates multi-branch decision logic with value routing.",
    "templateRoute": "/templates/conditional-logic-engine",
    "screenshot": "/apps/conditional-logic-engine.png",
    "tags": [
      "boolean"
    ],
    "heading": "🔀 Conditional Logic Engine",
    "tagline": "Enter a value and see how the workflow routes it.",
    "buttonLabel": "Run",
    "inputs": [
      {
        "label": "Value",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Result",
        "kind": "text"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/creative-story-ideas",
    "title": "Creative Story Ideas — Free AI Mini App | NodeTool",
    "description": "Generate creative story ideas from a genre and character type.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "creative-story-ideas",
    "name": "Creative Story Ideas",
    "summary": "A beginner-friendly template demonstrating core NodeTool concepts: inputs, templates, LLM agents, streaming, and outputs. Generate creative story ideas based on your preferences.",
    "templateRoute": "/templates/creative-story-ideas",
    "screenshot": "/apps/creative-story-ideas.png",
    "tags": [
      "start",
      "beginner",
      "tutorial",
      "template",
      "example"
    ],
    "heading": "✨ Creative Story Ideas",
    "tagline": "Generate creative story ideas from a genre and character type.",
    "buttonLabel": "Generate Story Ideas",
    "inputs": [
      {
        "label": "Genre",
        "kind": "text"
      },
      {
        "label": "Main Character Type",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Ideas",
        "kind": "text"
      }
    ],
    "widgetCount": 8
  },
  {
    "route": "/apps/data-generator",
    "title": "Data Generator — Free AI Mini App | NodeTool",
    "description": "Describe the dataset you need — an agent generates it, structured and ready.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "data-generator",
    "name": "Data Generator",
    "summary": "Generate structured data using AI agents",
    "templateRoute": "/templates/data-generator",
    "screenshot": "/apps/data-generator.png",
    "tags": [
      "agents"
    ],
    "heading": "🧮 Data Generator",
    "tagline": "Describe the dataset you need — an agent generates it, structured and ready.",
    "buttonLabel": "Generate data",
    "inputs": [],
    "outputs": [
      {
        "label": "Generated Data",
        "kind": "data"
      }
    ],
    "widgetCount": 6
  },
  {
    "route": "/apps/fetch-papers",
    "title": "Fetch Papers — Free AI Mini App | NodeTool",
    "description": "Automatically fetch the latest research papers, downloaded and organized.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "fetch-papers",
    "name": "Fetch Papers",
    "summary": "This workflow automatically fetches and downloads research papers from the Awesome Transformers GitHub repository. It extracts paper links from the README.md file, filters for actual papers, and downloads them to a specified folder. Ideal for researchers and AI enthusiasts who want to stay updated with the latest transformer model papers.",
    "templateRoute": "/templates/fetch-papers",
    "screenshot": "/apps/fetch-papers.png",
    "tags": [
      "automation"
    ],
    "heading": "📚 Fetch Papers",
    "tagline": "Automatically fetch the latest research papers, downloaded and organized.",
    "buttonLabel": "Fetch papers",
    "inputs": [],
    "outputs": [
      {
        "label": "Preview",
        "kind": "text"
      }
    ],
    "widgetCount": 6
  },
  {
    "route": "/apps/flashcard-generator",
    "title": "Flashcard Generator — Free AI Mini App | NodeTool",
    "description": "Enter any topic and generate study flashcards.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "flashcard-generator",
    "name": "Flashcard Generator",
    "summary": "Generate study flashcards using AI and store them persistently in a database. Enter any topic and get instant flashcards that are saved for future review.",
    "templateRoute": "/templates/flashcard-generator",
    "screenshot": "/apps/flashcard-generator.png",
    "tags": [
      "education",
      "database",
      "ai",
      "flashcards",
      "learning"
    ],
    "heading": "🃏 Flashcard Generator",
    "tagline": "Enter any topic and generate study flashcards.",
    "buttonLabel": "Generate Flashcards",
    "inputs": [
      {
        "label": "Topic",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Flashcards",
        "kind": "data"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/hacker-news-agent",
    "title": "Hacker News Agent — Free AI Mini App | NodeTool",
    "description": "One click for a smart digest of today's Hacker News front page.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "hacker-news-agent",
    "name": "Hacker News Agent",
    "summary": "Scrape and analyze the front page of Hacker News.",
    "templateRoute": "/templates/hacker-news-agent",
    "screenshot": "/apps/hacker-news-agent.png",
    "tags": [
      "hackernews",
      "news",
      "analysis"
    ],
    "heading": "🗞️ Hacker News Agent",
    "tagline": "One click for a smart digest of today's Hacker News front page.",
    "buttonLabel": "Analyze today's front page",
    "inputs": [],
    "outputs": [
      {
        "label": "Analysis",
        "kind": "text"
      }
    ],
    "widgetCount": 6
  },
  {
    "route": "/apps/hook-and-thumbnail-factory",
    "title": "Hook & Thumbnail Factory — Free AI Mini App | NodeTool",
    "description": "Give it a video topic — get scroll-stopping hooks and a matching thumbnail.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "hook-and-thumbnail-factory",
    "name": "Hook & Thumbnail Factory",
    "summary": "Turn a video topic into scroll-stopping hook ideas and a matching AI thumbnail for each — a faceless short-form content starter kit in one run.",
    "templateRoute": "/templates/hook-and-thumbnail-factory",
    "screenshot": "/apps/hook-and-thumbnail-factory.png",
    "tags": [
      "image",
      "content",
      "social",
      "video",
      "example"
    ],
    "heading": "🪝 Hook & Thumbnail Factory",
    "tagline": "Give it a video topic — get scroll-stopping hooks and a matching thumbnail.",
    "buttonLabel": "Make hooks & thumbnail",
    "inputs": [
      {
        "label": "What's your video about?",
        "kind": "text"
      },
      {
        "label": "Who's watching?",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Hooks",
        "kind": "text"
      },
      {
        "label": "Thumbnail",
        "kind": "image"
      }
    ],
    "widgetCount": 12
  },
  {
    "route": "/apps/image-enhance",
    "title": "Image Enhance — Free AI Mini App | NodeTool",
    "description": "Sharper, brighter, cleaner — enhance any photo in one click.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "image-enhance",
    "name": "Image Enhance",
    "summary": "Improve image quality with basic enhancement tools like sharpening, contrast and color adjustment",
    "templateRoute": "/templates/image-enhance",
    "screenshot": "/apps/image-enhance.png",
    "tags": [
      "image",
      "start",
      "example"
    ],
    "heading": "✨ Image Enhance",
    "tagline": "Sharper, brighter, cleaner — enhance any photo in one click.",
    "buttonLabel": "Enhance my photo",
    "inputs": [],
    "outputs": [
      {
        "label": "Enhanced Image",
        "kind": "image"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/image-to-audio-story",
    "title": "Image To Audio Story — Free AI Mini App | NodeTool",
    "description": "Point it at a picture — hear the story it tells, narrated aloud.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "image-to-audio-story",
    "name": "Image To Audio Story",
    "summary": "Generate and narrate creative stories from images using AI",
    "templateRoute": "/templates/image-to-audio-story",
    "screenshot": "/apps/image-to-audio-story.png",
    "tags": [
      "start",
      "multimodal",
      "example"
    ],
    "heading": "🔊 Image To Audio Story",
    "tagline": "Point it at a picture — hear the story it tells, narrated aloud.",
    "buttonLabel": "Tell me its story",
    "inputs": [],
    "outputs": [
      {
        "label": "Narration",
        "kind": "audio"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/image-to-video-animation",
    "title": "Image to Video Animation — Free AI Mini App | NodeTool",
    "description": "Type a scene — get a still, then watch it come alive as a cinematic clip.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "image-to-video-animation",
    "name": "Image to Video Animation",
    "summary": "Generate a high-quality still from text, then animate it into a short cinematic clip.",
    "templateRoute": "/templates/image-to-video-animation",
    "screenshot": "/apps/image-to-video-animation.png",
    "tags": [
      "image",
      "video",
      "example"
    ],
    "heading": "🎥 Image to Video Animation",
    "tagline": "Type a scene — get a still, then watch it come alive as a cinematic clip.",
    "buttonLabel": "Animate my scene",
    "inputs": [
      {
        "label": "Describe the scene",
        "kind": "text"
      },
      {
        "label": "How should it move?",
        "kind": "text"
      },
      {
        "label": "Length & pacing",
        "kind": "text"
      },
      {
        "label": "What to avoid",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Animation",
        "kind": "video"
      }
    ],
    "widgetCount": 11
  },
  {
    "route": "/apps/learning-path-generator",
    "title": "Learning Path Generator — Free AI Mini App | NodeTool",
    "description": "Enter a topic and get a structured learning path.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "learning-path-generator",
    "name": "Learning Path Generator",
    "summary": "Create a comprehensive learning path for a topic.",
    "templateRoute": "/templates/learning-path-generator",
    "screenshot": "/apps/learning-path-generator.png",
    "tags": [
      "education",
      "planning",
      "example"
    ],
    "heading": "🎓 Learning Path Generator",
    "tagline": "Enter a topic and get a structured learning path.",
    "buttonLabel": "Generate Learning Path",
    "inputs": [
      {
        "label": "Topic",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Learning Path",
        "kind": "text"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/meeting-transcript-summarizer",
    "title": "Meeting Transcript Summarizer — Free AI Mini App | NodeTool",
    "description": "Drop in a meeting recording — get the transcript and crisp notes back.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "meeting-transcript-summarizer",
    "name": "Meeting Transcript Summarizer",
    "summary": "Automatically transcribe a meeting recording and generate concise notes.",
    "templateRoute": "/templates/meeting-transcript-summarizer",
    "screenshot": "/apps/meeting-transcript-summarizer.png",
    "tags": [
      "audio",
      "llm"
    ],
    "heading": "📝 Meeting Transcript Summarizer",
    "tagline": "Drop in a meeting recording — get the transcript and crisp notes back.",
    "buttonLabel": "Summarize my meeting",
    "inputs": [],
    "outputs": [
      {
        "label": "Summary",
        "kind": "text"
      },
      {
        "label": "Transcript",
        "kind": "text"
      }
    ],
    "widgetCount": 11
  },
  {
    "route": "/apps/movie-posters",
    "title": "Movie Posters — Free AI Mini App | NodeTool",
    "description": "Describe your film and generate a cinematic poster.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "movie-posters",
    "name": "Movie Posters",
    "summary": "Create cinematic movie posters using AI image generation",
    "templateRoute": "/templates/movie-posters",
    "screenshot": "/apps/movie-posters.png",
    "tags": [
      "start",
      "image",
      "example"
    ],
    "heading": "🎬 Movie Poster Studio",
    "tagline": "Describe your film and generate a cinematic poster.",
    "buttonLabel": "Generate Poster",
    "inputs": [
      {
        "label": "Movie Title",
        "kind": "text"
      },
      {
        "label": "Genre",
        "kind": "text"
      },
      {
        "label": "Primary Audience",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Poster",
        "kind": "image"
      }
    ],
    "widgetCount": 9
  },
  {
    "route": "/apps/movie-trailer-generator",
    "title": "Movie Trailer Generator — Free AI Mini App | NodeTool",
    "description": "Type one logline — get a cinematic teaser cut shot-by-shot.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "movie-trailer-generator",
    "name": "Movie Trailer Generator",
    "summary": "Type a single logline and get back a cinematic teaser. Prompt nodes template the inputs into a treatment and turn each shot into full cinematic key art; the shots are animated and cut together into the final trailer.",
    "templateRoute": "/templates/movie-trailer-generator",
    "screenshot": "/apps/movie-trailer-generator.png",
    "tags": [
      "video",
      "generation",
      "ai",
      "storytelling",
      "creative",
      "trailer",
      "example"
    ],
    "heading": "🍿 Movie Trailer Generator",
    "tagline": "Type one logline — get a cinematic teaser cut shot-by-shot.",
    "buttonLabel": "Cut my trailer",
    "inputs": [
      {
        "label": "Your movie in one sentence",
        "kind": "text"
      },
      {
        "label": "Visual style",
        "kind": "text"
      },
      {
        "label": "Number of shots",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Trailer",
        "kind": "video"
      }
    ],
    "widgetCount": 10
  },
  {
    "route": "/apps/music-video-visualizer",
    "title": "Music Video Visualizer — Free AI Mini App | NodeTool",
    "description": "Feed it a track — get mood-matched visuals cut to your music.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "music-video-visualizer",
    "name": "Music Video Visualizer",
    "summary": "Create reactive visuals from audio tracks with mood-matched imagery. Transcribes audio, analyzes mood/energy, and generates visual frames synced to the music.",
    "templateRoute": "/templates/music-video-visualizer",
    "screenshot": "/apps/music-video-visualizer.png",
    "tags": [
      "video",
      "audio",
      "music",
      "visualization",
      "example"
    ],
    "heading": "🎵 Music Video Visualizer",
    "tagline": "Feed it a track — get mood-matched visuals cut to your music.",
    "buttonLabel": "Visualize my track",
    "inputs": [
      {
        "label": "Genre",
        "kind": "text"
      },
      {
        "label": "Visual style",
        "kind": "text"
      },
      {
        "label": "Number of scenes",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Music Video",
        "kind": "video"
      }
    ],
    "widgetCount": 11
  },
  {
    "route": "/apps/photo-enhancement-suite",
    "title": "Photo Enhancement Suite — Free AI Mini App | NodeTool",
    "description": "Batch-enhance a whole folder of photos — color, brightness, upscaling.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "photo-enhancement-suite",
    "name": "Photo Enhancement Suite",
    "summary": "Batch enhance photos with AI-powered improvements including color correction and upscaling.",
    "templateRoute": "/templates/photo-enhancement-suite",
    "screenshot": "/apps/photo-enhancement-suite.png",
    "tags": [
      "image",
      "photo",
      "batch processing"
    ],
    "heading": "🖼️ Photo Enhancement Suite",
    "tagline": "Batch-enhance a whole folder of photos — color, brightness, upscaling.",
    "buttonLabel": "Enhance my photos",
    "inputs": [
      {
        "label": "Brightness",
        "kind": "number"
      },
      {
        "label": "Color boost",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Enhanced Photos",
        "kind": "image"
      },
      {
        "label": "Upscaled Photos",
        "kind": "image"
      }
    ],
    "widgetCount": 13
  },
  {
    "route": "/apps/podcast-repurposing-studio",
    "title": "Podcast Repurposing Studio — Free AI Mini App | NodeTool",
    "description": "One episode in — show notes, a newsletter, social posts, and quote cards out.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "podcast-repurposing-studio",
    "name": "Podcast Repurposing Studio",
    "summary": "Drop in one podcast episode and ship the whole content pack: episode titles and show notes, a newsletter edition, five social posts, and quote cards rendered as square images. Whisper transcribes once; four writer branches fan out from the transcript.",
    "templateRoute": "/templates/podcast-repurposing-studio",
    "screenshot": "/apps/podcast-repurposing-studio.png",
    "tags": [
      "podcast",
      "audio",
      "content",
      "marketing",
      "agents",
      "example"
    ],
    "heading": "🎙️ Podcast Repurposing Studio",
    "tagline": "One episode in — show notes, a newsletter, social posts, and quote cards out.",
    "buttonLabel": "Repurpose my episode",
    "inputs": [
      {
        "label": "About your show",
        "kind": "text"
      },
      {
        "label": "Quote cards to make",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Show Notes",
        "kind": "text"
      },
      {
        "label": "Newsletter",
        "kind": "text"
      },
      {
        "label": "Social Posts",
        "kind": "text"
      },
      {
        "label": "Quote Cards",
        "kind": "image"
      }
    ],
    "widgetCount": 17
  },
  {
    "route": "/apps/pokemon-maker",
    "title": "Pokemon Maker — Free AI Mini App | NodeTool",
    "description": "Mix any animals you like — meet the creature they become.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "pokemon-maker",
    "name": "Pokemon Maker",
    "summary": "",
    "templateRoute": "/templates/pokemon-maker",
    "screenshot": "/apps/pokemon-maker.png",
    "tags": [
      "example"
    ],
    "heading": "🐉 Pokemon Maker",
    "tagline": "Mix any animals you like — meet the creature they become.",
    "buttonLabel": "Create my creature",
    "inputs": [
      {
        "label": "Mix these animals",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Pokemon",
        "kind": "image"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/product-mockup-generator",
    "title": "Product Mockup Generator — Free AI Mini App | NodeTool",
    "description": "Turn one product shot into a set of polished lifestyle mockups.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "product-mockup-generator",
    "name": "Product Mockup Generator",
    "summary": "Generate product mockups for a given product.",
    "templateRoute": "/templates/product-mockup-generator",
    "screenshot": "/apps/product-mockup-generator.png",
    "tags": [
      "product-mockup",
      "mockup",
      "design",
      "example"
    ],
    "heading": "📦 Product Mockup Generator",
    "tagline": "Turn one product shot into a set of polished lifestyle mockups.",
    "buttonLabel": "Generate mockups",
    "inputs": [
      {
        "label": "Product name",
        "kind": "text"
      },
      {
        "label": "Describe the product",
        "kind": "text"
      },
      {
        "label": "Who's it for?",
        "kind": "text"
      },
      {
        "label": "How many scenes?",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Mockup",
        "kind": "image"
      },
      {
        "label": "Scene",
        "kind": "image"
      }
    ],
    "widgetCount": 15
  },
  {
    "route": "/apps/product-video-generator",
    "title": "Product Video Generator — Free AI Mini App | NodeTool",
    "description": "Brief in, launch video out — a realistic 16:9 spot for your product.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "product-video-generator",
    "name": "Product Video Generator",
    "summary": "Create a realistic 16:9 marketing video for a new product launch using the ImageToVideo node.",
    "templateRoute": "/templates/product-video-generator",
    "screenshot": "/apps/product-video-generator.png",
    "tags": [
      "business",
      "data",
      "video",
      "example"
    ],
    "heading": "📺 Product Video Generator",
    "tagline": "Brief in, launch video out — a realistic 16:9 spot for your product.",
    "buttonLabel": "Generate launch video",
    "inputs": [
      {
        "label": "Campaign brief",
        "kind": "text"
      },
      {
        "label": "Target audience",
        "kind": "text"
      },
      {
        "label": "Key features",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Product Video",
        "kind": "video"
      }
    ],
    "widgetCount": 11
  },
  {
    "route": "/apps/research-paper-summarizer",
    "title": "Research Paper Summarizer — Free AI Mini App | NodeTool",
    "description": "Paste a paper or abstract and extract the key findings.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "research-paper-summarizer",
    "name": "Research Paper Summarizer",
    "summary": "Extract and summarize key findings from research papers and technical documents.",
    "templateRoute": "/templates/research-paper-summarizer",
    "screenshot": "/apps/research-paper-summarizer.png",
    "tags": [
      "research"
    ],
    "heading": "📄 Research Paper Summarizer",
    "tagline": "Paste a paper or abstract and extract the key findings.",
    "buttonLabel": "Summarize",
    "inputs": [
      {
        "label": "Paper Text",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Summary",
        "kind": "text"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/seo-content-engine",
    "title": "SEO Content Engine — Free AI Mini App | NodeTool",
    "description": "One topic in — a keyword-targeted article batch out, with hero images.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "seo-content-engine",
    "name": "SEO Content Engine",
    "summary": "One topic in, a keyword-targeted article batch out. A strategist agent plans the topic cluster, a list generator turns it into briefs, and every brief becomes a full Markdown article with an editorial hero image.",
    "templateRoute": "/templates/seo-content-engine",
    "screenshot": "/apps/seo-content-engine.png",
    "tags": [
      "seo",
      "content",
      "marketing",
      "writing",
      "agents",
      "example"
    ],
    "heading": "📈 SEO Content Engine",
    "tagline": "One topic in — a keyword-targeted article batch out, with hero images.",
    "buttonLabel": "Plan & write my articles",
    "inputs": [
      {
        "label": "Your business",
        "kind": "text"
      },
      {
        "label": "Audience & seed topics",
        "kind": "text"
      },
      {
        "label": "Articles to write",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Content Plan",
        "kind": "text"
      },
      {
        "label": "Articles",
        "kind": "text"
      },
      {
        "label": "Hero Images",
        "kind": "image"
      }
    ],
    "widgetCount": 15
  },
  {
    "route": "/apps/social-media-calendar-filler",
    "title": "Social Media Calendar Filler — Free AI Mini App | NodeTool",
    "description": "Fill a month of social posts — images, captions, and hashtags included.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "social-media-calendar-filler",
    "name": "Social Media Calendar Filler",
    "summary": "Generate a month's worth of social media content with images, captions, and hashtags. Plans content based on monthly themes and brand guidelines.",
    "templateRoute": "/templates/social-media-calendar-filler",
    "screenshot": "/apps/social-media-calendar-filler.png",
    "tags": [
      "content",
      "social media",
      "marketing",
      "planning",
      "example"
    ],
    "heading": "📅 Social Media Calendar Filler",
    "tagline": "Fill a month of social posts — images, captions, and hashtags included.",
    "buttonLabel": "Fill my calendar",
    "inputs": [
      {
        "label": "Brand name",
        "kind": "text"
      },
      {
        "label": "This month's theme",
        "kind": "text"
      },
      {
        "label": "Audience",
        "kind": "text"
      },
      {
        "label": "Brand voice",
        "kind": "text"
      },
      {
        "label": "Posts per week",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Post Images",
        "kind": "image"
      },
      {
        "label": "Captions",
        "kind": "text"
      }
    ],
    "widgetCount": 15
  },
  {
    "route": "/apps/story-to-video-generator",
    "title": "Story to Video Generator — Free AI Mini App | NodeTool",
    "description": "Type a story idea — watch it become a cinematic AI-generated video.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "story-to-video-generator",
    "name": "Story to Video Generator",
    "summary": "Transform story ideas into cinematic AI-generated videos. An agent crafts detailed visual prompts optimized for video generation, then creates the video using Gemini Veo.",
    "templateRoute": "/templates/story-to-video-generator",
    "screenshot": "/apps/story-to-video-generator.png",
    "tags": [
      "video",
      "generation",
      "ai",
      "storytelling",
      "creative"
    ],
    "heading": "🚀 Story to Video Generator",
    "tagline": "Type a story idea — watch it become a cinematic AI-generated video.",
    "buttonLabel": "Generate my video",
    "inputs": [
      {
        "label": "Your story idea",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Video",
        "kind": "video"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/summarize-audio",
    "title": "Summarize Audio — Free AI Mini App | NodeTool",
    "description": "Any recording in — the gist out. Transcribed and summarized for you.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "summarize-audio",
    "name": "Summarize Audio",
    "summary": "Transcribe an audio file and summarize the text.",
    "templateRoute": "/templates/summarize-audio",
    "screenshot": "/apps/summarize-audio.png",
    "tags": [
      "audio",
      "start",
      "huggingface",
      "example"
    ],
    "heading": "🎧 Summarize Audio",
    "tagline": "Any recording in — the gist out. Transcribed and summarized for you.",
    "buttonLabel": "Summarize it",
    "inputs": [],
    "outputs": [
      {
        "label": "Summary",
        "kind": "text"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/summarize-rss",
    "title": "Summarize RSS — Free AI Mini App | NodeTool",
    "description": "Your feeds, read for you — one click for a clean daily brief.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "summarize-rss",
    "name": "Summarize RSS",
    "summary": "",
    "templateRoute": "/templates/summarize-rss",
    "screenshot": "/apps/summarize-rss.png",
    "tags": [],
    "heading": "📰 Summarize RSS",
    "tagline": "Your feeds, read for you — one click for a clean daily brief.",
    "buttonLabel": "Brief me",
    "inputs": [],
    "outputs": [
      {
        "label": "Summary",
        "kind": "text"
      }
    ],
    "widgetCount": 6
  },
  {
    "route": "/apps/transcribe-audio",
    "title": "Transcribe Audio — Free AI Mini App | NodeTool",
    "description": "Speech to text with word-level timestamps — paste-ready in seconds.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "transcribe-audio",
    "name": "Transcribe Audio",
    "summary": "Convert speech to text using Whisper model with word-level timestamps",
    "templateRoute": "/templates/transcribe-audio",
    "screenshot": "/apps/transcribe-audio.png",
    "tags": [
      "start",
      "audio",
      "huggingface"
    ],
    "heading": "🎤 Transcribe Audio",
    "tagline": "Speech to text with word-level timestamps — paste-ready in seconds.",
    "buttonLabel": "Transcribe",
    "inputs": [],
    "outputs": [
      {
        "label": "Transcript",
        "kind": "text"
      }
    ],
    "widgetCount": 7
  },
  {
    "route": "/apps/wikipedia-agent",
    "title": "Wikipedia Agent — Free AI Mini App | NodeTool",
    "description": "Point the agent at a seed article and a topic to research.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "wikipedia-agent",
    "name": "Wikipedia Agent",
    "summary": "Wikipedia style research and documentation agent.",
    "templateRoute": "/templates/wikipedia-agent",
    "screenshot": "/apps/wikipedia-agent.png",
    "tags": [
      "wikipedia",
      "research",
      "writing"
    ],
    "heading": "📚 Wikipedia Research Agent",
    "tagline": "Point the agent at a seed article and a topic to research.",
    "buttonLabel": "Research",
    "inputs": [
      {
        "label": "Seed URL",
        "kind": "text"
      },
      {
        "label": "Topic",
        "kind": "text"
      }
    ],
    "outputs": [
      {
        "label": "Findings",
        "kind": "text"
      }
    ],
    "widgetCount": 8
  },
  {
    "route": "/apps/youtube-research-agent",
    "title": "YouTube Research Agent — Free AI Mini App | NodeTool",
    "description": "An agent scours YouTube and distills what actually matters.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "youtube-research-agent",
    "name": "YouTube Research Agent",
    "summary": "Search YouTube using SerpAPI and analyze results with Claude Agent for deep research insights.",
    "templateRoute": "/templates/youtube-research-agent",
    "screenshot": "/apps/youtube-research-agent.png",
    "tags": [
      "youtube",
      "research",
      "serpapi",
      "claude",
      "agent",
      "search",
      "analysis"
    ],
    "heading": "▶️ YouTube Research Agent",
    "tagline": "An agent scours YouTube and distills what actually matters.",
    "buttonLabel": "Run the research",
    "inputs": [],
    "outputs": [
      {
        "label": "Research",
        "kind": "text"
      }
    ],
    "widgetCount": 6
  },
  {
    "route": "/apps/youtube-thumbnail-pipeline",
    "title": "YouTube Thumbnail Pipeline — Free AI Mini App | NodeTool",
    "description": "Generate a batch of bold, click-worthy thumbnail variations.",
    "priority": 0.4,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "youtube-thumbnail-pipeline",
    "name": "YouTube Thumbnail Pipeline",
    "summary": "Generate multiple eye-catching YouTube thumbnail variations from video scripts. Creates bold text overlays, dramatic styling, and batch processes variations for A/B testing.",
    "templateRoute": "/templates/youtube-thumbnail-pipeline",
    "screenshot": "/apps/youtube-thumbnail-pipeline.png",
    "tags": [
      "image",
      "youtube",
      "content creation",
      "thumbnails"
    ],
    "heading": "🖼️ YouTube Thumbnail Pipeline",
    "tagline": "Generate a batch of bold, click-worthy thumbnail variations.",
    "buttonLabel": "Generate thumbnails",
    "inputs": [
      {
        "label": "Video title",
        "kind": "text"
      },
      {
        "label": "What's the video about?",
        "kind": "text"
      },
      {
        "label": "Text on the thumbnail",
        "kind": "text"
      },
      {
        "label": "How many variations?",
        "kind": "number"
      }
    ],
    "outputs": [
      {
        "label": "Thumbnails",
        "kind": "image"
      }
    ],
    "widgetCount": 11
  }
];
