// Generated by web/scripts/build-project-shots.mjs. Do not edit.
export interface ProjectShot {
  id: string;
  width: number;
  height: number;
}

export const PROJECT_SHOTS: ProjectShot[] = [
  {
    "id": "project-new",
    "width": 1440,
    "height": 520
  },
  {
    "id": "project-overview",
    "width": 1440,
    "height": 900
  },
  {
    "id": "project-list",
    "width": 1440,
    "height": 900
  }
];
