// AUTO-GENERATED by marketing/scripts/generate-recipes.mjs — do not edit by hand.
// Regenerate: npm run gen:recipes
//
// Guided UI instructions: scripts/recipe-guides.mjs. Examples: scripts/recipes.mjs.
// Legacy workflow metadata supports bundle exports and template cross-links.
import type { RecipeEntry } from "./recipes";

export const recipeEntries: RecipeEntry[] = [
  {
    "sample": null,
    "productionRun": null,
    "guide": {
      "entry": "Directed Campaign Kit",
      "stages": [
        "Brief",
        "Direction",
        "Hero",
        "Formats",
        "Revision"
      ],
      "introduction": "Upload a product image. The app writes the brief and three directions. Approve the hero, then make formats and revisions.",
      "inputs": [
        "One clear product image",
        "Optional campaign steer or reference image",
        "Language and image models configured in NodeTool"
      ],
      "brief": "Create a campaign for the product in the supplied image. Infer a concise product name, audience, message, headline, and call to action. Propose three distinct visual directions. Keep the product recognizable and avoid unsupported performance claims.",
      "note": "The product image is the only required input. Add exact copy or audience details before uploading when they must not be inferred. Model selection stays available in the app.",
      "steps": [
        {
          "id": "upload",
          "phase": "Brief",
          "stage": "Product image",
          "title": "Start with the product",
          "description": "Open Directed Campaign Kit. Add an optional campaign steer first, then upload one clear product image. Uploading starts the language-model roundtrip automatically.",
          "action": "Upload the product image"
        },
        {
          "id": "review",
          "phase": "Brief",
          "stage": "AI draft",
          "title": "Review the filled brief",
          "description": "Check the inferred product name, audience, message, headline, and call to action. Edit any value that must be exact. The app keeps your non-empty values when you ask it to analyze again.",
          "action": "Approve or edit the brief"
        },
        {
          "id": "direction",
          "phase": "Direction",
          "stage": "A, B, or C",
          "title": "Choose one visual direction",
          "description": "Compare the three written directions before generating an image. Select the route that best expresses the message and gives the product a clear role in the composition.",
          "action": "Choose a direction"
        },
        {
          "id": "hero",
          "phase": "Hero",
          "stage": "Generate",
          "title": "Generate and approve the hero",
          "description": "Open Optional steering and models if you want a specific image model. Generate the 16:9 hero, compare it with the product image, and accept it only when identity, copy, and composition are sound.",
          "action": "Accept the hero"
        },
        {
          "id": "formats",
          "phase": "Formats",
          "stage": "4:5 and 9:16",
          "title": "Build the campaign formats",
          "description": "Create portrait and story versions from the accepted hero. The app keeps the copy editable and exports a campaign record that can reopen the project later.",
          "action": "Build the formats"
        },
        {
          "id": "revision",
          "phase": "Revision",
          "stage": "Compare",
          "title": "Direct one bounded revision",
          "description": "Describe one change, what must stay fixed, and what may respond. Choose the revision model if needed, generate the take, then compare it with the accepted original before choosing a final version.",
          "action": "Accept the original or revision"
        }
      ]
    },
    "route": "/recipes/directed-campaign-kit",
    "title": "Directed campaign kit | NodeTool guided recipe",
    "description": "Turn one product image into an approved campaign hero, two ready-to-edit formats, and one controlled revision.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "directed-campaign-kit",
    "name": "Directed campaign kit",
    "outcome": "Turn one product image into an approved campaign hero, two ready-to-edit formats, and one controlled revision.",
    "audience": "Small brand and social teams",
    "heroThumbnail": "/apps/directed-campaign-kit.png",
    "bundle": "/recipes/directed-campaign-kit.nodetool",
    "workflowCount": 3,
    "nodeCount": 40,
    "keys": [
      {
        "provider": "fal_ai",
        "env": "FAL_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "render-a-directed-campaign-hero",
        "name": "Render a Directed Campaign Hero",
        "route": "/templates/render-a-directed-campaign-hero",
        "role": "Approve the hero",
        "handoff": "In the app, upload the product image, review the AI-written brief and directions, choose one, then check product identity and composition before accepting.",
        "thumbnail": null,
        "nodeCount": 8,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/nano-banana/edit"
          }
        ],
        "alternative": null
      },
      {
        "template": "compose-directed-campaign-formats",
        "name": "Compose Directed Campaign Formats",
        "route": "/templates/compose-directed-campaign-formats",
        "role": "Build the formats",
        "handoff": "Keep the accepted hero and exact copy together in 4:5 and 9:16.",
        "thumbnail": null,
        "nodeCount": 20,
        "models": [],
        "alternative": null
      },
      {
        "template": "revise-an-accepted-campaign-hero",
        "name": "Revise an Accepted Campaign Hero",
        "route": "/templates/revise-an-accepted-campaign-hero",
        "role": "Direct one revision",
        "handoff": "Compare the revision with the original, then use the same composition workflow.",
        "thumbnail": null,
        "nodeCount": 12,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/nano-banana/edit"
          }
        ],
        "alternative": null
      }
    ]
  },
  {
    "sample": null,
    "productionRun": {
      "runId": "2026-09-14-ugc-cup",
      "status": "accepted",
      "statusLabel": "15-second native-audio UGC Reel",
      "proofTitle": "One take, finished for social.",
      "summary": "A small impulse purchase becomes a playful kitchen video, with animated captions and a seventh cup joining the collection.",
      "provider": "Seedance video supplied from Dreamina. Captions and animation added locally.",
      "hero": {
        "src": "/recipes/runs/2026-09-14-ugc-cup/close.jpg",
        "alt": "Creator holding an olive travel cup with the caption Look how nice.",
        "width": 720,
        "height": 1280
      },
      "card": {
        "src": "/recipes/runs/2026-09-14-ugc-cup/poster.jpg",
        "alt": "Creator holding an olive cup above animated captions and seven cup icons.",
        "width": 720,
        "height": 1280
      },
      "ogImage": "/recipes/runs/2026-09-14-ugc-cup/poster.jpg",
      "proof": {
        "src": "/recipes/runs/2026-09-14-ugc-cup/captions.jpg",
        "alt": "The caption six cups appears above six small cup outlines.",
        "caption": "Six cup outlines appear with the joke. A seventh olive cup joins them on the next line.",
        "width": 720,
        "height": 1280
      },
      "video": {
        "mp4": "/recipes/runs/2026-09-14-ugc-cup/final.mp4",
        "webm": null,
        "poster": "/recipes/runs/2026-09-14-ugc-cup/poster.jpg",
        "hasAudio": true,
        "caption": "A 15-second kitchen UGC video with animated captions, green underlines, and the original voice and room sound."
      },
      "supportedClaims": [
        "The supplied Dreamina recording shows the creator talking about buying another cup because it is green.",
        "The local finishing pass added timed caption groups, animated green underlines, and six cup outlines followed by a seventh olive cup.",
        "The final MP4 is 720×1280, runs for 15.07 seconds, and preserves the source audio without re-encoding."
      ],
      "essentialLimitation": "Generated product details, lip-sync, factual claims, and caption words still need review before publishing.",
      "limitations": [
        "The Olive Travel Cup is a fictional demonstration product.",
        "The model-generated performance may not reproduce every product detail exactly."
      ],
      "reviewLabel": "Reviewed example"
    },
    "guide": {
      "entry": "UGC Product Video",
      "stages": [
        "Angle",
        "References",
        "Generate",
        "Finish",
        "Review"
      ],
      "introduction": "Choose a simple observation, lock the references, generate one native-audio take, then finish the captions in NodeTool.",
      "inputs": [
        "One vertical creator image",
        "One clean product image",
        "Approved product facts",
        "A native-audio video provider"
      ],
      "brief": "Make a 15-second vertical kitchen video with phone framing, dry delivery, room tone, and no music. Image 1 sets the creator and room. Image 2 sets the cup. Dialogue: \"I bought this because it's green. That's it. I already have, like, six cups. But apparently I needed a green one. Look how nice.\" Add captions and the six-to-seven cup animation afterward.",
      "note": "Dreamina supplied the recording. The caption and cup animation were finished locally.",
      "steps": [
        {
          "id": "angle",
          "phase": "Angle",
          "stage": "Angle",
          "title": "Pick the joke",
          "description": "Compare three angles. Keep the one a creator could say without sounding scripted.",
          "action": "Choose an angle",
          "image": {
            "src": "/recipes/runs/2026-09-14-ugc-cup/steps/01-angle.png",
            "alt": "NodeTool UGC Product Video app showing three written angles for the olive travel cup.",
            "caption": "The app turns one product note into three angles.",
            "width": 1960,
            "height": 1050
          }
        },
        {
          "id": "creator",
          "phase": "Creator",
          "stage": "Creator",
          "title": "Set the creator",
          "description": "Use a vertical frame with a clear face, natural light, and the intended room.",
          "action": "Add the creator",
          "image": {
            "src": "/recipes/runs/2026-09-14-ugc-cup/steps/02-creator.png",
            "alt": "Vertical creator reference showing a woman speaking to camera in a bright kitchen.",
            "caption": "The creator reference fixes the face, framing, and room.",
            "width": 941,
            "height": 720
          }
        },
        {
          "id": "product",
          "phase": "References",
          "stage": "Product",
          "title": "Set the product",
          "description": "Use a clean image that shows the cup silhouette, finish, lid, and proportions.",
          "action": "Add the product",
          "image": {
            "src": "/recipes/runs/2026-09-14-ugc-cup/steps/03-product.png",
            "alt": "Olive travel cup product reference used as the second NodeTool entity.",
            "caption": "The product reference controls the cup, not the room.",
            "width": 1024,
            "height": 768
          }
        },
        {
          "id": "dialogue",
          "phase": "Generate",
          "stage": "Generate",
          "title": "Generate one take",
          "description": "Generate the voice and picture together. Leave a short pause before the punchline.",
          "action": "Generate the take",
          "image": {
            "src": "/recipes/runs/2026-09-14-ugc-cup/steps/04-generate.png",
            "alt": "NodeTool UGC Product Video app with creator and product inputs, Seedance model selection, and a generated vertical video.",
            "caption": "Both references feed one native-audio Seedance take.",
            "width": 1960,
            "height": 1150
          }
        },
        {
          "id": "finish",
          "phase": "Finish",
          "stage": "Captions",
          "title": "Time the captions",
          "description": "Match each caption to the voice. Add the seventh cup on the punchline.",
          "action": "Finish in the timeline",
          "image": {
            "src": "/recipes/runs/2026-09-14-ugc-cup/steps/05-captions.png",
            "alt": "NodeTool Studio timeline with separate caption, video, and voice tracks.",
            "caption": "Caption blocks stay editable on the NodeTool timeline.",
            "width": 1920,
            "height": 1080
          }
        },
        {
          "id": "inspect",
          "phase": "Review",
          "stage": "Review",
          "title": "Review the reel",
          "description": "Watch once with sound, then muted. Check lip-sync, captions, cup identity, and timing.",
          "action": "Approve or regenerate",
          "image": {
            "src": "/recipes/runs/2026-09-14-ugc-cup/steps/06-review.png",
            "alt": "NodeTool UGC Product Video app showing the finished vertical reel and review guidance.",
            "caption": "The finished reel remains beside its review checklist.",
            "width": 1960,
            "height": 1050
          }
        }
      ]
    },
    "route": "/recipes/ugc-product-video",
    "title": "UGC product video | NodeTool guided recipe",
    "description": "Turn creator and product references into a casual 15-second vertical video with native voice and playful caption animation.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "ugc-product-video",
    "name": "UGC product video",
    "outcome": "Turn creator and product references into a casual 15-second vertical video with native voice and playful caption animation.",
    "audience": "Founder-led brands, creators, and paid social teams",
    "heroThumbnail": "/apps/ugc-product-video.png",
    "bundle": "/recipes/ugc-product-video.nodetool",
    "workflowCount": 3,
    "nodeCount": 21,
    "keys": [
      {
        "provider": "openai",
        "env": "OPENAI_API_KEY"
      },
      {
        "provider": "atlascloud",
        "env": "ATLASCLOUD_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "ad-copy-in-three-registers",
        "name": "Ad Copy in Three Registers",
        "route": "/templates/ad-copy-in-three-registers",
        "role": "Choose the angle",
        "handoff": "Compare plain, playful, and premium routes before writing one spoken 15-second testimonial.",
        "thumbnail": "/templates/ad-copy-in-three-registers.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      },
      {
        "template": "generate-a-native-audio-ugc-testimonial",
        "name": "Generate a Native-Audio UGC Testimonial",
        "route": "/templates/generate-a-native-audio-ugc-testimonial",
        "role": "Generate the creator testimonial",
        "handoff": "Choose a compatible native-audio reference-to-video model. Give it image 1 for creator identity and image 2 for product identity, then generate voice, lip-sync, natural phone motion, and the brief 4.5–7.0 second product beat in one pass. The finished sample used Seedance 2.5 on AtlasCloud.",
        "thumbnail": null,
        "nodeCount": 8,
        "models": [
          {
            "provider": "atlascloud",
            "model": "bytedance/seedance-2.5/reference-to-video"
          }
        ],
        "alternative": null
      },
      {
        "template": "brand-a-ugc-product-video",
        "name": "Brand a UGC Product Video",
        "route": "/templates/brand-a-ugc-product-video",
        "role": "Finish the Reel",
        "handoff": "Choose a caption style and optional brand accent. The workflow transcribes the generated clip, adds animated captions and restrained graphic beats, then renders the exact brand and slogan over the close while preserving native audio.",
        "thumbnail": null,
        "nodeCount": 10,
        "models": [],
        "alternative": null
      }
    ]
  },
  {
    "sample": null,
    "productionRun": {
      "runId": "2026-09-14-photographic-commercial",
      "status": "accepted",
      "statusLabel": "13-second photographic commercial",
      "proofTitle": "A moment before the day.",
      "summary": "Fresh coffee pours, she takes a quiet moment, then heads out with her cup. Three shots follow one morning ritual.",
      "provider": "Opening and exit supplied from Dreamina. Middle shot generated with Seedance 2.0 via Fal. Edited in NodeTool and encoded locally.",
      "hero": {
        "src": "/recipes/runs/2026-09-14-photographic-commercial/card.jpg",
        "alt": "Woman holding an olive travel cup in a softly lit kitchen.",
        "width": 1200,
        "height": 630
      },
      "card": {
        "src": "/recipes/runs/2026-09-14-photographic-commercial/card.jpg",
        "alt": "Woman holding an olive travel cup in a softly lit kitchen.",
        "width": 1200,
        "height": 630
      },
      "ogImage": "/recipes/runs/2026-09-14-photographic-commercial/card.jpg",
      "proof": null,
      "video": {
        "mp4": "/recipes/runs/2026-09-14-photographic-commercial/commercial.mp4",
        "webm": null,
        "poster": "/recipes/runs/2026-09-14-photographic-commercial/poster.webp",
        "hasAudio": true,
        "caption": "A moment before the day. A 13-second commercial for the fictional Olive Travel Cup, with location sound."
      },
      "supportedClaims": [
        "The opening shows coffee filling the cup. The closing shot follows the woman out through her front door.",
        "The approved four-second middle shot is preserved between the two new shots in an editable NodeTool timeline.",
        "The final MP4 is 1920×1080 at 24 fps, runs for 13 seconds, and includes balanced location sound."
      ],
      "essentialLimitation": "Generated product geometry and human motion need review before use in a brand campaign.",
      "limitations": [
        "The Olive Travel Cup is a fictional, unbranded demonstration product.",
        "The master was encoded locally from the saved edit. Frame inspection and media checks do not establish parity with a filmed commercial."
      ],
      "reviewLabel": "Reviewed example"
    },
    "guide": {
      "entry": "Storyboard",
      "stages": [
        "Idea",
        "Story",
        "Entities",
        "Look"
      ],
      "introduction": "Build a photographic reference, direct a physical moment, then judge the moving film. This example follows one woman and one travel cup through a quiet morning.",
      "inputs": [
        "A clear product photograph",
        "A person and location reference for a lifestyle scene",
        "A reference-capable image model and a video model with native audio"
      ],
      "brief": "Make a photographic commercial for the Olive Travel Cup. An adult woman in an oatmeal shirt pauses in a naturally lit kitchen before starting her day. The final edit should be about 13 seconds: coffee pouring into the cup, a quiet reaction with the cup below her chin, then leaving home with it. Preserve the same cup, woman, clothes and home. Soft overcast window light, natural skin and fabric texture, restrained camera moves. Widescreen 16:9, with kitchen ambience, breath and cloth movement. No generated lettering or product-performance claims.",
      "note": "The opening and exit were rendered in Dreamina and supplied as video files. The middle shot was selected from a Seedance 2.0 scene generated through Fal. The edit and balanced sound are saved in NodeTool, and the final movie was encoded locally.",
      "steps": [
        {
          "id": "idea",
          "phase": "Guided setup",
          "stage": "Idea",
          "title": "Choose a moment the product belongs in",
          "description": "Create a project and choose Storyboard. Describe who uses the product, where the scene happens, and the small action that gives the ad a beginning and an ending. Include the intended format and sound.",
          "action": "Write the brief"
        },
        {
          "id": "story",
          "phase": "Guided setup",
          "stage": "Story",
          "title": "Plan the cuts and the sound together",
          "description": "Choose Commercial. Give each shot an action: fill the cup, pause, then leave. Write what changes physically and what the audience hears. Allow each action to finish before cutting. When revising separate clips, plan how their ambience will join in the edit.",
          "action": "Review the scene direction"
        },
        {
          "id": "entities",
          "phase": "Guided setup",
          "stage": "Entities",
          "title": "Keep the product, person and room consistent",
          "description": "Attach the original product entity. Prepare consistent character and kitchen references, then references for the pour and the doorway exit. Assign the relevant entities to the scene. Preserve the product's proportions, lid and colour in every image.",
          "action": "Attach the references"
        },
        {
          "id": "look",
          "phase": "Guided setup",
          "stage": "Look",
          "title": "Make the reference look photographed",
          "description": "Use 16:9 and a reference-capable image model. Specify the actual light source, lens, skin detail, fabric weave and product finish. Here the light comes from a broad kitchen window. Inspect the reference before spending on video.",
          "action": "Review the master frame",
          "image": {
            "src": "/recipes/runs/2026-09-14-photographic-commercial/reference.webp",
            "alt": "Generated photographic reference of a woman and the olive travel cup in a naturally lit kitchen.",
            "caption": "The master reference fixes the person, wardrobe, room and daylight.",
            "width": 1672,
            "height": 941
          }
        },
        {
          "id": "detail",
          "phase": "Storyboard",
          "stage": "References",
          "title": "Check the physical interaction at close range",
          "description": "Preserve the cup from the reference and describe the action with concrete verbs. As coffee enters, the level rises and covers more of the inner wall. The stream stops before overflow. Avoid re-describing the product in ways that invite a redesign.",
          "action": "Inspect the product and hand",
          "image": {
            "src": "/recipes/runs/2026-09-14-photographic-commercial/insert.webp",
            "alt": "Generated reference of coffee pouring from a glass carafe into the open olive cup.",
            "caption": "The opening reference establishes the cup, carafe, light and point where the stream meets the coffee.",
            "width": 1672,
            "height": 941
          }
        },
        {
          "id": "motion",
          "phase": "Finish",
          "stage": "Clips",
          "title": "Render a directed scene",
          "description": "Use a video model that supports image references and native audio. Direct the subject, movement, camera and sound. The opening and exit in this example were rendered in Dreamina. Preserve an approved shot by reusing its source footage instead of regenerating it.",
          "action": "Render the scene"
        },
        {
          "id": "review",
          "phase": "Finish",
          "stage": "Review",
          "title": "Judge movement as carefully as the still",
          "description": "Watch the clip with sound. Check whether the action is convincing: coffee must accumulate as it pours, and a departure must show movement out of the home. Here the doorway reference was corrected to show her back from inside the hallway. Inspect product geometry, hands and each cut.",
          "action": "Select a usable take"
        },
        {
          "id": "timeline",
          "phase": "Finish",
          "stage": "Timeline",
          "title": "Finish the actual returned footage",
          "description": "Import the sources and assemble four seconds of pouring, the approved four-second reaction, and five seconds of departure. Balance the pouring, breath, footsteps and ambience, smoothing the sound at each join. Verify the 13-second export at 1080p and 24 fps. Add approved copy as editable text if needed.",
          "action": "Review and export the commercial"
        }
      ]
    },
    "route": "/recipes/viral-video-ad-engine",
    "title": "Product commercials | NodeTool guided recipe",
    "description": "Give your product a story. Direct the shots, shape the sound, and finish your ad in the timeline.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "viral-video-ad-engine",
    "name": "Product commercials",
    "outcome": "Give your product a story. Direct the shots, shape the sound, and finish your ad in the timeline.",
    "audience": "Product and brand marketing teams",
    "heroThumbnail": "/templates/hook-and-thumbnail-factory.jpg",
    "bundle": "/recipes/viral-video-ad-engine.nodetool",
    "workflowCount": 4,
    "nodeCount": 24,
    "keys": [
      {
        "provider": "openai",
        "env": "OPENAI_API_KEY"
      },
      {
        "provider": "fal_ai",
        "env": "FAL_API_KEY"
      },
      {
        "provider": "kie",
        "env": "KIE_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "ad-copy-in-three-registers",
        "name": "Ad Copy in Three Registers",
        "route": "/templates/ad-copy-in-three-registers",
        "role": "Find your tone",
        "handoff": "Turn one offer into plain, playful, and premium ad copy.",
        "thumbnail": "/templates/ad-copy-in-three-registers.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      },
      {
        "template": "hook-and-thumbnail-factory",
        "name": "Hook & Thumbnail Factory",
        "route": "/templates/hook-and-thumbnail-factory",
        "role": "Build your test set",
        "handoff": "Generate hooks and a thumbnail for each from your video topic.",
        "thumbnail": "/templates/hook-and-thumbnail-factory.jpg",
        "nodeCount": 12,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          },
          {
            "provider": "fal_ai",
            "model": "fal-ai/flux/schnell"
          }
        ],
        "alternative": null
      },
      {
        "template": "ad-loop-from-a-product-photo",
        "name": "Ad Loop from a Product Photo",
        "route": "/templates/ad-loop-from-a-product-photo",
        "role": "Animate the product",
        "handoff": "Turn your product photo into a short, slowed-down video loop.",
        "thumbnail": "/templates/ad-loop-from-a-product-photo.jpg",
        "nodeCount": 6,
        "models": [
          {
            "provider": "kie",
            "model": "kling-2.6/image-to-video"
          }
        ],
        "alternative": null
      },
      {
        "template": "cut-a-landscape-clip-for-vertical",
        "name": "Cut a Landscape Clip for Vertical",
        "route": "/templates/cut-a-landscape-clip-for-vertical",
        "role": "Go vertical",
        "handoff": "Resize the loop to 1080×1920. This step runs locally with no provider charge.",
        "thumbnail": "/templates/cut-a-landscape-clip-for-vertical.jpg",
        "nodeCount": 3,
        "models": [],
        "alternative": null
      }
    ]
  },
  {
    "sample": null,
    "productionRun": {
      "runId": "2026-09-10-marketing-recipes-01",
      "status": "partial",
      "statusLabel": "English and Spanish example",
      "proofTitle": "Review the words. Revise one voice line.",
      "summary": "An English presenter, revoiced in Spanish. Edit the translation and revise individual voice lines.",
      "provider": "Media generated with FAL and Replicate through NodeTool",
      "hero": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/recipe-card.webp",
        "alt": "Synthetic presenter with English and Spanish versions of the same short script."
      },
      "card": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/translation-review.webp",
        "alt": "English source lines beside their Spanish translation and back-translation review.",
        "caption": "Synthetic presenter example with a recorded translation review."
      },
      "ogImage": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/recipe-card.jpg",
      "proof": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/translation-review.webp",
        "alt": "English source lines beside their Spanish translation and back-translation review.",
        "caption": "The reviewed Spanish wording is imported into the Script guide before choosing a voice."
      },
      "video": {
        "mp4": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/language-comparison.mp4",
        "webm": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/language-comparison.webm",
        "poster": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/language-comparison-poster.webp",
        "hasAudio": true,
        "caption": "Synthetic presenter with English, Spanish voiceover, and lip-sync versions."
      },
      "supportedClaims": [
        "The captured Script flow preserved three approved Spanish lines through setup.",
        "Inworld Realtime TTS 2 with the female Ashley voice produced the Spanish track used in the comparison video.",
        "Line 2 was redirected and revoiced before three clips were sent to an editable 16.3-second timeline."
      ],
      "essentialLimitation": "The native timeline preview failed, and human audition and lip-sync acceptance remain pending.",
      "limitations": [
        "Five required app captures, the walkthrough, persistent document IDs, and lossless capture originals are missing."
      ],
      "reviewLabel": "Partial example"
    },
    "guide": {
      "entry": "Script",
      "stages": [
        "Idea",
        "Format",
        "Voices"
      ],
      "introduction": "Prepare the translation with the agent, then review and voice it in the Script guide. Timing and lip sync come last.",
      "inputs": [
        "A short source video you can use",
        "A reviewed transcript and translation",
        "A voice provider for the target language"
      ],
      "brief": "Empieza con una breve descripción. Revisa el texto, elige una voz y escucha el resultado antes de exportarlo.\n\nSi necesitas cambiar una frase, edítala y vuelve a grabarla.\n\nTu guion sigue siendo editable, así que la siguiente versión parte del trabajo que ya tienes.",
      "note": "Screenshots show a Spanish Script session using Kokoro ef_dora. The comparison video used the Inworld Ashley voice. Choosing a language in Voices does not translate the script.",
      "steps": [
        {
          "id": "translation",
          "phase": "Prepare",
          "stage": "Agent",
          "title": "Prepare and review the translation",
          "description": "Ask the agent to transcribe the source, then compare the text with the audio. Translate it into your target language and review the meaning, names, and pronunciation before opening Script.",
          "action": "Review the translated words"
        },
        {
          "id": "idea",
          "phase": "Guided setup",
          "stage": "Idea",
          "title": "Bring your translated script",
          "description": "Choose Script when creating a project. Paste or import the reviewed target-language text and keep the imported words. This example starts with three Spanish lines.",
          "action": "Continue",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/steps/du-c3.png",
            "width": 3200,
            "height": 2000,
            "alt": "Script Idea with three imported Spanish lines.",
            "caption": "The reviewed Spanish words are imported before the voice is chosen."
          }
        },
        {
          "id": "format",
          "phase": "Guided setup",
          "stage": "Format",
          "title": "Choose voiceover narration",
          "description": "Select Voiceover narration and a length close to the source video. The example uses a custom 23-second target. Actual voice duration is measured after generation.",
          "action": "Continue to review",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/steps/du-c4.png",
            "width": 3200,
            "height": 2000,
            "alt": "Script Format with Voiceover narration selected and a 23-second target.",
            "caption": "Choose the format and target length while preserving the imported wording."
          }
        },
        {
          "id": "review",
          "phase": "Guided setup",
          "stage": "Format",
          "title": "Read every line",
          "description": "Check the speaker and wording of each line. Make language corrections here, before paying to voice the script.",
          "action": "Continue to voices",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/steps/du-c5.png",
            "width": 3200,
            "height": 2000,
            "alt": "Script review showing the three Spanish narrator lines.",
            "caption": "Each line remains editable at the review step."
          }
        },
        {
          "id": "voices",
          "phase": "Guided setup",
          "stage": "Voices",
          "title": "Listen before choosing a voice",
          "description": "Set the target language and pace. Choose an available voice model and narrator, then audition it on your own words. Check pronunciation before voicing all lines.",
          "action": "Voice your script",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/steps/du-c6.png",
            "width": 3200,
            "height": 2000,
            "alt": "Voices step with Spanish, Normal pace, Kokoro Spanish, and an ef_dora audition.",
            "caption": "The voice audition uses words from this script."
          }
        },
        {
          "id": "takes",
          "phase": "Script",
          "stage": "Voice takes",
          "title": "Review the generated takes",
          "description": "Listen to each line in the Script editor. Check the delivery and actual duration against the source video rather than relying on the target length.",
          "action": "Listen to each line",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/steps/du-c7.png",
            "width": 3200,
            "height": 2000,
            "alt": "Script editor reporting three voiced lines in an editable Spanish script.",
            "caption": "This session produced three voiced lines with a total duration of 16.3 seconds."
          }
        },
        {
          "id": "revise",
          "phase": "Script",
          "stage": "Revision",
          "title": "Revoice only the line that needs it",
          "description": "Change a line's direction or wording, generate another take, and choose the delivery you prefer. Keep the other accepted lines.",
          "action": "Generate another take",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/multilingual-video-dubber/steps/du-c8.png",
            "width": 3200,
            "height": 2000,
            "alt": "Script editor with revised direction and two takes for the second line.",
            "caption": "Line 2 was redirected and revoiced without replacing the whole script."
          }
        },
        {
          "id": "timeline",
          "phase": "Finish",
          "stage": "Timeline",
          "title": "Fit the voice to the picture",
          "description": "Send the voice takes to a timeline and add the original video. Mute the original speech, align each translated line, and adjust pauses. Play through the full result and export captions with the final timing.",
          "action": "Send to timeline"
        },
        {
          "id": "lip-sync",
          "phase": "Finish",
          "stage": "Lip sync",
          "title": "Choose the final delivery",
          "description": "Export a voiceover cut, or ask the agent for a separate supported lip-sync pass using the source picture and accepted target-language audio. Review mouth movement, timing, and pronunciation before using the result.",
          "action": "Review and export"
        }
      ]
    },
    "route": "/recipes/multilingual-video-dubber",
    "title": "Multilingual video | NodeTool guided recipe",
    "description": "Review a translation, choose a voice, and edit the delivery line by line. Finish with a new-language voiceover or a separate lip-sync pass.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "multilingual-video-dubber",
    "name": "Multilingual video",
    "outcome": "Review a translation, choose a voice, and edit the delivery line by line. Finish with a new-language voiceover or a separate lip-sync pass.",
    "audience": "Teams adapting videos for another language",
    "heroThumbnail": "/templates/ai-spokesperson.jpg",
    "bundle": "/recipes/multilingual-video-dubber.nodetool",
    "workflowCount": 5,
    "nodeCount": 27,
    "keys": [
      {
        "provider": "openai",
        "env": "OPENAI_API_KEY"
      },
      {
        "provider": "replicate",
        "env": "REPLICATE_API_TOKEN"
      },
      {
        "provider": "fal_ai",
        "env": "FAL_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "transcribe-a-clip",
        "name": "Transcribe a Clip",
        "route": "/templates/transcribe-a-clip",
        "role": "Transcribe your clip",
        "handoff": "Extract the spoken words as text. Only the audio goes to the transcription model.",
        "thumbnail": "/templates/transcribe-a-clip.jpg",
        "nodeCount": 4,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-4o-mini-transcribe"
          }
        ],
        "alternative": null
      },
      {
        "template": "localise-a-script-and-revoice-it",
        "name": "Localise a Script and Revoice It",
        "route": "/templates/localise-a-script-and-revoice-it",
        "role": "Translate and revoice",
        "handoff": "Choose a target language and turn the transcript into a new voice track.",
        "thumbnail": "/templates/localise-a-script-and-revoice-it.jpg",
        "nodeCount": 7,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          },
          {
            "provider": "openai",
            "model": "tts-1"
          }
        ],
        "alternative": null
      },
      {
        "template": "one-tagline-six-markets",
        "name": "One Tagline, Six Markets",
        "route": "/templates/one-tagline-six-markets",
        "role": "Check your key messages",
        "handoff": "Translate key lines into six languages, with back-translations for review.",
        "thumbnail": "/templates/one-tagline-six-markets.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      },
      {
        "template": "ai-spokesperson",
        "name": "AI Spokesperson",
        "route": "/templates/ai-spokesperson",
        "role": "Sync the presenter",
        "handoff": "Add the presenter clip and translated script. This step generates its own voice track and matches the mouth movements.",
        "thumbnail": "/templates/ai-spokesperson.jpg",
        "nodeCount": 8,
        "models": [
          {
            "provider": "replicate",
            "model": "inworld/realtime-tts-1.5-max"
          },
          {
            "provider": "fal_ai",
            "model": "fal-ai/sync-lipsync/v2/pro"
          }
        ],
        "alternative": null
      },
      {
        "template": "subtitle-text-from-a-recording",
        "name": "Subtitle Text from a Recording",
        "route": "/templates/subtitle-text-from-a-recording",
        "role": "Create subtitle text",
        "handoff": "Turn the localised audio into text split into subtitle-length lines.",
        "thumbnail": "/templates/subtitle-text-from-a-recording.jpg",
        "nodeCount": 5,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-4o-mini-transcribe"
          },
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      }
    ]
  },
  {
    "sample": null,
    "productionRun": {
      "runId": "2026-09-10-marketing-recipes-01",
      "status": "partial",
      "statusLabel": "Three views and a motion clip",
      "proofTitle": "Build a catalogue set from one product reference.",
      "summary": "Turn one product photo into a cutout, studio shots, and seasonal scenes.",
      "provider": "Media generated with FAL through NodeTool",
      "hero": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/recipe-card.webp",
        "alt": "Olive Travel Cup shown as a cutout, studio product image, winter scene, and motion frame."
      },
      "card": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/source-to-set.webp",
        "alt": "Accepted Olive Travel Cup reference beside its transparent cutout and catalogue treatments.",
        "caption": "One accepted reference carried through a coordinated catalogue set."
      },
      "ogImage": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/recipe-card.jpg",
      "proof": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/source-to-set.webp",
        "alt": "Accepted Olive Travel Cup reference beside its transparent cutout and catalogue treatments.",
        "caption": "The same accepted reference moves from source to cutout, studio treatment, seasonal treatment, and delivery assets."
      },
      "video": {
        "mp4": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/product-motion.mp4",
        "webm": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/product-motion.webm",
        "poster": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/product-motion-poster.webp",
        "hasAudio": false,
        "caption": "A selected product view becomes a silent six-second camera-arc clip."
      },
      "supportedClaims": [
        "One accepted product reference produced a three-shot catalogue.",
        "The run produced a transparent cutout, studio and seasonal stills, a short motion clip, a 4096px derivative, and factual listing copy.",
        "The recorded Commercial flow shows the real setup and finishing sequence."
      ],
      "essentialLimitation": "The scene treatments are generative and do not preserve source pixels unchanged.",
      "limitations": [
        "The motion clip is a short camera arc, not a full 360-degree reconstruction.",
        "Project naming and exact take linkage are unverified. The capture files and walkthrough need format and frame-rate recapture before acceptance."
      ],
      "reviewLabel": "Partial example"
    },
    "guide": {
      "entry": "Storyboard",
      "stages": [
        "Idea",
        "Story",
        "Entities",
        "Look"
      ],
      "introduction": "Plan three product views in the Commercial storyboard guide, keep one product reference throughout, then prepare delivery files with the agent.",
      "inputs": [
        "One clear product photo",
        "The views and formats you need",
        "Verified product facts for listing copy"
      ],
      "brief": "Create three square catalogue views of the Olive Travel Cup. A clean studio hero on a pale limestone plinth, a winter-light scene with a blurred branch in the distance, and a three-quarter hero for a short camera move. Keep the olive body and charcoal lid consistent. No text, labels, or extra products.",
      "note": "Screenshots show the real Commercial setup. Delivery images were generated separately from the same reference. Cutout, motion, upscale, and listing copy are agent-assisted.",
      "steps": [
        {
          "id": "source",
          "phase": "Prepare",
          "stage": "Product",
          "title": "Start with a clear product photo",
          "description": "Choose a complete, unobstructed view of the product. Keep this as the reference for the whole set. Ask the agent for a transparent cutout if your catalogue needs one.",
          "action": "Choose your reference"
        },
        {
          "id": "idea",
          "phase": "Guided setup",
          "stage": "Idea",
          "title": "Describe the catalogue set",
          "description": "Create a project and choose Storyboard. In Idea, describe the three views, the setting, and the details that must stay consistent.",
          "action": "Continue",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c1.png",
            "width": 3200,
            "height": 2000,
            "alt": "Storyboard Idea containing the Olive Travel Cup catalogue brief.",
            "caption": "A short brief describes the whole product set."
          }
        },
        {
          "id": "story",
          "phase": "Guided setup",
          "stage": "Story",
          "title": "Choose Commercial and three shots",
          "description": "Select Commercial and 3 shots. Generate a screenplay for a studio hero, a seasonal treatment, and a view that can become a motion clip.",
          "action": "Generate screenplay",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c2.png",
            "width": 3200,
            "height": 2000,
            "alt": "Story step with Commercial and three shots selected.",
            "caption": "The Commercial format plans three views before rendering any stills."
          }
        },
        {
          "id": "review",
          "phase": "Guided setup",
          "stage": "Story",
          "title": "Review the three views",
          "description": "Edit the shot descriptions so each has a clear purpose. Keep the product, scale, and lighting direction coherent across the set.",
          "action": "Set up entities",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c3.png",
            "width": 3200,
            "height": 2000,
            "alt": "Review of the three-shot catalogue screenplay.",
            "caption": "Review the studio, winter-light, and motion-view descriptions."
          }
        },
        {
          "id": "entities",
          "phase": "Guided setup",
          "stage": "Entities",
          "title": "Use the same product in every shot",
          "description": "Create or select the product entity from your reference photo. Assign it to all three shots so each generation uses the same reference.",
          "action": "Choose the look",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c4.png",
            "width": 3200,
            "height": 2000,
            "alt": "Entities step assigning the Olive Travel Cup to all three catalogue shots.",
            "caption": "One product entity is assigned to each view."
          }
        },
        {
          "id": "look",
          "phase": "Guided setup",
          "stage": "Look",
          "title": "Choose a square photographic look",
          "description": "Select 1:1 and a photographic style. Choose an image model that supports reference images, then generate the storyboard.",
          "action": "Generate your storyboard",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c5.png",
            "width": 3200,
            "height": 2000,
            "alt": "Look step with square format, photographic style, and a reference-capable model.",
            "caption": "Set the format and image model once for the board."
          }
        },
        {
          "id": "stills",
          "phase": "Storyboard",
          "stage": "Stills",
          "title": "Review the set together",
          "description": "Compare the three stills. Check the lid, silhouette, colour, and shadows. Revise only the view that needs another pass.",
          "action": "Review each shot",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c6.png",
            "width": 3200,
            "height": 2000,
            "alt": "Storyboard containing the three rendered Olive Travel Cup catalogue views.",
            "caption": "The board keeps the three views together for review."
          }
        },
        {
          "id": "motion",
          "phase": "Finish",
          "stage": "Motion",
          "title": "Animate one product view",
          "description": "Select the three-quarter hero and add a small camera arc. Review the product edges and shape throughout the clip. A short camera move is enough for this example.",
          "action": "Render the selected clip",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/ecommerce-sku-visual-factory/steps/sku-c7.png",
            "width": 3200,
            "height": 2000,
            "alt": "Shot inspector for the selected product motion view.",
            "caption": "Choose one shot for motion rather than animating the whole set."
          }
        },
        {
          "id": "delivery",
          "phase": "Finish",
          "stage": "Delivery",
          "title": "Prepare the listing assets",
          "description": "Ask the agent to upscale the selected studio image, prepare web copies, and write listing text using verified facts. Check the transparent cutout on light and dark backgrounds, then export the set.",
          "action": "Review and export the set"
        }
      ]
    },
    "route": "/recipes/ecommerce-sku-visual-factory",
    "title": "Product catalogue assets | NodeTool guided recipe",
    "description": "Turn one product reference into a coordinated set of studio images, seasonal scenes, and a short motion clip.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "ecommerce-sku-visual-factory",
    "name": "Product catalogue assets",
    "outcome": "Turn one product reference into a coordinated set of studio images, seasonal scenes, and a short motion clip.",
    "audience": "Ecommerce and catalogue teams",
    "heroThumbnail": "/templates/put-a-product-on-a-studio-backdrop.jpg",
    "bundle": "/recipes/ecommerce-sku-visual-factory.nodetool",
    "workflowCount": 6,
    "nodeCount": 29,
    "keys": [
      {
        "provider": "fal_ai",
        "env": "FAL_API_KEY"
      },
      {
        "provider": "openai",
        "env": "OPENAI_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "cut-a-product-out-of-its-background",
        "name": "Cut a Product Out of Its Background",
        "route": "/templates/cut-a-product-out-of-its-background",
        "role": "Remove the background",
        "handoff": "Create a product cutout with a transparent background.",
        "thumbnail": "/templates/cut-a-product-out-of-its-background.jpg",
        "nodeCount": 7,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/bria/background/remove"
          }
        ],
        "alternative": null
      },
      {
        "template": "put-a-product-on-a-studio-backdrop",
        "name": "Put a Product on a Studio Backdrop",
        "route": "/templates/put-a-product-on-a-studio-backdrop",
        "role": "Set the scene",
        "handoff": "Add a scene description to place your cutout on a new backdrop.",
        "thumbnail": "/templates/put-a-product-on-a-studio-backdrop.jpg",
        "nodeCount": 7,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/bria/background/remove"
          },
          {
            "provider": "fal_ai",
            "model": "fal-ai/nano-banana/edit"
          }
        ],
        "alternative": null
      },
      {
        "template": "relight-a-product-for-a-seasonal-campaign",
        "name": "Relight a Product for a Seasonal Campaign",
        "route": "/templates/relight-a-product-for-a-seasonal-campaign",
        "role": "Change the lighting",
        "handoff": "Relight the product shot for a seasonal campaign.",
        "thumbnail": "/templates/relight-a-product-for-a-seasonal-campaign.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/image-apps-v2/relighting"
          }
        ],
        "alternative": null
      },
      {
        "template": "spin-a-packshot-into-a-turntable-clip",
        "name": "Spin a Packshot into a Turntable Clip",
        "route": "/templates/spin-a-packshot-into-a-turntable-clip",
        "role": "Add a turntable clip",
        "handoff": "Animate the still with a short camera move around the product.",
        "thumbnail": "/templates/spin-a-packshot-into-a-turntable-clip.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/ltx-2.3/image-to-video/fast"
          }
        ],
        "alternative": null
      },
      {
        "template": "take-a-product-shot-to-print-resolution",
        "name": "Take a Product Shot to Print Resolution",
        "route": "/templates/take-a-product-shot-to-print-resolution",
        "role": "Prepare for print",
        "handoff": "Upscale the approved image to create your print master.",
        "thumbnail": "/templates/take-a-product-shot-to-print-resolution.jpg",
        "nodeCount": 6,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/clarity-upscaler"
          }
        ],
        "alternative": null
      },
      {
        "template": "write-a-listing-from-the-product-photo",
        "name": "Write a Listing from the Product Photo",
        "route": "/templates/write-a-listing-from-the-product-photo",
        "role": "Draft the listing",
        "handoff": "Generate marketplace copy from the product photo, including visible materials and finish.",
        "thumbnail": "/templates/write-a-listing-from-the-product-photo.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      }
    ]
  },
  {
    "sample": null,
    "productionRun": {
      "runId": "2026-09-10-marketing-recipes-01",
      "status": "partial",
      "statusLabel": "Storyboard example",
      "proofTitle": "A mystery told in six frames.",
      "summary": "The Next Tide: a six-shot storyboard with a shared cast, locations, and props.",
      "provider": "Reference images and voice takes generated with FAL through NodeTool",
      "hero": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/recipe-card.webp",
        "alt": "NodeTool Storyboard view showing the six-shot board for The Next Tide."
      },
      "card": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/storyboard-board.jpg",
        "alt": "The complete six-shot storyboard for The Next Tide.",
        "caption": "The reviewed board is the end of this recorded example."
      },
      "ogImage": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/recipe-card.jpg",
      "proof": {
        "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/entity-references.webp",
        "alt": "Reference images for Elin, the lighthouse, the keeper's room, and the message bottle.",
        "caption": "Reusable character, location, and prop references anchor the six-shot board. Select the Stills step above to see the editable storyboard."
      },
      "video": null,
      "supportedClaims": [
        "The Storyboard flow created a six-shot mystery board with reusable character, location, and prop references."
      ],
      "essentialLimitation": "No finished trailer exists.",
      "limitations": [
        "Motion clips, score, editable timeline, masters, previews, and finishing captures are missing.",
        "The selected keyframes and accepted voice takes remain server-side and are not presented here as exported deliverables."
      ],
      "reviewLabel": "Partial example"
    },
    "guide": {
      "entry": "Storyboard",
      "stages": [
        "Idea",
        "Story",
        "Entities",
        "Look"
      ],
      "introduction": "Start from a Mystery storyboard: review the story, cast character and location references, then choose the look.",
      "inputs": [
        "A short story premise",
        "Character, location, and prop references",
        "Your chosen image, video, and voice providers"
      ],
      "brief": "The Next Tide. A lighthouse keeper discovers a bottle carrying a message dated forty years in the future, written in her own hand. A restrained mystery on a blue-hour coast, with a warm amber keeper's room. Six shots for a short trailer. One central character, a lighthouse, a room, and a message bottle. No readable text inside generated pictures.",
      "note": "This example stops at the six-shot storyboard. Motion, score, and the trailer are not in this run. The final steps explain how to continue.",
      "steps": [
        {
          "id": "idea",
          "phase": "Guided setup",
          "stage": "Idea",
          "title": "Start with the story",
          "description": "Create a project and choose Storyboard. Describe the central character, discovery, and mood. The example starts with a lighthouse keeper finding a message from the future.",
          "action": "Continue",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/steps/tr-c1.png",
            "width": 3200,
            "height": 2000,
            "alt": "Storyboard Idea with The Next Tide mystery brief.",
            "caption": "The story begins as a short written premise."
          }
        },
        {
          "id": "story",
          "phase": "Guided setup",
          "stage": "Story",
          "title": "Choose Mystery and six shots",
          "description": "Select Mystery and 6 shots. Generate the screenplay to turn the premise into scenes, framing, and actions.",
          "action": "Generate screenplay",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/steps/tr-c2.png",
            "width": 3200,
            "height": 2000,
            "alt": "Story step with Mystery and six shots selected.",
            "caption": "Choose the genre and size of the storyboard."
          }
        },
        {
          "id": "review",
          "phase": "Guided setup",
          "stage": "Story",
          "title": "Shape the reveal",
          "description": "Read the six shots in order. Establish the coast, discover the bottle, show the room and note, then build to the keeper's recognition. Keep each shot to one clear action.",
          "action": "Set up entities",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/steps/tr-c3.png",
            "width": 3200,
            "height": 2000,
            "alt": "The reviewed six-shot screenplay for The Next Tide.",
            "caption": "Edit the scene and shot descriptions before generating pictures."
          }
        },
        {
          "id": "entities",
          "phase": "Guided setup",
          "stage": "Entities",
          "title": "Cast the character and places",
          "description": "Create or select references for Elin, the lighthouse, the keeper's room, and the bottle. Assign each only to the shots where it appears.",
          "action": "Choose the look",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/steps/tr-c4.png",
            "width": 3200,
            "height": 2000,
            "alt": "Entities step with reusable character, location, and prop references.",
            "caption": "References are assigned per shot to keep the cast and settings coherent."
          }
        },
        {
          "id": "look",
          "phase": "Guided setup",
          "stage": "Look",
          "title": "Set the visual direction",
          "description": "Choose 16:9 and a cinematic style. Use cool coastal light outside and warm lamplight inside. Select a model that can use the entity references.",
          "action": "Generate your storyboard",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/steps/tr-c5.png",
            "width": 3200,
            "height": 2000,
            "alt": "Look step for the widescreen cinematic mystery storyboard.",
            "caption": "The look is set before rendering the board."
          }
        },
        {
          "id": "stills",
          "phase": "Storyboard",
          "stage": "Stills",
          "title": "Review the six-frame story",
          "description": "Read the pictures in sequence. Check Elin's appearance, the lighthouse, the room, and the bottle. Revise individual shots or ask the Storyboard Assistant for a change.",
          "action": "Review the storyboard",
          "image": {
            "src": "/recipes/runs/2026-09-10-marketing-recipes-01/storyboard-to-trailer/steps/tr-c6.png",
            "width": 3200,
            "height": 2000,
            "alt": "The Next Tide six-shot storyboard beside the Storyboard Assistant.",
            "caption": "The example reaches this editable six-shot board."
          }
        },
        {
          "id": "script",
          "phase": "Continue",
          "stage": "Script",
          "title": "Develop the voiceover",
          "description": "Open the linked script, or use Extract script. Write the narrator's lines, choose a voice, and audition the delivery. Match accepted voice takes to the shots they accompany.",
          "action": "Open script"
        },
        {
          "id": "motion",
          "phase": "Continue",
          "stage": "Clips",
          "title": "Bring the chosen shots into motion",
          "description": "Give each shot one restrained movement and render its clip. Check identity and continuity before assembling. This example's motion clips are still pending.",
          "action": "Render clips"
        },
        {
          "id": "timeline",
          "phase": "Continue",
          "stage": "Timeline",
          "title": "Cut the trailer",
          "description": "Once the clips and voice are ready, assemble the timeline. Add a separately generated score, balance the mix, and use editable title text. Play through the full cut before exporting the finished trailer.",
          "action": "Assemble timeline"
        }
      ]
    },
    "route": "/recipes/storyboard-to-trailer",
    "title": "Storyboard to trailer | NodeTool guided recipe",
    "description": "Turn a story idea into a six-shot storyboard, then develop its voice, motion, and edit in the same workspace.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "storyboard-to-trailer",
    "name": "Storyboard to trailer",
    "outcome": "Turn a story idea into a six-shot storyboard, then develop its voice, motion, and edit in the same workspace.",
    "audience": "Filmmakers and small production teams",
    "heroThumbnail": "/templates/movie-trailer-generator.jpg",
    "bundle": "/recipes/storyboard-to-trailer.nodetool",
    "workflowCount": 4,
    "nodeCount": 26,
    "keys": [
      {
        "provider": "openai",
        "env": "OPENAI_API_KEY"
      },
      {
        "provider": "gemini",
        "env": "GEMINI_API_KEY"
      },
      {
        "provider": "kie",
        "env": "KIE_API_KEY"
      },
      {
        "provider": "fal_ai",
        "env": "FAL_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "trailer-beats-from-a-premise",
        "name": "Trailer Beats from a Premise",
        "route": "/templates/trailer-beats-from-a-premise",
        "role": "Plan the beats",
        "handoff": "Turn your premise into a hook, escalation, turning point, and title card.",
        "thumbnail": "/templates/trailer-beats-from-a-premise.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      },
      {
        "template": "shot-list-from-a-synopsis",
        "name": "Shot List from a Synopsis",
        "route": "/templates/shot-list-from-a-synopsis",
        "role": "Plan the shots",
        "handoff": "Turn your synopsis into numbered shots with framing and duration.",
        "thumbnail": "/templates/shot-list-from-a-synopsis.jpg",
        "nodeCount": 3,
        "models": [
          {
            "provider": "openai",
            "model": "gpt-5-mini"
          }
        ],
        "alternative": null
      },
      {
        "template": "movie-trailer-generator",
        "name": "Movie Trailer Generator",
        "route": "/templates/movie-trailer-generator",
        "role": "Render the trailer",
        "handoff": "Turn a logline into a storyboard, generate and animate the frames, then assemble the teaser.",
        "thumbnail": "/templates/movie-trailer-generator.jpg",
        "nodeCount": 10,
        "models": [
          {
            "provider": "gemini",
            "model": "gemini-3.1-pro-preview"
          },
          {
            "provider": "kie",
            "model": "gpt-image-2-text-to-image"
          },
          {
            "provider": "gemini",
            "model": "veo-3.1-generate-preview"
          }
        ],
        "alternative": {
          "template": "directed-film-to-timeline",
          "name": "Directed Film to Timeline",
          "route": "/templates/directed-film-to-timeline",
          "label": "Keep editing on the timeline",
          "why": "Get an editable sequence. Regenerate a shot or change the cut without rerunning the whole workflow."
        }
      },
      {
        "template": "score-a-silent-clip",
        "name": "Score a Silent Clip",
        "route": "/templates/score-a-silent-clip",
        "role": "Add the score",
        "handoff": "Generate music to fit the clip and your chosen mood, then mix it with the original audio.",
        "thumbnail": "/templates/score-a-silent-clip.jpg",
        "nodeCount": 10,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/stable-audio-25/text-to-audio"
          }
        ],
        "alternative": null
      }
    ]
  },
  {
    "sample": null,
    "productionRun": {
      "runId": "2026-09-11-impossible-product-worlds",
      "status": "partial",
      "statusLabel": "15-second drone reveal",
      "proofTitle": "Small object. Big escape.",
      "summary": "A giant cup in the desert. A hidden pool in its lid. One continuous drone shot reveals an impossible escape.",
      "provider": "GPT Image 2 stills and Kling v3 Turbo clips generated with AtlasCloud through NodeTool",
      "hero": {
        "src": "/recipes/runs/2026-09-11-impossible-product-worlds/pool-poster.webp",
        "alt": "A giant olive travel cup in the desert with a turquoise pool and loungers inside its lid.",
        "width": 540,
        "height": 960
      },
      "card": {
        "src": "/recipes/runs/2026-09-11-impossible-product-worlds/pool-poster.webp",
        "alt": "A giant olive travel cup in the desert with a turquoise pool and loungers inside its lid.",
        "width": 540,
        "height": 960
      },
      "ogImage": "/recipes/runs/2026-09-11-impossible-product-worlds/pool-poster.jpg",
      "proof": null,
      "video": {
        "mp4": "/recipes/runs/2026-09-11-impossible-product-worlds/drone-reveal-final.mp4",
        "webm": null,
        "poster": "/recipes/runs/2026-09-11-impossible-product-worlds/pool-poster.webp",
        "hasAudio": false,
        "caption": "A silent 15-second concept film at 1080×1920. The first eight seconds are one continuous generated drone shot."
      },
      "supportedClaims": [
        "The opening camera move keeps the cup in view while revealing a pool inside its fitted lid.",
        "The final MP4 contains 450 frames at 30 fps and was visually reviewed."
      ],
      "essentialLimitation": "Product proportions vary between generated shots.",
      "limitations": [
        "The fictional product changes proportions between generated shots. The result demonstrates a creative direction, not exact product reproduction.",
        "Final playback was assembled locally after the timeline renderer omitted the revised opening clip. No recorded UI walkthrough or soundtrack is included."
      ],
      "reviewLabel": "Partial example"
    },
    "guide": {
      "entry": "Storyboard",
      "stages": [
        "Idea",
        "Story",
        "Entities",
        "Look"
      ],
      "introduction": "Three shots: one continuous drone flight over a giant cup that reveals a pool in its lid, then ordinary tabletop scale, then a packshot.",
      "inputs": [
        "One clear product photo with the full silhouette visible",
        "A product name and approved closing line",
        "Your chosen image and video providers, plus a music provider if needed"
      ],
      "brief": "Small object. Big escape. Create a three-shot surreal commercial for the Olive Travel Cup, a fictional unbranded olive-green travel cup with a charcoal lid. Use the supplied product reference throughout.\n\n1. An eight-second continuous drone flight. Begin low in golden dunes facing a monumental cup. Fly forward, rise above its rim, and tilt down to reveal a luxury turquoise pool built into its fitted lid, with pale stone coping, two cream loungers, and a beige parasol. Keep the same cup visible throughout. The pool already exists and is revealed by the camera angle. No cut, lid detachment, or object transformation.\n2. Four seconds at ordinary scale: the cup on a sunlit tabletop with its lid beside it. A small lateral camera slide establishes familiar scale.\n3. Three seconds on a cobalt-blue studio background: cup upright, lid fitted, clear space above for the closing line.\n\nVertical 9:16. Target 15 seconds: 8, 4, and 3. Warm directional light and sharp shadows. No people, generated lettering, extra handles, or product-performance claims. Add Small object. Big escape. as editable text over the final hero.",
      "note": "The example is a silent 15-second concept film, rendered through AtlasCloud and assembled locally. Product proportions vary between shots.",
      "steps": [
        {
          "id": "reference",
          "phase": "Prepare",
          "stage": "Product",
          "title": "Choose the details that must survive",
          "description": "Start with an unobstructed product photo. Note its silhouette, colour, lid, and materials. If you use another product, adapt the hidden pool to a visible feature such as a cap or recess.",
          "action": "Choose your product reference"
        },
        {
          "id": "idea",
          "phase": "Guided setup",
          "stage": "Idea",
          "title": "Give the product an impossible setting",
          "description": "Create a project and choose Storyboard. Paste the example brief into Idea, then replace the product details with your own. Keep the drone approach and pool reveal in one continuous opening shot, followed by a tabletop shot and final hero.",
          "action": "Continue"
        },
        {
          "id": "story",
          "phase": "Guided setup",
          "stage": "Story",
          "title": "Plan a three-shot Commercial",
          "description": "Select Commercial and 3 shots. Generate the screenplay. Use the 15-second target to keep the concept focused, then set the exact shot lengths when you edit the clips.",
          "action": "Generate screenplay"
        },
        {
          "id": "review",
          "phase": "Guided setup",
          "stage": "Review",
          "title": "Make the scale change readable",
          "description": "Keep the cup visible while the camera rises above its rim. The pool should already exist inside the fitted lid and become visible as the camera tilts down. Use the next cut to return to ordinary tabletop scale.",
          "action": "Set up entities"
        },
        {
          "id": "entities",
          "phase": "Guided setup",
          "stage": "Entities",
          "title": "Anchor every world to one product",
          "description": "Create or select a product entity using your photo and assign it to all three shots. Describe the fitted lid, its rim, and drinking opening so the pool reveal retains the product's identity.",
          "action": "Choose the look"
        },
        {
          "id": "look",
          "phase": "Guided setup",
          "stage": "Look",
          "title": "Make the impossible feel photographed",
          "description": "Choose 9:16 and a photographic style with warm directional light, sharp shadows, golden sand, and deep blue backgrounds. Select an image model that supports entity references, then generate the board.",
          "action": "Generate your storyboard"
        },
        {
          "id": "stills",
          "phase": "Storyboard",
          "stage": "Stills",
          "title": "Review the product before the spectacle",
          "description": "Compare every still with the source photo. Check the silhouette, lid geometry, and colour. Begin the drone shot below the lid rim so the pool is hidden. Keep the lid attached throughout the reveal. Regenerate a still if it changes the product's silhouette.",
          "action": "Accept one still per shot"
        },
        {
          "id": "motion",
          "phase": "Finish",
          "stage": "Motion",
          "title": "Move the camera through each scene",
          "description": "Render the opening as one eight-second clip: approach the cup, ascend above its rim, then tilt down to reveal the luxury pool, narrow deck, loungers, and parasol. Keep the cup stationary and the camera path continuous. Render the tabletop slide and near-static hero separately.",
          "action": "Render and review each clip",
          "image": {
            "src": "/recipes/runs/2026-09-11-impossible-product-worlds/pool-poster.webp",
            "alt": "The drone camera reveals a luxury pool inside the giant cup's fitted lid.",
            "caption": "A frame from the continuous drone reveal in the rendered example.",
            "width": 540,
            "height": 960
          }
        },
        {
          "id": "edit",
          "phase": "Finish",
          "stage": "Timeline",
          "title": "Cut from impossible to familiar",
          "description": "Assemble the three accepted clips and trim them to 8, 4, and 3 seconds. Use a direct cut for the return to tabletop scale. Add your approved closing line as editable text over the final hero and check its position in the vertical frame.",
          "action": "Assemble the 15-second edit"
        },
        {
          "id": "delivery",
          "phase": "Finish",
          "stage": "Delivery",
          "title": "Finish with sound and a clear product read",
          "description": "If the cut needs music, ask the agent for a sparse instrumental score covering the full edit, with a change at the tabletop reveal. Balance it in the timeline. Watch once with sound and once muted, check the final product and closing line, then export the vertical film.",
          "action": "Review and export"
        }
      ]
    },
    "route": "/recipes/impossible-product-worlds",
    "title": "Impossible product worlds | NodeTool guided recipe",
    "description": "Fly above a giant product to reveal a luxury pool in its lid, then return to a clean hero shot in a short surreal commercial.",
    "priority": 0.8,
    "changeFrequency": "monthly",
    "indexable": true,
    "slug": "impossible-product-worlds",
    "name": "Impossible product worlds",
    "outcome": "Fly above a giant product to reveal a luxury pool in its lid, then return to a clean hero shot in a short surreal commercial.",
    "audience": "Brand teams and creative studios",
    "heroThumbnail": "/templates/put-a-product-on-a-studio-backdrop.jpg",
    "bundle": "/recipes/impossible-product-worlds.nodetool",
    "workflowCount": 1,
    "nodeCount": 7,
    "keys": [
      {
        "provider": "fal_ai",
        "env": "FAL_API_KEY"
      }
    ],
    "steps": [
      {
        "template": "put-a-product-on-a-studio-backdrop",
        "name": "Put a Product on a Studio Backdrop",
        "route": "/templates/put-a-product-on-a-studio-backdrop",
        "role": "Build each world",
        "handoff": "Replace the image-edit prompt with one scene from your approved board. Repeat from the same product photo for each scene, and match the aspect ratio to your delivery.",
        "thumbnail": "/templates/put-a-product-on-a-studio-backdrop.jpg",
        "nodeCount": 7,
        "models": [
          {
            "provider": "fal_ai",
            "model": "fal-ai/bria/background/remove"
          },
          {
            "provider": "fal_ai",
            "model": "fal-ai/nano-banana/edit"
          }
        ],
        "alternative": null
      }
    ]
  }
];
