"""
Supabase Select DSL Example

Run a typed SELECT query against a Supabase table and return a DataFrame.

Requirements:
- Set NODE_SUPABASE_URL and NODE_SUPABASE_KEY for user-provided nodes
- Ensure the table exists (e.g., "todos" with columns id, title, done)
"""

from nodetool.dsl.graph import create_graph, run_graph
from nodetool.dsl.nodetool.output import Output

# DSL wrappers for Supabase nodes (generated by codegen)
from nodetool.dsl.lib.supabase import Select

# Enum for filter operators
from nodetool.nodes.lib.supabase import FilterOp

from nodetool.metadata.types import RecordType, ColumnDef


# Define which columns to return (leave empty to select all)
columns = RecordType(
    type="record_type",
    columns=[
        ColumnDef(name="id", data_type="int"),
        ColumnDef(name="title", data_type="string"),
        ColumnDef(name="done", data_type="int"),
    ]
)

select = Select(
    table_name="todos",
    columns=columns,
    filters=[
        ("done", FilterOp.EQ, False),
    ],
    order_by="id",
    descending=False,
    limit=50,
    to_dataframe=True,
)

out = Output(name="todos_df", value=select.output)
graph = create_graph(out)


if __name__ == "__main__":
    result = run_graph(graph)
    print("Rows:")
    print(result["todos_df"])  # DataframeRef
