/**
 * SSRF guard for outbound fetches of caller-supplied URLs, and the one address
 * table every screening surface in the repo reads.
 *
 * Image/video providers (FAL, Replicate, …) return result URLs that the server
 * then `fetch`es to download the generated bytes. Those URLs originate from the
 * provider's response, so without validation a compromised or misbehaving
 * provider — or a response coerced via a crafted prompt — could point the
 * server at internal services (`http://169.254.169.254/...`,
 * `http://localhost:6379/...`, RFC1918 hosts, …). The same is true of a media
 * ref a workflow carries and of a URL a model hands a tool.
 *
 * Two things live here, and the split matters. {@link isBlockedIpLiteral} is
 * the **address table** — which literals are internal — shared with the sandbox
 * fetch bridge (`packages/agents/src/network-guard.ts`), which allows plain
 * http and an opt-in private mode that this module never does.
 * {@link isSafePublicHttpsUrl} is NodeTool's **default policy** on top of it:
 * https only, to an apparently-public host. A predicate is not a protected
 * fetch, though — only {@link safeFetch} validates every redirect hop, so an
 * operation that actually goes out calls that.
 *
 * The check is conservative: unparseable URLs, non-https schemes, and literal
 * IP addresses in loopback / link-local / RFC1918 / CGNAT / benchmarking ranges
 * (including IPv4-mapped IPv6 literals and IPv4 embedded in 6to4 / NAT64
 * transition addresses) are refused. Alternate IPv4 spellings — decimal, hex,
 * octal, short form — are normalized by the WHATWG URL parser before the table
 * sees them.
 *
 * **DNS rebinding is out of scope here, deliberately.** A public name that
 * resolves to a private address passes: this process does not control which
 * address `fetch` connects to, and pinning one would break TLS and virtual
 * hosting. Two answers exist and the inventory records which each surface uses
 * — `assertResolvedHostAllowed` (a resolve-and-check pass, for a URL handed to
 * a separate process that opens its own sockets), and the deployment's egress
 * control as the security boundary for everything in-process. See
 * `docs/url-egress-inventory.md`.
 */

/**
 * Expand an IPv6 literal (already stripped of brackets, lower-cased) into its 8
 * 16-bit hextets, handling `::` compression and a trailing dotted-quad. Returns
 * `null` if `host` is not a well-formed IPv6 literal.
 */
function expandIpv6(host: string): number[] | null {
  if (!host.includes(":")) return null;
  // Rewrite a trailing dotted-quad (`...:a.b.c.d`) into two hex hextets so the
  // rest of the parse only deals with `:`-separated groups.
  const body = host.replace(/((?:\d{1,3}\.){3}\d{1,3})$/, (m) => {
    const oct = m.split(".").map((n) => parseInt(n, 10));
    if (oct.some((n) => n > 255)) return "\0"; // sentinel → fails group parse
    const hex = (n: number) => n.toString(16).padStart(2, "0");
    return `${hex(oct[0])}${hex(oct[1])}:${hex(oct[2])}${hex(oct[3])}`;
  });
  const halves = body.split("::");
  if (halves.length > 2) return null;
  const parseGroup = (s: string): number[] | null => {
    if (s === "") return [];
    const out: number[] = [];
    for (const p of s.split(":")) {
      if (!/^[0-9a-f]{1,4}$/.test(p)) return null;
      out.push(parseInt(p, 16));
    }
    return out;
  };
  const head = parseGroup(halves[0]);
  if (head === null) return null;
  let hextets: number[];
  if (halves.length === 2) {
    const rest = parseGroup(halves[1]);
    if (rest === null) return null;
    const middle = 8 - head.length - rest.length;
    if (middle < 0) return null;
    hextets = [...head, ...new Array(middle).fill(0), ...rest];
  } else {
    hextets = head;
  }
  if (hextets.length !== 8) return null;
  return hextets;
}

/**
 * True for IPv4 octet pairs in loopback / RFC1918 / link-local / CGNAT /
 * benchmarking ranges.
 */
function isPrivateIpv4(a: number, b: number): boolean {
  // 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8
  if (a === 0 || a === 10 || a === 127) return true;
  // 169.254.0.0/16 (link-local, incl. the 169.254.169.254 metadata service)
  if (a === 169 && b === 254) return true;
  // 172.16.0.0/12
  if (a === 172 && b >= 16 && b <= 31) return true;
  // 192.168.0.0/16
  if (a === 192 && b === 168) return true;
  // 100.64.0.0/10 (CGNAT)
  if (a === 100 && b >= 64 && b <= 127) return true;
  // 198.18.0.0/15 (benchmarking)
  if (a === 198 && (b === 18 || b === 19)) return true;
  return false;
}

/**
 * True when `host` is a literal IPv4/IPv6 address in a loopback, link-local,
 * private, CGNAT or benchmarking range — including the IPv6 spellings that
 * carry an IPv4 inside them (IPv4-mapped, IPv4-compatible, 6to4, NAT64).
 *
 * This is the address table, not a policy: it says nothing about schemes,
 * hostnames or redirects, and a caller that allows private networks on purpose
 * (the sandbox fetch bridge under `allowPrivateNetwork`) skips it rather than
 * reimplementing it. A hostname that is not a literal is not this function's
 * question — it answers `false`, and what the name *resolves* to is decided by
 * the surface's DNS-rebinding policy (see the module comment).
 */
export function isBlockedIpLiteral(host: string): boolean {
  // Strip IPv6 brackets and any zone id (`fe80::1%eth0`), lower-case for the
  // hex comparisons.
  const h = host
    .replace(/^\[|\]$/g, "")
    .split("%")[0]
    .toLowerCase();
  // IPv4 in dotted form, standalone or as an IPv6 tail (`::ffff:127.0.0.1`).
  const dotted = h.match(/(?:^|:)((?:\d{1,3}\.){3}\d{1,3})$/);
  if (dotted) {
    const [a, b] = dotted[1].split(".").map((n) => parseInt(n, 10));
    return isPrivateIpv4(a, b);
  }
  if (!h.includes(":")) return false;
  if (h === "::" || h === "::1") return true; // unspecified / loopback
  if (h.startsWith("fc") || h.startsWith("fd")) return true; // ULA fc00::/7
  // link-local fe80::/10 — the first hextet spans fe80–febf, so the first three
  // hex digits are fe8/fe9/fea/feb; "fe80" alone is too narrow.
  if (/^fe[89ab]/.test(h)) return true;
  // IPv4 embedded in a hex-serialized IPv6 literal. The WHATWG parser rewrites
  // `::ffff:127.0.0.1` to `::ffff:7f00:1`, which the dotted regex above no
  // longer matches, and the transition prefixes hide an IPv4 in the same way:
  // IPv4-mapped/-compatible and NAT64 (64:ff9b::/96) in the low 32 bits, 6to4
  // (2002:WWXX:YYZZ::/16) in the second and third hextets.
  const hextets = expandIpv6(h);
  if (!hextets) return false;
  const isZero = (from: number, to: number): boolean =>
    hextets.slice(from, to).every((n) => n === 0);
  let embedded: number | null = null;
  if (hextets[0] === 0x2002) {
    embedded = hextets[1];
  } else if (isZero(0, 5) && hextets[5] === 0xffff) {
    embedded = hextets[6]; // ::ffff:a.b.c.d
  } else if (isZero(0, 6)) {
    embedded = hextets[6]; // ::a.b.c.d (IPv4-compatible, deprecated)
  } else if (hextets[0] === 0x64 && hextets[1] === 0xff9b && isZero(2, 6)) {
    embedded = hextets[6]; // 64:ff9b::/96
  }
  if (embedded === null) return false;
  return isPrivateIpv4((embedded >> 8) & 0xff, embedded & 0xff);
}

/**
 * Return `true` when `url` is an https URL whose host is not a loopback,
 * link-local, or RFC1918 private address. NodeTool's default egress policy.
 */
export function isSafePublicHttpsUrl(url: string): boolean {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return false;
  }
  if (parsed.protocol !== "https:") {
    return false;
  }
  // Normalise: strip IPv6 brackets (WHATWG URL may include them depending on
  // the runtime) and any trailing dot (`localhost.` resolves the same as
  // `localhost` but would dodge the exact/suffix checks below).
  const host = parsed.hostname
    .toLowerCase()
    .replace(/^\[|\]$/g, "")
    .replace(/\.+$/, "");
  if (!host) return false;
  if (
    host === "localhost" ||
    host === "ip6-localhost" ||
    host === "ip6-loopback" ||
    host.endsWith(".localhost") ||
    host.endsWith(".local") ||
    host.endsWith(".internal")
  ) {
    return false;
  }
  return !isBlockedIpLiteral(host);
}

/**
 * Throw if `url` is not a safe public https URL (see {@link isSafePublicHttpsUrl}).
 * Use before `fetch`ing any provider-supplied download URL.
 */
export function assertSafePublicHttpsUrl(url: string): void {
  if (!isSafePublicHttpsUrl(url)) {
    throw new Error(
      `Refusing to fetch unsafe URL (must be https to a public host): ${url}`
    );
  }
}

/** Request headers that must not cross an origin boundary on a redirect. */
const CROSS_ORIGIN_SENSITIVE_HEADERS = [
  "authorization",
  "cookie",
  "proxy-authorization",
  "x-goog-api-key"
];

/**
 * Return a copy of `init` with credentials and body stripped, for replay
 * against a different origin. Mirrors browser behaviour: a cross-origin
 * redirect must not forward `Authorization`/`Cookie` headers or the request
 * body, both of which may carry secrets meant only for the original host.
 */
function stripCrossOriginCredentials(init: RequestInit): RequestInit {
  const headers = new Headers(init.headers ?? undefined);
  for (const name of CROSS_ORIGIN_SENSITIVE_HEADERS) headers.delete(name);
  const next: RequestInit = { ...init, headers };
  delete next.body;
  return next;
}

/**
 * `fetch` a provider-supplied URL with SSRF protection. The initial URL and
 * every redirect hop are validated with {@link assertSafePublicHttpsUrl}, so a
 * public host cannot redirect into an internal/loopback target or downgrade to
 * http. Redirects are followed manually up to `maxRedirects`. When a redirect
 * crosses to a different origin, auth headers and the request body are stripped
 * so they are never leaked to the redirect target.
 */
export async function safeFetch(
  url: string,
  init?: RequestInit,
  maxRedirects = 5,
  // The underlying fetch implementation. Defaults to the global fetch; callers
  // that inject a fetch (e.g. providers with a testable `fetchFn`) can pass it
  // here so the SSRF URL validation still runs on every hop while the actual
  // request goes through their implementation.
  fetchImpl: typeof fetch = fetch
): Promise<Response> {
  let current = url;
  let currentInit: RequestInit = { ...init };
  let currentOrigin = new URL(url).origin;
  for (let hop = 0; hop <= maxRedirects; hop++) {
    assertSafePublicHttpsUrl(current);
    const res = await fetchImpl(current, { ...currentInit, redirect: "manual" });
    // A real Response always has headers; tolerate minimal fetch mocks/polyfills
    // that omit them (treated as no redirect).
    const location = res.headers?.get?.("location") ?? null;
    if (res.status >= 300 && res.status < 400 && location) {
      const next = new URL(location, current);
      if (next.origin !== currentOrigin) {
        currentInit = stripCrossOriginCredentials(currentInit);
      }
      current = next.toString();
      currentOrigin = next.origin;
      continue;
    }
    return res;
  }
  throw new Error(`Too many redirects while fetching: ${url}`);
}
