import type { ModuleConfig } from "../types.js";

export const config: ModuleConfig = {
  configs: {
    "half-moon-ai/ai-detector/detect-image": {
      className: "AIDetectorImage",
      docstring:
        "AI Detector analyzes images to determine if they were generated by AI or are real photos.",
      tags: ["vision", "ai-detection", "analysis", "classification"],
      useCases: [
        "Detect AI-generated images",
        "Verify image authenticity",
        "Filter synthetic content",
        "Content moderation for AI images",
        "Analyze image provenance"
      ],
      basicFields: ["image"]
    },
    "fal-ai/arbiter/image/text": {
      className: "ArbiterImageText",
      docstring:
        "Arbiter measures semantic alignment between images and text descriptions.",
      tags: ["vision", "alignment", "similarity", "text-image", "analysis"],
      useCases: [
        "Measure image-text alignment",
        "Verify prompt accuracy",
        "Quality control for generated images",
        "Rank images by text relevance",
        "Evaluate caption accuracy"
      ],
      basicFields: ["image", "text"]
    },
    "fal-ai/arbiter/image/image": {
      className: "ArbiterImageImage",
      docstring:
        "Arbiter measures similarity and alignment between reference images.",
      tags: [
        "vision",
        "similarity",
        "comparison",
        "image-matching",
        "analysis"
      ],
      useCases: [
        "Compare image similarity",
        "Measure visual alignment",
        "Find duplicate images",
        "Rank image variations",
        "Evaluate image consistency"
      ],
      basicFields: ["image1", "image2"]
    },
    "fal-ai/arbiter/image": {
      className: "ArbiterImage",
      docstring:
        "Arbiter provides comprehensive image analysis and quality metrics.",
      tags: ["vision", "analysis", "quality", "metrics", "image-evaluation"],
      useCases: [
        "Analyze image quality",
        "Extract image metrics",
        "Evaluate visual properties",
        "Assess image characteristics",
        "Generate quality reports"
      ],
      basicFields: ["image"]
    },
    "fal-ai/florence-2-large/region-to-description": {
      className: "Florence2RegionToDescription",
      docstring:
        "Florence-2 Large generates detailed descriptions of specific image regions.",
      tags: ["vision", "captioning", "region-description", "florence", "ocr"],
      useCases: [
        "Describe specific image regions",
        "Generate region captions",
        "Extract region information",
        "Annotate image areas",
        "Create detailed region descriptions"
      ],
      basicFields: ["image", "region"]
    },
    "fal-ai/florence-2-large/ocr": {
      className: "Florence2OCR",
      docstring:
        "Florence-2 Large performs optical character recognition to extract text from images.",
      tags: ["vision", "ocr", "text-extraction", "florence", "reading"],
      useCases: [
        "Extract text from images",
        "Read document images",
        "Digitize printed text",
        "Parse image text content",
        "Convert images to text"
      ],
      basicFields: ["image"]
    },
    "fal-ai/florence-2-large/more-detailed-caption": {
      className: "Florence2MoreDetailedCaption",
      docstring:
        "Florence-2 Large generates highly detailed, comprehensive image captions.",
      tags: [
        "vision",
        "captioning",
        "detailed-description",
        "florence",
        "analysis"
      ],
      useCases: [
        "Generate detailed image descriptions",
        "Create comprehensive captions",
        "Produce rich image narratives",
        "Analyze image content thoroughly",
        "Generate long-form descriptions"
      ],
      basicFields: ["image"]
    },
    "fal-ai/florence-2-large/region-to-category": {
      className: "Florence2RegionToCategory",
      docstring:
        "Florence-2 Large classifies image regions into semantic categories.",
      tags: [
        "vision",
        "classification",
        "region-analysis",
        "florence",
        "categorization"
      ],
      useCases: [
        "Classify image regions",
        "Categorize image areas",
        "Label image segments",
        "Identify region types",
        "Semantic region analysis"
      ],
      basicFields: ["image", "region"]
    },
    "fal-ai/florence-2-large/caption": {
      className: "Florence2Caption",
      docstring:
        "Florence-2 Large generates concise, accurate captions for images.",
      tags: ["vision", "captioning", "description", "florence", "analysis"],
      useCases: [
        "Generate image captions",
        "Create alt text for images",
        "Describe images concisely",
        "Automate image descriptions",
        "Produce accessibility captions"
      ],
      basicFields: ["image"]
    },
    "fal-ai/florence-2-large/detailed-caption": {
      className: "Florence2DetailedCaption",
      docstring:
        "Florence-2 Large generates detailed captions with rich contextual information.",
      tags: [
        "vision",
        "captioning",
        "detailed-description",
        "florence",
        "analysis"
      ],
      useCases: [
        "Generate detailed captions",
        "Create rich image descriptions",
        "Produce comprehensive captions",
        "Analyze image context",
        "Generate informative descriptions"
      ],
      basicFields: ["image"]
    },
    "fal-ai/omdet-turbo": {
      className: "OmDetTurbo",
      docstring:
        "OmDet Turbo performs fast object detection and classification in images.",
      tags: [
        "vision",
        "object-detection",
        "detection",
        "classification",
        "fast"
      ],
      useCases: [
        "Detect objects in images quickly",
        "Real-time object detection",
        "Fast image analysis",
        "Identify multiple objects",
        "Efficient object classification"
      ],
      basicFields: ["image"]
    },
    "fal-ai/owl-v2": {
      className: "OwlV2",
      docstring:
        "OWL-v2 performs open-vocabulary object detection using text queries.",
      tags: [
        "vision",
        "object-detection",
        "open-vocabulary",
        "owl",
        "detection"
      ],
      useCases: [
        "Detect objects by text description",
        "Open-vocabulary object detection",
        "Find arbitrary objects in images",
        "Query-based detection",
        "Flexible object identification"
      ],
      basicFields: ["image", "query"]
    },
    "fal-ai/vision/gpt4o": {
      className: "VisionGPT4O",
      docstring:
        "GPT-4O Vision provides advanced image understanding and analysis with language model reasoning.",
      tags: ["vision", "understanding", "gpt4", "multimodal", "analysis"],
      useCases: [
        "Analyze images with AI reasoning",
        "Answer questions about images",
        "Extract complex image information",
        "Understand image context",
        "Generate detailed image insights"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/vision/gpt4o-mini": {
      className: "VisionGPT4OMini",
      docstring:
        "GPT-4O Mini Vision provides efficient image understanding with reduced resource usage.",
      tags: [
        "vision",
        "understanding",
        "gpt4",
        "mini",
        "efficient",
        "analysis"
      ],
      useCases: [
        "Efficient image analysis",
        "Quick image understanding",
        "Cost-effective vision tasks",
        "Fast image reasoning",
        "Lightweight image processing"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/pixtral/large": {
      className: "PixtralLarge",
      docstring:
        "Pixtral Large provides powerful multimodal understanding for complex image analysis.",
      tags: ["vision", "understanding", "pixtral", "multimodal", "analysis"],
      useCases: [
        "Complex image analysis",
        "Detailed image understanding",
        "Advanced visual reasoning",
        "Comprehensive image interpretation",
        "Sophisticated image tasks"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/moondream/v2": {
      className: "MoondreamV2",
      docstring:
        "Moondream v2 provides efficient vision-language understanding for image analysis.",
      tags: ["vision", "understanding", "moondream", "efficient", "analysis"],
      useCases: [
        "Efficient image understanding",
        "Quick visual question answering",
        "Lightweight image analysis",
        "Fast image interpretation",
        "Compact vision model"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/llama-vision/free": {
      className: "LlamaVisionFree",
      docstring:
        "Llama Vision Free provides accessible vision-language understanding at no cost.",
      tags: [
        "vision",
        "understanding",
        "llama",
        "free",
        "multimodal",
        "analysis"
      ],
      useCases: [
        "Free image analysis",
        "Accessible vision tasks",
        "No-cost image understanding",
        "Budget-friendly vision processing",
        "Open access image reasoning"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/blip-2": {
      className: "BLIP2",
      docstring:
        "BLIP-2 provides vision-language understanding for image captioning and VQA.",
      tags: ["vision", "captioning", "vqa", "blip", "understanding"],
      useCases: [
        "Generate image captions",
        "Answer visual questions",
        "Image-text understanding",
        "Visual question answering",
        "Image description generation"
      ],
      basicFields: ["image"]
    },
    "fal-ai/deepseek-vl2": {
      className: "DeepSeekVL2",
      docstring:
        "DeepSeek VL2 provides advanced vision-language understanding with deep reasoning.",
      tags: ["vision", "understanding", "deepseek", "reasoning", "analysis"],
      useCases: [
        "Deep image analysis",
        "Advanced visual reasoning",
        "Complex image understanding",
        "Detailed image interpretation",
        "Sophisticated vision tasks"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/hunyuan-vision": {
      className: "HunyuanVision",
      docstring:
        "Hunyuan Vision provides powerful image understanding from Tencent.",
      tags: ["vision", "understanding", "hunyuan", "analysis", "tencent"],
      useCases: [
        "Comprehensive image analysis",
        "Advanced image understanding",
        "Visual content interpretation",
        "Image reasoning tasks",
        "Detailed visual analysis"
      ],
      basicFields: ["image", "prompt"]
    },
    "fal-ai/sam-3/image/embed": {
      className: "Sam3ImageEmbed",
      docstring: "Sam 3",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "openrouter/router/vision": {
      className: "OpenrouterRouterVision",
      docstring: "OpenRouter [Vision]",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "fal-ai/moondream3-preview/detect": {
      className: "Moondream3PreviewDetect",
      docstring: "Moondream3 Preview [Detect]",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "fal-ai/moondream3-preview/point": {
      className: "Moondream3PreviewPoint",
      docstring: "Moondream3 Preview [Point]",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "fal-ai/moondream3-preview/query": {
      className: "Moondream3PreviewQuery",
      docstring: "Moondream 3 Preview [Query]",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "fal-ai/moondream3-preview/caption": {
      className: "Moondream3PreviewCaption",
      docstring: "Moondream3 Preview [Caption]",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "perceptron/isaac-01/openai/v1/chat/completions": {
      className: "PerceptronIsaac01OpenaiV1ChatCompletions",
      docstring: "Isaac 0.1 [OpenAI Compatible Endpoint]",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Automated content generation",
        "Creative workflows",
        "Batch processing",
        "Professional applications",
        "Rapid prototyping"
      ]
    },
    "perceptron/isaac-01": {
      className: "PerceptronIsaac01",
      docstring:
        "Isaac-01 is a multimodal vision-language model from Perceptron for various vision language tasks.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/x-ailab/nsfw": {
      className: "XAilabNsfw",
      docstring: "Predict whether an image is NSFW or SFW.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/video-understanding": {
      className: "VideoUnderstanding",
      docstring:
        "A video understanding model to analyze video content and answer questions about what's happening in the video based on user prompts.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream2/visual-query": {
      className: "Moondream2VisualQuery",
      docstring:
        "Moondream2 is a highly efficient open-source vision language model that combines powerful image understanding capabilities with a remarkably small footprint.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream2": {
      className: "Moondream2",
      docstring:
        "Moondream2 is a highly efficient open-source vision language model that combines powerful image understanding capabilities with a remarkably small footprint.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream2/point-object-detection": {
      className: "Moondream2PointObjectDetection",
      docstring:
        "Moondream2 is a highly efficient open-source vision language model that combines powerful image understanding capabilities with a remarkably small footprint.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream2/object-detection": {
      className: "Moondream2ObjectDetection",
      docstring:
        "Moondream2 is a highly efficient open-source vision language model that combines powerful image understanding capabilities with a remarkably small footprint.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/got-ocr/v2": {
      className: "GotOcrV2",
      docstring:
        "GOT-OCR2 works on a wide range of tasks, including plain document OCR, scene text OCR, formatted document OCR, and even OCR for tables, charts, mathematical formulas, geometric shapes, molecular formulas and sheet music.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream-next/batch": {
      className: "MoondreamNextBatch",
      docstring:
        "MoonDreamNext Batch is a multimodal vision-language model for batch captioning.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/sa2va/4b/video": {
      className: "Sa2va4bVideo",
      docstring:
        "Sa2VA is an MLLM capable of question answering, visual prompt understanding, and dense object segmentation at both image and video levels",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/sa2va/8b/video": {
      className: "Sa2va8bVideo",
      docstring:
        "Sa2VA is an MLLM capable of question answering, visual prompt understanding, and dense object segmentation at both image and video levels",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/sa2va/4b/image": {
      className: "Sa2va4bImage",
      docstring:
        "Sa2VA is an MLLM capable of question answering, visual prompt understanding, and dense object segmentation at both image and video levels",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/sa2va/8b/image": {
      className: "Sa2va8bImage",
      docstring:
        "Sa2VA is an MLLM capable of question answering, visual prompt understanding, and dense object segmentation at both image and video levels",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream-next": {
      className: "MoondreamNext",
      docstring:
        "MoonDreamNext is a multimodal vision-language model for captioning, gaze detection, bbox detection, point detection, and more.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/imageutils/nsfw": {
      className: "ImageutilsNsfw",
      docstring: "Predict the probability of an image being NSFW.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/moondream/batched": {
      className: "MoondreamBatched",
      docstring: "Answer questions from the images.",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    },
    "fal-ai/llava-next": {
      className: "LlavaNext",
      docstring: "Vision",
      tags: ["vision", "analysis", "image-understanding", "detection"],
      useCases: [
        "Image analysis and understanding",
        "Object detection and recognition",
        "Visual content moderation",
        "Automated image captioning",
        "Scene understanding"
      ]
    }
  }
};
