/**
 * Registers the NodeTool native messaging host with the user's browsers.
 *
 * Chrome finds a native host through a JSON manifest in a per-browser
 * directory. The manifest points at a wrapper script, which pins the Node
 * binary and the host entry so Chrome does not depend on PATH.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { NATIVE_HOST_NAME } from "./bridge-paths.js";

/** The extension's ID, fixed by the `key` field in `chrome-extension/manifest.json`. */
export const EXTENSION_ID = "acnankgjnlmpbjcpebmelmognbnnhigb";

const BROWSER_DATA_DIRS: Record<string, string[]> = {
  darwin: [
    "Library/Application Support/Google/Chrome",
    "Library/Application Support/Chromium",
    "Library/Application Support/BraveSoftware/Brave-Browser",
    "Library/Application Support/Microsoft Edge",
    "Library/Application Support/Arc/User Data"
  ],
  linux: [
    ".config/google-chrome",
    ".config/chromium",
    ".config/BraveSoftware/Brave-Browser",
    ".config/microsoft-edge"
  ]
};

export interface InstallNativeHostOptions {
  /** Node binary the wrapper runs. Defaults to the current one. */
  nodePath?: string;
  /** Host entry script. Defaults to the built `native-host-bin.js` beside this module. */
  hostScript?: string;
  /** Home directory. Defaults to `os.homedir()`. */
  home?: string;
}

export interface InstallNativeHostResult {
  wrapperPath: string;
  manifests: string[];
}

/** Directories (one per installed browser) that hold native host manifests. */
export function nativeHostManifestDirs(home = os.homedir()): string[] {
  const roots = BROWSER_DATA_DIRS[process.platform] ?? [];
  return roots
    .map((root) => path.join(home, root))
    .filter((dir) => fs.existsSync(dir))
    .map((dir) => path.join(dir, "NativeMessagingHosts"));
}

/**
 * The built host entry. Next to this module when running from `dist`; under a
 * source run (tsx) it lives in the package's `dist` folder instead.
 */
function resolveHostScript(): string {
  const sibling = fileURLToPath(new URL("./native-host-bin.js", import.meta.url));
  if (fs.existsSync(sibling)) return sibling;
  return fileURLToPath(new URL("../../dist/extension/native-host-bin.js", import.meta.url));
}

export function installNativeHost(options: InstallNativeHostOptions = {}): InstallNativeHostResult {
  if (process.platform === "win32") {
    throw new Error("Installing the native host on Windows needs a registry entry, which is not supported yet");
  }
  const home = options.home ?? os.homedir();
  const hostScript = options.hostScript ?? resolveHostScript();
  if (!fs.existsSync(hostScript)) {
    throw new Error(`Native host entry not found at ${hostScript}. Run npm run build:packages first`);
  }
  const nodePath = options.nodePath ?? process.execPath;

  const wrapperDir = path.join(home, ".nodetool", "browser-bridge");
  fs.mkdirSync(wrapperDir, { recursive: true });
  const wrapperPath = path.join(wrapperDir, "native-host");
  fs.writeFileSync(
    wrapperPath,
    `#!/bin/sh\n# Generated by \`nodetool extension install\`. Do not edit.\nexec "${nodePath}" "${hostScript}"\n`,
    { mode: 0o755 }
  );

  const manifest = JSON.stringify(
    {
      name: NATIVE_HOST_NAME,
      description: "NodeTool browser bridge",
      path: wrapperPath,
      type: "stdio",
      allowed_origins: [`chrome-extension://${EXTENSION_ID}/`]
    },
    null,
    2
  );
  const manifests: string[] = [];
  for (const dir of nativeHostManifestDirs(home)) {
    fs.mkdirSync(dir, { recursive: true });
    const file = path.join(dir, `${NATIVE_HOST_NAME}.json`);
    fs.writeFileSync(file, manifest);
    manifests.push(file);
  }
  if (manifests.length === 0) {
    throw new Error("No supported browser profile directory found (Chrome, Chromium, Brave, Edge or Arc)");
  }
  return { wrapperPath, manifests };
}
