/** @jsxImportSource @emotion/react */
/**
 * Standalone entry for the app-builder preview page (marketing screenshots).
 * Renders one shipped example app with seeded demo values — no backend, no
 * WebSocket. The app is chosen with ?slug=<app-slug>; preview bundles are
 * served from /app-preview/<slug>.json (generated by
 * scripts/build-example-apps.mjs).
 */
import ReactDOM from "react-dom/client";

import "../styles/base.css";
import "@puckeditor/core/puck.css";

import AppPreviewApp from "./AppPreviewApp";

const root = ReactDOM.createRoot(document.getElementById("root")!);
root.render(<AppPreviewApp />);
