/** @jsxImportSource @emotion/react */
/**
 * Standalone entry for the app-builder preview page (marketing screenshots).
 * Renders one template's mini app with seeded demo values — no backend, no
 * WebSocket. The template is chosen with ?slug=<template-slug>; bundles are
 * served from /app-preview/<slug>.json (generated by
 * scripts/generate-template-apps.mjs).
 */
import ReactDOM from "react-dom/client";

import "../styles/base.css";
import "@puckeditor/core/puck.css";

import AppPreviewApp from "./AppPreviewApp";

const root = ReactDOM.createRoot(document.getElementById("root")!);
root.render(<AppPreviewApp />);
