/** @jsxImportSource @emotion/react */
import { memo, useCallback } from "react";
import { css } from "@emotion/react";
import { useTheme } from "@mui/material/styles";
import type { Theme } from "@mui/material/styles";
import BugReportIcon from "@mui/icons-material/BugReport";
import {
  nodeErrorToDisplayString,
  hasNodeError,
} from "../../stores/ErrorStore";
import useErrorStore from "../../stores/ErrorStore";
import useLogsStore, { nodeLogKey } from "../../stores/LogStore";
import isEqual from "fast-deep-equal";
import { CopyButton, Tooltip } from "../ui_primitives";
import { VERSION } from "../../config/constants";

const GITHUB_ISSUE_URL =
  "https://github.com/nodetool-ai/nodetool/issues/new";

const REPORT_LINES = 100;

/** Build a pre-filled GitHub new-issue URL. */
function buildReportUrl(
  nodeType: string,
  errorText: string,
  logLines: string[],
  systemInfo: string
): string {
  const title = `[Bug] Node "${nodeType}" error: ${errorText.split("\n")[0].slice(0, 80)}`;

  const lastLogs =
    logLines.length > 0
      ? logLines.slice(-REPORT_LINES).join("\n")
      : "(no logs captured)";

  const body = `## Node Error Report

**Node type:** \`${nodeType}\`
**NodeTool version:** ${VERSION}

### Error

\`\`\`
${errorText}
\`\`\`

### System Information

\`\`\`
${systemInfo}
\`\`\`

### Last ${REPORT_LINES} log lines

\`\`\`
${lastLogs}
\`\`\`

---
*Automatically generated by the "Report this issue" button in NodeTool.*
`;

  const params = new URLSearchParams({
    title,
    body,
    labels: "bug",
  });

  return `${GITHUB_ISSUE_URL}?${params.toString()}`;
}

/** Gather browser / OS system information. */
function getSystemInfo(): string {
  const lines: string[] = [
    `Browser: ${navigator.userAgent}`,
    `Platform: ${navigator.platform}`,
    `Language: ${navigator.language}`,
    `Screen: ${window.screen.width}x${window.screen.height} (devicePixelRatio: ${window.devicePixelRatio})`,
    `NodeTool version: ${VERSION}`,
  ];
  return lines.join("\n");
}

const errorStyles = (theme: Theme) =>
  css({
    position: "relative",
    backgroundColor: theme.vars.palette.error.main,
    borderRadius: "1px",
    padding: "10px",
    transition: "background-color 0.2s",
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: "100%",

    ".error-text": {
      width: "100%",
      maxHeight: "18em",
      fontFamily: theme.fontFamily1,
      fontSize: theme.fontSizeSmaller,
      color: theme.vars.palette.grey[1000],
      cursor: "auto",
      userSelect: "text",
      lineHeight: "1.2em",
      padding: "0.5em .2em 0 0",
      whiteSpace: "pre-wrap",
      overflowWrap: "anywhere",
      wordBreak: "break-word",
      overflowY: "auto",
      "&::selection": {
        backgroundColor: theme.vars.palette.grey[0]
      }
    },
    ".error-actions": {
      display: "flex",
      alignItems: "center",
      gap: "4px",
      position: "absolute",
      top: 10,
      right: 10,
    },
    ".report-button": {
      display: "inline-flex",
      alignItems: "center",
      gap: "4px",
      padding: "2px 8px",
      borderRadius: "4px",
      border: `1px solid ${theme.vars.palette.grey[1000]}44`,
      backgroundColor: "transparent",
      color: theme.vars.palette.grey[1000],
      fontSize: theme.fontSizeSmaller,
      cursor: "pointer",
      textDecoration: "none",
      lineHeight: "1.4",
      "&:hover": {
        backgroundColor: `${theme.vars.palette.grey[1000]}22`,
      },
    },
  });

export const NodeErrors: React.FC<{
  id: string;
  workflow_id: string;
  nodeType?: string;
}> = ({ id, workflow_id, nodeType = "unknown" }) => {
  const theme = useTheme();
  const error = useErrorStore((state) =>
    workflow_id !== undefined ? state.getError(workflow_id, id) : undefined
  );

  const logs = useLogsStore(
    (state) => state.logsByNode[nodeLogKey(workflow_id, id)]
  );

  const handleReport = useCallback(() => {
    const errorText = nodeErrorToDisplayString(error);
    const logLines = (logs ?? []).map(
      (l) => `[${l.severity.toUpperCase()}] ${l.content}`
    );
    const url = buildReportUrl(
      nodeType,
      errorText,
      logLines,
      getSystemInfo()
    );
    window.open(url, "_blank", "noopener,noreferrer");
  }, [error, logs, nodeType]);

  if (!hasNodeError(error)) {
    return null;
  }

  const errorDisplay = nodeErrorToDisplayString(error);

  return (
    <div css={errorStyles(theme)} className="node-error nodrag nowheel">
      <div className="error-actions">
        <Tooltip title="Report this issue on GitHub">
          <button
            className="report-button nodrag"
            onClick={handleReport}
            tabIndex={-1}
            aria-label="Report this issue on GitHub"
          >
            <BugReportIcon sx={{ fontSize: "0.9em" }} />
            Report
          </button>
        </Tooltip>
        <CopyButton
          value={errorDisplay}
          tooltip="Copy to clipboard"
          tabIndex={-1}
        />
      </div>
      <div className="error-text">{errorDisplay}</div>
    </div>
  );
};

export default memo(NodeErrors, isEqual);