name: Claude PR Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate critique with Claude
        id: critique
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: "Provide a short critique of this pull request. Point out potential issues, unclear changes, and suggestions for improvement."
          allowed_tools: "Bash(git diff --name-only HEAD~1),Bash(git diff HEAD~1),View,GlobTool,GrepTool,Write"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Comment critique on PR
        if: steps.critique.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const executionFile = '${{ steps.critique.outputs.execution_file }}';
            const executionLog = JSON.parse(fs.readFileSync(executionFile, 'utf8'));

            let critique = '';
            for (let i = executionLog.length - 1; i >= 0; i--) {
              if (executionLog[i].role === 'assistant') {
                critique = executionLog[i].content;
                break;
              }
            }

            if (critique) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## Claude Critique\n\n' + critique + '\n\n*Generated by Claude*'
              });
            }
