name: Conda Pack

on:
  push:
    tags:
      - "v*"
    paths:
      - "requirements.txt"

jobs:
  pack-conda-env:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      PYTHON_VERSION: "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Free Disk Space
        if: matrix.os == 'ubuntu-latest'
        uses: jlumbroso/free-disk-space@main

      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Pack Conda Environment
        shell: bash -l {0}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        run: |
          python build.py pack
