name: Conda

on:
  push:
    tags:
      - "v*"

jobs:
  pack-conda-env:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      PYTHON_VERSION: "3.11"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Free Disk Space
        if: matrix.os == 'ubuntu-latest'
        uses: jlumbroso/free-disk-space@main

      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Pack Conda Environment
        shell: bash -l {0}
        # env:
        #   S3_PACKAGES_ENDPOINT_URL: ${{ secrets.S3_PACKAGES_ENDPOINT_URL }}
        #   AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        #   AWS_REGION: auto
        run: |
          python build.py pack

      - name: Upload Conda Environment
        uses: actions/upload-artifact@v3
        with:
          name: conda-environments
          path: |
            build/conda-env-*.tar.gz
            build/conda-env-*.zip
            build/requirements-*.txt
