name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - "electron/**"
  pull_request:
    branches:
      - main
    paths:
      - "web/**"
      - "electron/**"

jobs:
  web-type:
    name: Web Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install web dependencies
        run: |
          cd web
          npm ci

      - name: Run TypeScript type check
        run: |
          cd web
          npx tsc --noEmit

      - name: Run ESLint
        run: |
          cd web
          npx eslint .

  electron-type:
    name: Electron Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install electron dependencies
        run: |
          cd electron
          npm ci

      - name: Run TypeScript type check
        run: |
          cd electron
          npm run typecheck

      - name: Run ESLint
        run: |
          cd electron
          npx eslint .

  mini-apps:
    name: Apps Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install mini apps dependencies
        run: |
          cd apps
          npm ci

      - name: Run ESLint
        run: |
          cd apps
          npx eslint .
