name: Package and Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          # - os: ubuntu-latest
          #   platform: linux
          #   arch: x64
          - os: macos-latest
            platform: mac
            arch: arm64
          - os: windows-latest
            platform: win
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.11"

      - name: Set up build tools
        shell: bash -l {0}
        run: |
          python build.py --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --step setup

      - name: Package python
        shell: bash -l {0}
        run: |
          python build.py --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --step python

      - name: Package react
        shell: bash -l {0}
        run: |
          python build.py --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --step react

      - name: Package electron
        shell: bash -l {0}
        run: |
          python build.py --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} --step electron

      - name: Find release assets
        id: find_assets
        shell: bash
        run: |
          assets=$(find build -type f \( -name "*.tar" -o -name "*.dmg" -o -name "*.exe" -o -name "*.zip" \))
          echo "assets=$assets" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.asset }}
          asset_name: ${{ basename(matrix.asset) }}
          asset_content_type: application/octet-stream
        strategy:
          matrix:
            asset: ${{ steps.find_assets.outputs.assets }}
