name: Package and Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: release
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: nodetool

      - name: Install Poetry and Conda-Pack
        shell: bash -el {0}
        run: |
          conda install -c conda-forge conda-pack

      - name: Install Packages
        shell: bash -el {0}
        run: |
          pip install 'nodetool[worker]'

      - name: Pack Conda Environment
        shell: bash -el {0}
        run: |
          conda-pack -n nodetool -o nodetool.tar.gz

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          artifacts: nodetool.tar.gz
