name: Package and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: nodetool

      - name: Install Poetry and Conda-Pack
        shell: bash -el {0}
        run: |
          conda install -c conda-forge conda-pack

      - name: Install Packages
        shell: bash -el {0}
        run: |
          pip install 'nodetool[worker]'

      - name: Pack Conda Environment
        shell: bash -el {0}
        run: |
          conda-pack -n nodetool -o nodetool.tar.gz

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: nodetool.tar.gz
