name: Package and Release

on:
  push:
    main:
      - "*"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          # - os: ubuntu-latest
          #   platform: linux
          #   arch: x64
          - os: macos-latest
            platform: mac
            arch: arm64
          # - os: windows-latest
          #   platform: win
          #   arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.11"

      - name: Run build script
        shell: bash -l {0}
        run: |
          python build.py --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nodetool-${{ matrix.platform }}-${{ matrix.arch }}
          path: build/build/electron-app/*.{dmg,exe,AppImage,tar.gz}

        # - name: Create Release
        #   uses: ncipollo/release-action@v1
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   with:
        #     draft: false
        #     prerelease: false
        #     artifacts: nodetool-${{matrix.os}}.tar.gz
