name: Type Check

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - "src/**"
      - "electron/**"
  pull_request:
    branches:
      - main
    paths:
      - "web/**"
      - "src/**"
      - "electron/**"

jobs:
  web-type-check:
    name: Web TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install web dependencies
        run: |
          cd web
          npm install

      - name: Run TypeScript type check
        run: |
          cd web
          npx tsc --noEmit

  electron-type-check:
    name: Electron TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install electron dependencies
        run: |
          cd electron
          npm install

      - name: Run TypeScript type check
        run: |
          cd electron
          npm run typecheck
