name: Type Check

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  pull_request:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Run TypeScript type check
        run: |
          cd web
          npx tsc --noEmit
