import { defineConfig, loadEnv, type Plugin, type ProxyOptions, type UserConfig } from "vite";
import react from "@vitejs/plugin-react";
import svgr from "vite-plugin-svgr";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const configDir = dirname(fileURLToPath(import.meta.url));
const rootNodeModules = resolve(configDir, "../node_modules");

// The in-browser workflow runner (web/src/lib/workflow/browserWorkflowRunner.ts)
// lazily imports @nodetool-ai/workflow-runner + @nodetool-ai/base-nodes so a
// pure-browser sub-graph can execute client-side. Those packages (via the
// kernel/runtime) statically import `node:*` built-ins for their server code
// paths. Browser-tagged execution never reaches them, but the bundler must
// still resolve the specifiers — map each to a browser-safe stub. Mirrors the
// workflow-runner e2e harness config.
const NODE_STUBS = resolve(configDir, "vite-node-stubs");
const NODE_BUILTIN_STUBS: Record<string, string> = {
  "node:fs/promises": `${NODE_STUBS}/fs-promises-stub.js`,
  "node:fs": `${NODE_STUBS}/fs-stub.js`,
  "node:path": `${NODE_STUBS}/path-stub.js`,
  "node:url": `${NODE_STUBS}/url-stub.js`,
  "node:crypto": `${NODE_STUBS}/crypto-stub.js`,
  "node:os": `${NODE_STUBS}/os-stub.js`,
  "node:events": `${NODE_STUBS}/events-stub.js`,
  "node:child_process": `${NODE_STUBS}/child-process-stub.js`,
  "node:worker_threads": `${NODE_STUBS}/empty.js`,
  "node:cluster": `${NODE_STUBS}/empty.js`,
  "node:dgram": `${NODE_STUBS}/empty.js`,
  "node:dns": `${NODE_STUBS}/empty.js`,
  "node:net": `${NODE_STUBS}/empty.js`,
  "node:tls": `${NODE_STUBS}/empty.js`,
  "node:zlib": `${NODE_STUBS}/empty.js`,
  "node:http": `${NODE_STUBS}/empty.js`,
  "node:https": `${NODE_STUBS}/empty.js`,
  "node:http2": `${NODE_STUBS}/empty.js`,
  "node:perf_hooks": `${NODE_STUBS}/empty.js`,
  "node:vm": `${NODE_STUBS}/empty.js`,
  "node:stream": `${NODE_STUBS}/empty.js`,
  "node:async_hooks": `${NODE_STUBS}/empty.js`,
  "node:util": `${NODE_STUBS}/empty.js`,
  "node:buffer": `${NODE_STUBS}/empty.js`,
  "node:assert": `${NODE_STUBS}/empty.js`,
  "node:process": `${NODE_STUBS}/empty.js`,
  "node:module": `${NODE_STUBS}/empty.js`
};

// Vite's `resolve.alias` doesn't intercept the `node:` protocol — these imports
// bypass the alias plugin and hit the default resolver. Catch them in a `pre`
// resolveId hook before any other plugin runs.
function stubNodeProtocolPlugin(): Plugin {
  return {
    name: "stub-node-protocol",
    enforce: "pre",
    resolveId(source) {
      return NODE_BUILTIN_STUBS[source] ?? null;
    }
  };
}

export default defineConfig(async ({ mode }) => {
  // Load all env vars (including non-VITE_ prefixed ones) for server-side config
  const env = loadEnv(mode, configDir, "");
  const browserslistToEsbuild = (await import("browserslist-to-esbuild"))
    .default;
  const isDebug = mode === "debug";

  const apiTarget = env.PROXY_API_TARGET || "http://localhost:7777";
  const proxyConfig: Record<string, ProxyOptions> = {
    "/api": {
      target: apiTarget,
      changeOrigin: true,
      secure: false
    },
    "/ws": {
      target: apiTarget,
      ws: true,
      changeOrigin: true
    },
    "/trpc": {
      target: apiTarget,
      changeOrigin: true,
      secure: false
    },
    "/storage": {
      target: apiTarget,
      changeOrigin: true,
      secure: false,
      rewrite: (path) => path.replace(/^\/storage/, "/api/storage")
    }
  };

  return {
    server: {
      allowedHosts: [".nodetool.ai", "localhost"],
      port: 3000,
      proxy: proxyConfig
    },
    optimizeDeps: {
      include: [
        "superjson",
        "@trpc/client",
        "@trpc/react-query",
        "@tanstack/react-query",
      ],
      exclude: [
        "monaco-editor",
        "@monaco-editor/react",
        "@monaco-editor/loader",
      ]
    },
    resolve: {
      // Use the `nodetool-dev` export condition so @nodetool-ai/* packages
      // resolve to their `src/*.ts` sources instead of built `dist/*.js`.
      // This is the repo-wide convention declared in each package's exports.
      conditions: ["nodetool-dev", "import", "module", "browser", "default"],
      alias: {
        "monaco-editor": resolve(rootNodeModules, "monaco-editor"),
        // FAL pricing bundles generated by `packages/fal-codegen` and consumed
        // by `web/src/utils/attachBundleFalUnitPricing.ts`. Declared as ambient
        // modules in `web/src/fal-*.d.ts`.
        "@nodetool/fal-node-type-pricing": resolve(
          configDir,
          "../packages/fal-nodes/src/generated/fal-node-type-pricing.json"
        ),
        "@nodetool/fal-unit-pricing-catalog": resolve(
          configDir,
          "../packages/fal-nodes/src/generated/fal-unit-pricing.json"
        ),
        "@nodetool/kie-node-type-pricing": resolve(
          configDir,
          "../packages/kie-nodes/src/generated/kie-node-type-pricing.json"
        ),
        "@nodetool/kie-unit-pricing-catalog": resolve(
          configDir,
          "../packages/kie-nodes/src/generated/kie-unit-pricing.json"
        ),
      },
    },
    plugins: [
      stubNodeProtocolPlugin(),
      react({
        jsxImportSource: "@emotion/react",
        babel: {
          plugins: ["@emotion/babel-plugin"]
        }
      }),
      svgr()
    ],
    build: {
      // Note: `not ios < 14` excludes iOS 11–13. esbuild (via vite 8 / rolldown
      // worker bundling) cannot downlevel certain destructuring patterns in
      // monaco-editor's pre-bundled workers to those ancient targets.
      target: browserslistToEsbuild([">0.2%", "not dead", "not op_mini all", "not ios < 14"]),
      sourcemap: true,
      minify: isDebug ? false : "esbuild",
      ...(isDebug
        ? {}
        : {
            rollupOptions: {
              external: ["web-worker"],
              output: {
                manualChunks(id) {
                  if (!id.includes("node_modules")) return;
                  if (
                    /[\\/]node_modules[\\/](react|react-dom|react-router-dom|react-router|scheduler)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-react";
                  if (
                    /[\\/]node_modules[\\/](@mui[\\/]material|@mui[\\/]icons-material|@mui[\\/]system|@mui[\\/]base|@emotion[\\/]react|@emotion[\\/]styled|@emotion[\\/]cache|@emotion[\\/]serialize|@emotion[\\/]utils|@emotion[\\/]hash)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-mui";
                  if (/[\\/]node_modules[\\/]@mui[\\/]x-/.test(id))
                    return "vendor-mui-x";
                  if (
                    /[\\/]node_modules[\\/](react-plotly\.js|plotly\.js)[\\/]/.test(id)
                  )
                    return "vendor-plotly";
                  if (
                    /[\\/]node_modules[\\/](three|@react-three[\\/]fiber|@react-three[\\/]drei)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-three";
                  if (
                    /[\\/]node_modules[\\/](@monaco-editor[\\/]react|monaco-editor|lexical|@lexical)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-editor";
                  if (
                    /[\\/]node_modules[\\/](react-pdf|pdfjs-dist)[\\/]/.test(id)
                  )
                    return "vendor-pdf";
                  if (/[\\/]node_modules[\\/]wavesurfer\.js[\\/]/.test(id))
                    return "vendor-waveform";
                  // Workflow graph engine + layout
                  if (
                    /[\\/]node_modules[\\/](@xyflow|elkjs)[\\/]/.test(id)
                  )
                    return "vendor-flow";
                  // Server state + RPC stack (must stay together — shared runtime)
                  if (
                    /[\\/]node_modules[\\/](@tanstack|@trpc|superjson|@msgpack)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-query";
                  // Markdown / unified ecosystem (all must live together — shared
                  // unified processor state, hast/mdast types, and micromark
                  // extension registry).
                  if (
                    /[\\/]node_modules[\\/](react-markdown|remark-[^\\/]+|rehype-[^\\/]+|micromark[^\\/]*|mdast-util-[^\\/]+|hast-util-[^\\/]+|unified|unist-util-[^\\/]+|vfile[^\\/]*|bail|trough|is-plain-obj|decode-named-character-reference|character-entities[^\\/]*|html-void-elements|property-information|space-separated-tokens|comma-separated-tokens|web-namespaces|zwitch|longest-streak|parse-entities|ccount|escape-string-regexp|markdown-table|github-slugger|stringify-entities|html-url-attributes|dompurify|prismjs|react-syntax-highlighter|refractor)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-markdown";
                  // Data table + spreadsheet/zip libs
                  if (
                    /[\\/]node_modules[\\/](tabulator-tables|jszip|papaparse|read-excel-file|xlsx)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-data";
                  // Panel layout
                  if (/[\\/]node_modules[\\/]dockview[\\/]/.test(id))
                    return "vendor-dockview";
                  // Supabase client
                  if (/[\\/]node_modules[\\/]@supabase[\\/]/.test(id))
                    return "vendor-supabase";
                  // Search / command palette / small utilities cluster
                  if (
                    /[\\/]node_modules[\\/](cmdk|fuse\.js|chroma-js|zundo|date-fns|uuid|zod|fast-deep-equal|acorn-walk)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-utils";
                  // Static icon set (large SVG payload)
                  if (/[\\/]node_modules[\\/]@lobehub[\\/]/.test(id))
                    return "vendor-icons";
                  // Leave other dependencies unmatched so Rollup can apply
                  // its default chunking strategy instead of forcing a single
                  // shared misc vendor chunk.
                  return;
                }
              }
            }
          })
    }
  } satisfies UserConfig;
});
