import { defineConfig, loadEnv, type ProxyOptions, type UserConfig } from "vite";
import react from "@vitejs/plugin-react";
import svgr from "vite-plugin-svgr";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const configDir = dirname(fileURLToPath(import.meta.url));
const rootNodeModules = resolve(configDir, "../node_modules");

export default defineConfig(async ({ mode }) => {
  // Load all env vars (including non-VITE_ prefixed ones) for server-side config
  const env = loadEnv(mode, configDir, "");
  const browserslistToEsbuild = (await import("browserslist-to-esbuild"))
    .default;
  const isDebug = mode === "debug";

  const apiTarget = env.PROXY_API_TARGET || "http://localhost:7777";
  const proxyConfig: Record<string, ProxyOptions> = {
    "/api": {
      target: apiTarget,
      changeOrigin: true,
      secure: false
    },
    "/comfy-api": {
      target: "http://localhost:8000",
      changeOrigin: true,
      secure: false,
      ws: true,
      rewrite: (path) => path.replace(/^\/comfy-api/, "/api")
    },
    "/ws": {
      target: apiTarget,
      ws: true,
      changeOrigin: true
    },
    "/trpc": {
      target: apiTarget,
      changeOrigin: true,
      secure: false
    },
    "/storage": {
      target: apiTarget,
      changeOrigin: true,
      secure: false,
      rewrite: (path) => path.replace(/^\/storage/, "/api/storage")
    }
  };

  return {
    server: {
      allowedHosts: [".nodetool.ai", "localhost"],
      port: 3000,
      proxy: proxyConfig
    },
    optimizeDeps: {
      include: [
        "superjson",
        "@trpc/client",
        "@trpc/react-query",
        "@trpc/server",
        "@tanstack/react-query",
      ],
      exclude: [
        "monaco-editor",
        "@monaco-editor/react",
        "@monaco-editor/loader",
      ]
    },
    resolve: {
      // Use the `nodetool-dev` export condition so @nodetool-ai/* packages
      // resolve to their `src/*.ts` sources instead of built `dist/*.js`.
      // This is the repo-wide convention declared in each package's exports.
      conditions: ["nodetool-dev", "import", "module", "browser", "default"],
      alias: {
        "monaco-editor": resolve(rootNodeModules, "monaco-editor"),
        // FAL pricing bundles generated by `packages/fal-codegen` and consumed
        // by `web/src/utils/attachBundleFalUnitPricing.ts`. Declared as ambient
        // modules in `web/src/fal-*.d.ts`.
        "@nodetool/fal-node-type-pricing": resolve(
          configDir,
          "../packages/fal-nodes/src/generated/fal-node-type-pricing.json"
        ),
        "@nodetool/fal-unit-pricing-catalog": resolve(
          configDir,
          "../packages/fal-nodes/src/generated/fal-unit-pricing.json"
        ),
        "@nodetool/kie-node-type-pricing": resolve(
          configDir,
          "../packages/kie-nodes/src/generated/kie-node-type-pricing.json"
        ),
        "@nodetool/kie-unit-pricing-catalog": resolve(
          configDir,
          "../packages/kie-nodes/src/generated/kie-unit-pricing.json"
        ),
      },
    },
    plugins: [
      react({
        jsxImportSource: "@emotion/react",
        babel: {
          plugins: ["@emotion/babel-plugin"]
        }
      }),
      svgr()
    ],
    build: {
      // Note: `not ios < 14` excludes iOS 11–13. esbuild (via vite 8 / rolldown
      // worker bundling) cannot downlevel certain destructuring patterns in
      // monaco-editor's pre-bundled workers to those ancient targets.
      target: browserslistToEsbuild([">0.2%", "not dead", "not op_mini all", "not ios < 14"]),
      sourcemap: true,
      minify: isDebug ? false : "esbuild",
      ...(isDebug
        ? {}
        : {
            rollupOptions: {
              external: ["web-worker"],
              output: {
                manualChunks(id) {
                  if (!id.includes("node_modules")) return;
                  if (
                    /[\\/]node_modules[\\/](react|react-dom|react-router-dom|react-router|scheduler)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-react";
                  if (
                    /[\\/]node_modules[\\/](@mui[\\/]material|@mui[\\/]icons-material|@mui[\\/]system|@mui[\\/]base|@emotion[\\/]react|@emotion[\\/]styled|@emotion[\\/]cache|@emotion[\\/]serialize|@emotion[\\/]utils|@emotion[\\/]hash)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-mui";
                  if (
                    /[\\/]node_modules[\\/](react-plotly\.js|plotly\.js)[\\/]/.test(id)
                  )
                    return "vendor-plotly";
                  if (
                    /[\\/]node_modules[\\/](three|@react-three[\\/]fiber|@react-three[\\/]drei)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-three";
                  if (
                    /[\\/]node_modules[\\/](@monaco-editor[\\/]react|lexical)[\\/]/.test(
                      id
                    )
                  )
                    return "vendor-editor";
                  if (
                    /[\\/]node_modules[\\/](react-pdf|pdfjs-dist)[\\/]/.test(id)
                  )
                    return "vendor-pdf";
                  if (/[\\/]node_modules[\\/]wavesurfer\.js[\\/]/.test(id))
                    return "vendor-waveform";
                }
              }
            }
          })
    }
  } satisfies UserConfig;
});
